### ISSUE TITLE
Qt Web Assembly support

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#100]
Hello! Will this library support Qt Web Assembly? 
I think, that conditions should be modified like this:

    if (NOT WIN32 AND NOT APPLE AND NOT EMSCRIPTEN)
        find_dependency(Qt5X11Extras REQUIRED)
    endif()

**Comment by iamsergio** [comment]
does it then build 100% ?
and does it work ?

**Comment by iamsergio** [comment]
It runs now.
Not sure I recommend it though, dragging seems sluggish
