### ISSUE TITLE
It would be nice to be able to pin a floating window

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#102]
Using minimizable floating windows it would be nice if one could pin a window to have it always stay in front of the mainwindow.

**Comment by iamsergio** [comment]
Can you try Flag_KeepAboveIfNotUtilityWindow ?

If this is not good enough, check my last comment on issue #98 , copy that pure Qt non-KDDW code snippet and modify it to show what you need, and I'll implement an flag to expose that behaviour (if not too hacky)

**Comment by pklaffert** [comment]
The flags seem to be global. To be useful it would be great to be able to change the keep in front state on the fly for single floating windows.
I try to generate a mockup the following days to make it more clear.

**Comment by iamsergio** [comment]
ok, just reopen this when you have a mockup

Note that this is very "window manager dependent".
I can however expose needed api for users to implement workarounds on their on code, for the platforms they care about
