### ISSUE TITLE
Drop Indicators do not appear

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#103]
Hi Sergio, 

at times the drop indicators do not appear, this happens, at times and not every time.

Please find the gif attached.
![DropIndicatorBug](https://user-images.githubusercontent.com/8441461/99529817-bac65b80-29a0-11eb-95f6-6b9586bc30db.gif)

If you need more information, please feel free to write back.

Kind Regards
Nandish

**Comment by ruilvo** [comment]
I've found that using `KDDockWidgets::Config::Flag::Flag_NativeTitleBar` on Windows 10 makes so that the drop indicators never appear. I'm using latest from master as of today.

**Comment by nandishnan4** [comment]
Hi Rui,

i do not understand, if you are trying to explain another bug here in the same ticket or if you are trying to comment on the bug #103.

Regards
Nandish

**Comment by ruilvo** [comment]
Hello Nandish,

I was commenting on something that could be related behaviour. But you're definitely right and I should raise another ticket. 

Regards, 
Rui

**Comment by iamsergio** [comment]
Is this still repro with the latest ? (git pull today's changes)

**Comment by nandishnan4** [comment]
> 
> 
> Is this still repro with the latest ? (git pull today's changes)

Hi Sergio,
yes the problem still exists, I did pull on Friday 11.12.2020. 
![DropIndicatorsNotVisible](https://user-images.githubusercontent.com/8441461/102091974-cbdb7e80-3e1f-11eb-8fd5-345721c22000.gif)

Kind Regards
Nandish

**Comment by mateoconlechuga** [comment]
I am also able to reproduce this. It seems to mainly appear on windows as far as I can tell, and appears to be caused by the main window not having losing focus when the floating widget is selected. Clicking the main window allows the indicators to reappear.

**Comment by iamsergio** [comment]
@ruilvo your issue is fixed too
