### ISSUE TITLE
Minimize button doesn't work under XMing + X11 + putty

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#104]
System: 
* Windows 10 (Host)
* putty
* XMing 7.7.0.60
* Ubuntu 18.04
* Qt 5.15.1

Steps to reproduce:
* Start+Login the putty session to ubuntu
* Start kddockwidgets_example -k
* Observe the floating windows have minimize buttons
* Click on the minimize buttons
* Observe nothing happens

My first idea was, that we used a too old xming version (7.7.0.45). Hence I updated XMing to 7.7.0.60. But it doesn't help.
The start parameters for XMing are:
```
echo @off

rem call "C:\Program Files\Xming\XMing.exe" :0 -clipboard -multiwindow

set X11WINDOWNUM=38
call "C:\Tools\XMing\7.7.0.60\Xming.exe" :%X11WINDOWNUM% -multiwindow -clipboard -nolisten inet6 +bs -dpi 108 -xkblayout de -xkbmodel pc105 -xkbvariant nodeadkeys
set DISPLAY=127.0.0.1:%X11WINDOWNUM%.0

exit 0
```

![minimize_bug_xming_x11](https://user-images.githubusercontent.com/3143027/99692625-cc842d80-2a8a-11eb-914e-1e2cd72a8374.gif)

Greetings,
Thomas

**Comment by iamsergio** [comment]
Does the following app minimizes in that setup ?

```
#include <QtWidgets>

int main(int a, char **b)
{
    QApplication app(a, b);

    QPushButton button("Minimize");
    button.setWindowFlag(Qt::FramelessWindowHint);
    QObject::connect(&button, &QPushButton::clicked, [&button] {
        qDebug() << "About to minimize";
        button.showMinimized();
    });

    button.show();

    return app.exec();
}
```

**Comment by tlaemmlein** [comment]
I see it is a qt bug. I added a comment to the qt bug tracker: https://bugreports.qt.io/browse/QTBUG-45212.
