### ISSUE TITLE
Minimizing docking panels

### ISSUE THREAD

**Issue by smallB007** [KDAB/KDDockWidgets#105]
Hi, if I'm not mistaken, at the moment there isn't functionality to minimize docking panel so it is still visible, minimized in form of a "tile" and placed on the side to which it was docked. Visual Studio is the best example of it.
I believe that this feature would be desirable to have by many users.
Thank you.

**Comment by iamsergio** [comment]
Do you mean like in `kddockwidgets_example -w` ?
