### ISSUE TITLE
Documentation table misaligned 

### ISSUE THREAD

**Issue by ruilvo** [KDAB/KDDockWidgets#106]
On the documentation for [`enum KDDockWidgets::Config::Flag`](https://docs.kdab.com/kddockwidgets/latest/classKDDockWidgets_1_1Config.html#af7a2f7973617985365049a4d216bd905), the column on the right is one item down from the corresponding element on the left. In other words, it's missing `Flag_None` at the top of the left. Funnily enough, [it is correct in the source file](https://github.com/KDAB/KDDockWidgets/blob/97d8e4f18b6b0ef7527e100617aac8b77b1ffdd5/src/Config.h#L64). 

The error happens in either 1.0, 1.1 or latest docs.

**Comment by winterz** [comment]
fixed in commit ece7b22bec0b05e6758581a6ee3e010bf052d6a6
the documentation on  the website will be regenerated sometime in the next day.
