### ISSUE TITLE
Undocking a dock widget containing QOpenGLWidget inside causes QOpenGLContext issues

### ISSUE THREAD

**Issue by skarnproject** [KDAB/KDDockWidgets#107]
After undocking a dock widget containing QOpenGLWidget inside causes QOpenGLContext issues. The VAOs are no longer able to bound to that context.

**Comment by dangelog** [comment]
Hi,
are you recreating the VAO after the QOpenGLWidget's context gets re-initialized? Cf. the discussion here https://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup

**Comment by skarnproject** [comment]
> Hi,
> are you recreating the VAO after the QOpenGLWidget's context gets re-initialized? Cf. the discussion here https://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup

Yes, I am. I added this as a first attempt to fix the issue. It worked for dragging docked widgets within one window, but when you undock, the aboutToBeDestroyed signal of a QOpenGLContext is never emitted.

**Comment by iamsergio** [comment]
Can you reproduce with QDockWidget ?

**Comment by iamsergio** [comment]
Reopen when you have a minimal testcase showing the bug is in KDDW and not QDockWidget.
Otherwise this should simply be fixed directly in Qt.
