### ISSUE TITLE
Icons / pixmaps are not at the right size in hidpi screens

### ISSUE THREAD

**Issue by jcelerier** [KDAB/KDDockWidgets#11]
See attached image, with Qt Creator for reference 
- the buttons on docks are too big visually when comparing to lodpi screens
- they are pixelated
- the central icons which appear when moving are also pixelated
- the line under the tab seems to be missing 
- the tab icon is too large and pixelated

![out12](https://user-images.githubusercontent.com/2772730/61551454-81e94000-aa55-11e9-93e6-0255c33a5fe8.png)

**Comment by iamsergio** [comment]
when Qt hdpi env variables are you using ?

**Comment by jcelerier** [comment]
None that I know of, that's stock behaviour
