### ISSUE TITLE
Crash when closing dock widgets

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#110]
Windows 10
KDDW 1.1
Qt 5.15.1

Closing a dock widget can crash sporadically in 

> bool StatePreDrag::handleMouseMove(QPoint globalPos)

:
![image](https://user-images.githubusercontent.com/11087133/101628615-5dae4a80-3a20-11eb-93dc-11802175aaff.png)

To reproduce do the following in the KDDW example:
- Create some dockwidgets
- Close the dockwidgets
- Observe a crash

![crash_closing](https://user-images.githubusercontent.com/11087133/101629238-55a2da80-3a21-11eb-9827-d6790780f4f7.gif)

For dock widget creation I added the following code:
```

  QAction* newAction2 = fileMenu->addAction(QStringLiteral("Many new DockWidgets"));

  connect(newAction2, &QAction::triggered, this, [] {
    for (int i = 0; i < 10; ++i)
    {
      auto w = newMyWidget();
      w->setGeometry(100, 100, 100, 200);
      auto dock = new KDDockWidgets::DockWidget(QStringLiteral("new dock %1").arg(i));
      dock->setWidget(w);
      dock->resize(100, 200);
      dock->show();

      qApp->processEvents();
      dock->window()->move(300 + 10 * i, 300 + 10 * i);
    }
```

**Comment by iamsergio** [comment]
reproduced, will fix today

**Comment by iamsergio** [comment]
I can't reproduce the bug anymore, make very sure you have the latest from 1.1 branch, and not the v1.1 tag.
The sha is fb6e2afd7b974fc75a813fd562c370e66a597fd6
Make sure you don't have stale dll around either
