### ISSUE TITLE
Save and Restore for hidden (auto-hide feature) widgets doesn't work

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#116]
Hi,
Unfortunately, saving and loading does not work for hidden widgets in the auto-hide feature.
Steps to reproduce:

- Enable the auto-hide feature in the example with "-w".
- Enable one the widget the auto-hide and hide the widget.
- Change the layout by closing the "hidden" widget
- Save and restore the layout
- Observe the "hidden" widget is not restored.

See also the animation:
![save_and_restore_auto_hide_bug](https://user-images.githubusercontent.com/3143027/102229820-77520500-3eec-11eb-9f9d-704841f99f5b.gif)

**Comment by iamsergio** [comment]
right, it's not even implemented, but we should

**Comment by iamsergio** [comment]
The SideBars are now saved/restored.

The widget's overlayed state (popup mode) isn't restored though. Should it ?
Popups are kind of perishable, not sure we need to restore, or maybe we should...

**Comment by tlaemmlein** [comment]
No. The popup mode shouldn't be restored. I have already test your changes. Good work. Thanks.
Which branch will you then update: 1.1 or 1.2?
Greetings,
Thomas

**Comment by iamsergio** [comment]
Goes to 1.2, which will be released very soon, maybe today.
1.1.1 will probably get only crash fixes or core functionality fixes.
autohide/sidebar is experimental and might have other bugs still, not many people are using it yet.
