### ISSUE TITLE
Crash: undocking by drag operation

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#120]
Version 1.2 and 1.1 have a bug related to undocking panel by mouse. The bug is difficult to reproduce: undock panel by mouse drag + almost simultaneous double-click (dock-operation).
Environment: 
- Windows 10 (64bit);
- Qt 5.14.2 MSVC 2017 64bit; 
- KDDockWidgets 1.2 (1.1, master branch).

![image](https://user-images.githubusercontent.com/7323010/102692970-945e3f00-4230-11eb-853b-72aed00c2352.png)

**Comment by iamsergio** [comment]
which git sha1 did you test in 1.2 branch ?

**Comment by amuralev** [comment]
Yes, the last crash was reproduced on the latest Release version: 1.2.0
