### ISSUE TITLE
Crash: resize floating window inherited from QWebEngineView

### ISSUE THREAD

**Issue by nifh80s** [KDAB/KDDockWidgets#122]
when using a QWebEngineView with DockWidget, asset fails at qquickwidget.cpp line 996 when dragging to resize this webview if it's floating. The crash reason is that when qtTopLevelForHWND being called, QQuickWindow::winId creates its platformWindow which can not be created for QWebEngineView.
I'm using the master branch. Here's the asset message:
![Uploading Dingtalk_20201221125724.jpg…]()

**Comment by iamsergio** [comment]
any minimal testcase I can try ?
