### ISSUE TITLE
X11: stacking order of float window

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#123]
Under Linux X11 there is a violation of the stacking order of the float windows at undocking by mouse drag:

![bug_z_order_x11](https://user-images.githubusercontent.com/7323010/102742440-55360800-436e-11eb-8fd4-0ab02d56e7c3.gif)

Environment: 
- Ubuntu 18.04.5 LTS;
- X.Org 1.19.6;
- KDDockWidgets 1.2 (1.1);
- Qt 5.15.2 GCC.

**Comment by iamsergio** [comment]
works with X11/KWin, I'll need to install Ubuntu to try it out
