### ISSUE TITLE
Question: behavior of KDDockWidget::setFloating

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#125]
Why after **float** KDDockWidget is **closed** the call KDDockWidget::setFloating(false) causes the panel to **be displayed**? Сall KDDockWidget::setFloating should not affect on visibility of panel!?

![set_float_behavior](https://user-images.githubusercontent.com/7323010/103126282-3e155400-46a7-11eb-8226-a7895b3a663d.gif)

Environment:
- Windows 10 (64bit);
- Qt 5.15.1 MSVC 2019 64bit;
- KDDockWidgets 1.2 (release).

**Comment by iamsergio** [comment]
For our API setFloating(false) means to dock.
It's too late now to change the behaviour. Do you need an option to control this behaviour or can you workaround ?

**Comment by amuralev** [comment]
Yes, we need this option!  Can you add it?
