### ISSUE TITLE
is there a way floating windows become MainWindows

### ISSUE THREAD

**Issue by PerBothner** [KDAB/KDDockWidgets#131]
Is there a way to eliminate the distinction between FloatingWindow and MainWindow?  Ideally, I'd like them to look the same (including optional menubars); don't close application if the initial window is closed and there are existing floating windows; be able to programmatically create new DocksWidgets in a "floating window".

Consider the Chrome browser: You can drag a tab onto the desktop, and it becomes a new window indistinguishable from other Chrome windows.  I think that would be a desirable supported feature.  However, I don't know how difficult it would be.  One idea is that one could register an optional function that the library could call to create a new MainWindow. Figruing the right size might be tricky.

Context: I've been experimenting with KDDockWidgets as an alternative to the [GoldenLayout](https://golden-layout.com/) JavaScript library, for my [DomTerm](https://domterm.org) terminal emulator.  GoldenLayout has a nice UI, but it has some limitations, a major one that you can't drag a widget from one main-window to another.

**Comment by iamsergio** [comment]
It would be rather difficult to do in KDDW, and probably not done.

However maybe it can be worked around in the user app. The widget you pass to DockWidget::setWidget() can detect it's floating, and show the menu bars, it would need to be a MainWindow. And it should disable its inner docking when itself is docked

**Comment by PerBothner** [comment]
Thanks for the reply.  I'm puzzled by your suggested to make the widgets I use MainWindow for my widgets.  It seems awkward. A code example might help. Using nested MainWindows may handle the "look" issue, including adding optional menubar, but that is not my major concern. (I'm thinking [custom window decorations](https://www.qt.io/blog/custom-window-decorations) may be the way to go for MainWindow, too.)

If the suggestion in issue #132 were implemented that would help a lot.  Another high priority would be a way to prevent closing all MainWindows proventing automatically closing any FloatingWindows, but I assume that wouldn't be too difficult.

**Comment by iamsergio** [comment]
Please checkout branch `issue_131` and run kddockwidgets_example, it should do what you want

The commit message explains how to achieve it with master branch

**Comment by PerBothner** [comment]
Thanks. I tried it, but it doesn't help much. The problem is that a FloatingWindow both looks and behaves differently from a MainWindow, and I need them to look and behave the same.  The look is obviously different in terms of titlebar style (including buttons) - maybe relating to missing NativeTitleBar support.  Behaviorally, we still have the problem that closing every MainWindow closes any FloatingWindows as well.

I assume the idea is I could create a FrameworkWidgetFactory that overrides createFloatingWindow to customize the FloatingWindow.  But I think that's the wrong approach.  Better if we could override createFloatingWindow to return a new MainWindow.  Probably can't do that for compatibility reasons, but would it be possible to introduce a new createFloatingOrMainWindow method? It would default to calling creatingFloatingWindow. It might help to define a new class (TopWindow?) that is inherited by both MainWindow and FloatingWindow; that would be the return type of createFloatingOrMainWindow.

**Comment by PerBothner** [comment]
For more background/motivation
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/300#issuecomment-765164804
(I've been experimenting with both KDockWidgets and Qt-Advanced-Docking-System.)

**Comment by iamsergio** [comment]
The look can be changed by using `Flag_NativeTitleBar`, and the behaviour is a separate (and unrelated issue), which can be tackled in another report. Maybe don't even create an instance of MainWindow and just use floating windows already fixes the problem.

The missing behaviour is easier to fix than making floating windows use MainWindow as the top-level class
