### ISSUE TITLE
suggested DockWidget::addSiblingWidget method

### ISSUE THREAD

**Issue by PerBothner** [KDAB/KDDockWidgets#132]
This is related to issue #131 in that it could help hide the differences between DockWidgets in MainWindow and in FloatingWindow.

Would it be difficult to add a new method  to `DockWidget` with the prototype `addDockWidget (DockWidgetBase *dockWidget, Location location)`?  This would split the current DockWindow into two halvess containing the `this` DockWidget and the `dockWidget` argument.  This is similar to `MainWidget::addDockWidget` but it should work regardless of whether `this` is in a MainWindow or a FloatingWindow.

One would also want a similar method (or option) to add a tab (before or after the `this` DockWidget).

Would this be easy and useful?

**Comment by iamsergio** [comment]
See DockWidgetBase::addDockWidgetToContainingWindow(DockWidgetBase *other, KDDockWidgets::Location location,
                                         DockWidgetBase *relativeTo = nullptr)
                                         
                                         
It only works if the dock widget is in a floating window. But could be changed to make it work if it's in a main window too

**Comment by iamsergio** [comment]
See DockWidgetBase::addDockWidgetToContainingWindow(DockWidgetBase *other, KDDockWidgets::Location location,
                                         DockWidgetBase *relativeTo = nullptr)
                                         
                                         
It only works if the dock widget is in a floating window. But could be changed to make it work if it's in a main window too

**Comment by iamsergio** [comment]
DockWidgetBase::addDockWidgetToContainingWindow() can now be used regardless of it being in a main window or floating window.

See also DockWidgetBase::addDockWidgetAsTab() for the other question

**Comment by PerBothner** [comment]
Thanks - it works for me.
