### ISSUE TITLE
Toggle visibility of auto hidden DockWidgets makes them docked

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#139]
Steps:
Start kddw example with -w (auto hide feature)
Close all widgets and reopen two widgets again
Enable the auto hide for one of the widgets
Toggle the visibility of the auto hidden widget
Observe that the widget is dock
Expected: The widgets should be shown as "auto hide" state
The animation explains the steps:
![try_to_toggle_auto_hide_widget](https://user-images.githubusercontent.com/3143027/104610258-32082b00-5684-11eb-9620-03caa2be3def.gif)

In Visual Studio the behaviour meets my expectations:
![try_to_toggle_auto_hide_widget_in_vs](https://user-images.githubusercontent.com/3143027/104610384-595ef800-5684-11eb-8d63-b7b26af2bbcb.gif)

System:
kddw 1.2.1 
Windows 10
Visual Studio 2019

**Comment by tlaemmlein** [comment]
Of course you can say, that the toggle menu do the "toggle" and not the hide/show for the "auto hide" widgets:
![image](https://user-images.githubusercontent.com/3143027/104612280-4f3df900-5686-11eb-92a3-5cb476cf2815.png)
But what I need is the possibility to check the auto hide state. If the auto hide state is entered then show the widget in this manner. Otherwise do the toggle command.

I hope you udnerstand what I would like to have. I need a "auto hide" functionality -> Check the auto hide state and perform the hide and show of that.

Greetings,
Thomas

**Comment by iamsergio** [comment]
You mean that the toggle action shouldn't simply hide/dock, but additionally it should first check if the dock widget is in the sidebar, and if it is toggle its sidebar state ?

If yes that that sounds reasonable

**Comment by tlaemmlein** [comment]
Yes

**Comment by tlaemmlein** [comment]
After a discussion with the Product Owner, it would be nice if this incorrect behavior could be corrected by May 2021.

**Comment by tlaemmlein** [comment]
Thank you for the fast fix. Great work 👍
