### ISSUE TITLE
Header includes are wrong (Again!?)

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#140]
With kddw 1.2 there are some wrong includes:
Examples:
docks_export.h
DockWidgetBase.h
![image](https://user-images.githubusercontent.com/3143027/104915358-cdedab80-5990-11eb-8831-4efe0d838ba8.png)

This problem was already reported:
https://github.com/KDAB/KDDockWidgets/issues/65

The problem is, that in kddw there is a "src\fwd_headers\kddockwidgets" folder which is different to the "cmake install" folder.
To prevent this problem again you can change the include folders for the kddockwidgets_example project!?:
![image](https://user-images.githubusercontent.com/3143027/104915796-73088400-5991-11eb-91e3-9bdc55fdbd8b.png)
At the moment the include folder points directly into the source code of kddw. It would be better to points to the "installed" folder. And of course the lib must be "installed" for every build run. At the moment the build time is short...I don't know.

First of all, the includes must be fixed.

System:
Branch 1.2
All platforms (Windows, Linux, MacOS)
Independent of the compiler

**Comment by iamsergio** [comment]
Yes, they were wrong in TabWidget_p.h.

fwd_headers is only included when building within KDDW. If you build the example only, then only the installed KDDW will be used (example: `-isystem /usr/include/kddockwidgets/include`)
