### ISSUE TITLE
How to set window split ratio?

### ISSUE THREAD

**Issue by downloadproject** [KDAB/KDDockWidgets#143]
eg: Three columns ，15%，70%，15%。OR   left:20pix，right:20pix,The rest belongs to the middle. thank you!

**Comment by iamsergio** [comment]
MainWindow's `addDockWidget()` method can receive a struct of type `InitialOption`, which has a `preferredSize` field.

Add the middle one first, without any sizing option, then for the left and right specify 20px in `preferredSize`

Note that 20px is probably too small, 100px is probably the absolute minimum.

**Comment by downloadproject** [comment]
thank you! How can I set it smaller than 100px？

**Comment by downloadproject** [comment]
Thank you! Can you help me? My layout is as follows.The separator(only splitter1) cannot be dragged.
[widget.txt](https://github.com/KDAB/KDDockWidgets/files/5839789/widget.txt)

**Comment by downloadproject** [comment]
line1(The rest) column1(40px)         line1(500px) column2(The rest)                                  line1(200px)    column3(40px)    
line2(30px)      column1(40px)         line2(The rest) column2(Follow the previous line)      line2(The rest) column3(40px)

**Comment by downloadproject** [comment]
line1(The rest) column1(40px)----------- line1(500px) column2(The rest) -----------------------line1(200px) column3(40px)
line2(30px) column1(40px)--------------- line2(The rest) column2(Follow the previous line)--- line2(The rest) column3(40px)
