### ISSUE TITLE
Question: programmatically resizing and moving of float widgets

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#144]
Is there a way to set programmatically geometry of the **float** KDDockWidget other than from "DockWidget::window()"-interface? There are also difficulties to move/resize **hidden** **float** widgets (with Qt QDockWidget it can be done by "QWidget::setAttribute(Qt::WA_DontShowOnScreen) -> show -> **MOVE/RESIZE** -> hide -> QWidget::setAttribute(Qt::WA_DontShowOnScreen, false)"); are there any plans to "pull out" DockWidgetBase::lastPositions or something else?

**Comment by iamsergio** [comment]
why do you want to resize hidden floating widgets ?

**Comment by amuralev** [comment]
Thanks for the feedback... Our software has a "redock/reset"-function that resets geometry of all float dock widgets (visible and hidden) to default position and size. It is done so that the user can restore "lost" float windows, for example, by changing the configuration of monitors and etc.

**Comment by amuralev** [comment]
Perhaps there are plans to do it through reusing PIMPL of `KDDockWidgetBase`!?
