### ISSUE TITLE
How to set the layout？

### ISSUE THREAD

**Issue by downloadproject** [KDAB/KDDockWidgets#145]
Thank you! Can you help me? My layout is as follows.The separator(only splitter1) cannot be dragged.
How can I set it smaller than 100px？
line1(The rest) column1(40px)----------- line1(500px) column2(The rest) -----------------------line1(200px) column3(40px)
line2(30px) column1(40px)--------------- line2(The rest) column2(Follow the previous line)--- line2(The rest) column3(40px)
![image](https://user-images.githubusercontent.com/12030433/105259558-ff4fbc80-5bc6-11eb-83cd-a52e23674cb4.png)

**Comment by iamsergio** [comment]
See `Config::setAbsoluteWidgetMinSize()` to make it smaller than 100px.

For the layout:

```
mainWindow->addDockWidget(w2, Location_Top);

mainWindow->addDockWidget(w1, Location_Left, w2, QSize(40, 0));
mainWindow->addDockWidget(w3, Location_Right, w2, QSize(40, 0));


mainWindow->addDockWidget(w4, Location_Bottom, w1); // you can specify the height too...
mainWindow->addDockWidget(w5, Location_Bottom, w2);
mainWindow->addDockWidget(w6, Location_Bottom, w3);
```

To make the splitter not draggable try making your widget 1 having a maximum size == minimum size (Via the usual Qt API, not something in the KDDW headers)

**Comment by downloadproject** [comment]
Thank you very much for your reply
