### ISSUE TITLE
Question: native titlebar at OS Windows

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#147]
As you know, very often programs load data in a GUI thread  (problem of "big project"), so GUI "freezing" is exist and titlebar use own painting procedure (if not mistaken it is WM_NCPAINT)!

![native_titlebar_and_gui_freezing](https://user-images.githubusercontent.com/7323010/105698032-c42eef80-5f1e-11eb-9008-4b99125916af.gif)

Is there way/plans (for example by using Qt::FramelessWindowHint or anything from OS (WinAPI)) to remove this behaviour?

P.S.: There is KDDockWidgets::Config::Flag_NativeTitleBar, but would like use non-native titlebar customization...

Environment:
1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDockWidgets: master.

**Comment by iamsergio** [comment]
We don't support or recommend freezing the main thread. It's a big no-no which is frowned upon. 
Heavy "Work" in the main thread should use async API (or even threading).

You can however override FloatingWindowWidget (via the dock widget factory), override `QWidget::nativeEvent()` and catch `WM_NCPAINT` as you suggest. You'll also need `KDDockWidgets::Config::Flag_NativeTitleBar` so you can paint over it I guess. No idea how easy it is though.

**Comment by amuralev** [comment]
Thanks for reply! There is a little question. Is it possible to change type of top-level window at using `KDDockWidgets::Config::Flag_NativeTitleBar` (from `Qt::Window` to `Qt::Tool` at `windowFlagsToUse`) ?

**Comment by iamsergio** [comment]
It's not possible now, maybe an option would make sense ?
Please open a new issue, about making "windowFlagsToUse" more flexible to tune
