### ISSUE TITLE
Enhancement of native titlebar creation

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#149]
From version KDDW 1.1-1.2 float window has only type **Qt::Window** when using `KDDockWidgets::Config::Flag_NativeTitleBar` (function `windowFlagsToUse`). It would be more flexible to have ability to change this type, for example by an option.

**Comment by iamsergio** [comment]
Gave this a bit more thought.

What do you expect Qt::Tool does on Windows ?
Afaik Qt::Tool doesn't do anything on Windows.

**Comment by amuralev** [comment]
![image](https://user-images.githubusercontent.com/7323010/106314457-3129e880-6283-11eb-8fcc-a50267059671.png)

Yes of course, it is possible by overriding `FrameworkWidgetFactory::createFloatingWindow`, but sometimes unnecessary in some cases.
