### ISSUE TITLE
I know it is stupid, but how to run the example

### ISSUE THREAD

**Issue by SamuelyHsu** [KDAB/KDDockWidgets#15]
I know it is stupid, but how to run the example? I need to use it both on Windows and Linux, it would be appreciated if you could list steps.

**Comment by iamsergio** [comment]
try cmake -DCMAKE_INSTALL_PREFIX=/usr/local && make && make install
Then you can build the example with:
cd examples/dockwidgets/
cmake -DCMAKE_PREFIX_PATH=/usr/local && make

**Comment by iamsergio** [comment]
will update the README

**Comment by SamuelyHsu** [comment]
Hi, I tried but still failed, terminal output 
`
CMake Error: Could not find CMake module file: CMakeDetermineDESCRIPTIONCompiler.cmake
CMake Error: Error required internal CMake variable not set, CMake may be not be built correctly.
Missing variable is:
CMAKE_DESCRIPTION_COMPILER_ENV_VAR......
`
Maybe the issue comes from CMake 3.5, according to [this page](https://github.com/FedeDP/libmodule/issues/4), I delete DESCRIPTION and HOMEPAGE_URL in cmakelist, then it worked for me.
however, when I build the example with make, error occurred as follows
`
/usr/local/include/kddockwidgets/QWidgetAdapter.h:36:47: fatal error: widgets/QWidgetAdapter_widgets_p.h: No such file or directory
`
I guess it may be a path problem, will you fix it recently?
Another question, can it used on windows now?
Thanks.
>

**Comment by iamsergio** [comment]
this is fixed now, the header wasn't installed correctly
