### ISSUE TITLE
Crash by using QQuickWidget

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#150]
Bug is reproduced on latest **release** and **master** brahch:

1. Create FLOAT KDDockWidget with QQuickWidget (for example "kddockwidgets_minimal_example");
2. Try dock to MainWindow

![image](https://user-images.githubusercontent.com/7323010/106011997-70660700-60d4-11eb-8344-dc76d1a71bce.png)

![kdw_1_2_quickwidget_bug](https://user-images.githubusercontent.com/7323010/106011539-ffbeea80-60d3-11eb-817c-56f9ee346993.gif)

Environment:
1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDockWidgets: master and 1.2.

**Comment by iamsergio** [comment]
Can't repro on Linux.
Can you find out if it's not a Qt bug ? Assert seems to be in Qt, but can't the whole backtrace

**Comment by amuralev** [comment]
According to our observations, the bug is **NOT** reproduced when using KDDW 1.1.1 (release)
![kdw_1_1_quickwidget](https://user-images.githubusercontent.com/7323010/106087777-20bc2580-613e-11eb-9c13-234f37f42083.gif)

Environment:

Windows 10 (64bit);
Qt 5.15.1 MSVC 2019 64bit;
KDDockWidgets: version 1.1.1.

**Comment by amuralev** [comment]
Unfortunately, the bug is reproduced when using a **KDDW 1.1.1**, but in a different form (can reproduced by using 2 `QQuickWidget` that "starts" as `KDDockWidgets::AddingOption_StartHidden`

When using **one** monitor:
![kdw_1_1_quickwidget_bug](https://user-images.githubusercontent.com/7323010/106299613-cec6ed00-626e-11eb-9f4b-0191a2fea54d.gif)

When **move** mainwindow and docks to **secondary** monitor happens **crash**:

![image](https://user-images.githubusercontent.com/7323010/106299773-09c92080-626f-11eb-8802-a90946d373c0.png)

Also we have **problems** with **OpenGL-context** with KDDW 1.1.1 + `QOpenGLWidget` + OpenSceneGraph.

**Comment by amuralev** [comment]
Path for example:
[patch.txt](https://github.com/KDAB/KDDockWidgets/files/5895490/patch.txt)

**Comment by iamsergio** [comment]
can you do a `git diff > patch.diff`` at the root of the repo and attach here
The first patch seems to be missing changes to CMakeLists.txt

**Comment by iamsergio** [comment]
main.qml is missing ? Might be easier to commit to a fork, then I can check it out.

Trying the QOpenGLWidget but can't repro so far, will try with another GPU

**Comment by amuralev** [comment]
[patch.txt](https://github.com/KDAB/KDDockWidgets/files/5898390/patch.txt)

Steps:

1. Show "DockWidget #1" from menu;
2. Undock "DockWidget #1" by mouse drag;
3. Show "DockWidget #2" from menu;
4. Undock "DockWidget #2" by mouse drag;

See to output and painting "DockWidget #2". 

To reproduced crash:

1. Move MainWindow to secondary screen;
2. Dock "DockWidget #1" and "DockWidget #2" to "DockWidget #0"
3. Try undock "DockWidget #1" or "DockWidget #2"

**Comment by iamsergio** [comment]
Doesn't seem to apply
```
git apply ~/Downloads/patch.txt
C:/Users/serj/Downloads/patch.txt:64: trailing whitespace.
    else
error: examples/dockwidgets/main.qml: No such file or directory
error: patch failed: examples/dockwidgets/resources_example.qrc:6
error: examples/dockwidgets/resources_example.qrc: patch does not apply
```

tried master, 1.2 and 1.1

looks like the contents of the patch is for an older KDDW, can you pull the latest master and get a new diff

thanks

**Comment by amuralev** [comment]
Sorry, can you try again?
[patch.txt](https://github.com/KDAB/KDDockWidgets/files/5898571/patch.txt)

**Comment by amuralev** [comment]
Thanks for the fix!

**Comment by iamsergio** [comment]
Does it fix the QOpenGLWidget case too ?

**Comment by amuralev** [comment]
it seems that fix "cover" QOpenGLWidget-case (at least there is no crash and "bad"-output).
