### ISSUE TITLE
Question about implementation KDDockWidgetBase

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#151]
There is a commit [b93f115](https://github.com/KDAB/KDDockWidgets/commit/b93f115b5311a1737d8ee1cc8f16e6aed5e471c8) that install the filter of all events from application to `DockWidgetBase` (ctor):
 `qApp->installEventFilter(this)`. 
Maybe it's not a good idea... Easy enough to get UB. Here is a hypothetical/naive example:
![image](https://user-images.githubusercontent.com/7323010/106041774-ae275780-60f5-11eb-8cab-f56ebea424b0.png)

**Comment by amuralev** [comment]
Patch to demonstrate:
[patch_UB.txt](https://github.com/KDAB/KDDockWidgets/files/5895567/patch_UB.txt)

**Comment by iamsergio** [comment]
thanks for the patch, helped me understand what this was about

It's fixed now
