### ISSUE TITLE
Includes still not correct

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#152]
Unfortunately, I have to report that the includes are still not correct.
For example, we include 
#include <kddockwidgets/private/DragController_p.h>
And the DragController_p.h includes 
include\kddockwidgets\private\DragController_p.h:
  14  
  15: #include "docks_export.h"
  16  
But docks_export.h is located under include\kddockwidgets.

In the end we use 
lib\cmake\KDDockWidgets\KDDockWidgetsTargets.cmake
to have a working kddock lib (where the lib and include folders should be correct).

I have noticed that the content of lib\cmake\KDDockWidgets\KDDockWidgetsTargets.cmake has changed from 1.1.0 to 1.2.1
1.1.0:
set_target_properties(KDAB::kddockwidgets PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "KDDOCKWIDGETS_STATICLIB"
  INTERFACE_INCLUDE_DIRECTORIES "**${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/kddockwidgets**"
  INTERFACE_LINK_LIBRARIES "Qt5::Widgets;KDAB::kddockwidgets_multisplitter;\$<LINK_ONLY:Qt5::GuiPrivate>;Qt5::X11Extras"
)
1.2.1:
set_target_properties(KDAB::kddockwidgets PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "KDDOCKWIDGETS_STATICLIB"
  INTERFACE_INCLUDE_DIRECTORIES **"${_IMPORT_PREFIX}/include"**
  INTERFACE_LINK_LIBRARIES "Qt5::Widgets;Qt5::X11Extras"
)

So finally it is rather simple:
We need the ${_IMPORT_PREFIX}/include/kddockwidgets folder.

What should we do?
1. You take care that the ${_IMPORT_PREFIX}/include/kddockwidgets folder is in KDDockWidgetsTargets.cmake
2. We will add this addtional include folder
3. Or did we something wrong to build and (cmake) install the lib?

To be honest: I don't know how the KDDockWidgetsTargets.cmake and the similar cmake files are generated.

Greetings,
Thomas

**Comment by iamsergio** [comment]
please pull and check again, no need to debug more

DragController_p.h is simply not tested as an installed include as it's private, but I don't mind exposing it upon request

fixed in master and in 1.2 branch
