### ISSUE TITLE
Restoring TAB-position (index)

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#154]
1. Set up `KDDockWidgets::Config::Flag_AllowReorderTabs`;
2. Tabify two Docks (for example "DockWidget #2", "DockWidget #0"; 
![image](https://user-images.githubusercontent.com/7323010/106230751-a8229b00-6209-11eb-8e8d-ec114cb9bc5a.png)
3. Reorder tabs by "QTabBar-drag" as
![image](https://user-images.githubusercontent.com/7323010/106230920-f6d03500-6209-11eb-9f1d-e491c7e95416.png)
4. Undock "DockWidget #0" by mouse-drag;
5. Dock "DockWidget #0" by double-click or "float"-button;

Dock do **NOT** restore last **TAB**-position:
![image](https://user-images.githubusercontent.com/7323010/106230751-a8229b00-6209-11eb-8e8d-ec114cb9bc5a.png)

It is possible to fix this behavior?

**Comment by iamsergio** [comment]
sure

**Comment by amuralev** [comment]
Thanks for fix!
