### ISSUE TITLE
Visual Studio support

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#156]
Hello! src/CMakeLists.txt uses `CMAKE_BUILD_TYPE`, but this variable is absent when CMake generator is Visual Studio.

**Comment by iamsergio** [comment]
What's the problem, do you get an error ?

**Comment by iamsergio** [comment]
does it work after simply removing that block ?

**Comment by arietto** [comment]
Default error: 

    CMake Error at src/CMakeLists.txt:270 (string):
     string no output variable specified.
If I comment out WIN32 section, then the following error occurs:

    Evaluation file to be written multiple times with different content.  This
     is generally caused by the content evaluating the configuration type,
     language, or location of object files:
     D:/projects/KDDockWidgets-build/qt_KDDockWidgets.pri
