### ISSUE TITLE
Sidebar widget can not be hidden if there is no other docked widget

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#157]
Code basis: 1.2.1 (2021-01-28)
Steps:
* Activate the auto-hide feature
* Close all widgets except one
* Pin the widget to the sidebar
* click on the widget in the sidebar
* Click outside the overlayed sidebar widget into the main window
* Observe the sidebar widget is still visible
* Expectation: The sidebar widget should be hidden
![sidebar_widget_could_not_be_hidden](https://user-images.githubusercontent.com/3143027/106617446-ece26500-656e-11eb-91b1-dd275b5c5b2c.gif)

**Comment by iamsergio** [comment]
commit 7caa83be19db22a59818e671815473eb7aa66eb0 (origin/1.2, 1.2)
Author: Sergio Martins <sergio.martins@kdab.com>
Date:   Thu Feb 4 19:54:11 2021 +0000

    Also hide overlay when clicking on empty space of a main window
