### ISSUE TITLE
More pleasant method names for sidebar widgets checks

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#158]
I would like to have more pleasant method names for sidebar widgets checks.
Currently I have to write:
  if (kddock_wdg->isHidden())
    if (kddock_wdg->sideBarLocation() != KDDockWidgets::SideBarLocation::None)
      kddock_wdg->toggleAction()->toggle();

A better naming could be:
  if (kddock_wdg->isHidden())
    if (kddock_wdg->isInSideBar() )
      kddock_wdg->overlay();

I don't like the toggleAction method because I have to take care that the kddock_wdg must be hidden. Otherwise toggleAction will close my kddock_wdg.

At this point I have to say that I'm not satisfied with the API of kddock widgets. Yes, all things working in the most cases, but I have to search a lot to find my use case (In this case it is the sidebar).

In my eyes the whole docking stuff is more a state machine (sm) and it would be great if there is a documentation about these states. 
And it would be wonderful if there is a real (Qt) state machine behind because then it is possible to check the sm with gammaray.
Here is a sketch of a state machine which comes in my mind:

![image](https://user-images.githubusercontent.com/3143027/106621225-a4c54180-6572-11eb-99be-8face3da6f1e.png)

If there is a state machine chart I can check the names and therefore the wording in a fast time. So I can look into DockWidgetBase header to find the correct method. Furthermore with a state machine diagram it comes more clear that some states don't have a transition. 
Examples: 

- The transition from the sidebar state to floating is possible but NOT vice versa!
- In the docked state it could side-by-side or tabbed

Greetings,
Thomas

**Comment by iamsergio** [comment]
There's now `DockWidget::isInSideBar()`
There's also:
`MainWindow::overlayOnSideBar(dw)` and `MainWindow::toggleOverlayOnSideBar(dw)`

should be enough
