### ISSUE TITLE
nesting KDDockWidgets

### ISSUE THREAD

**Issue by downloadproject** [KDAB/KDDockWidgets#159]
I have a parent KDDockWidgets and a child KDDockWidgets. When the parent KDDockWidgets is designed as follows. Mainwindow runtime (setWindowState(Qt::WindowMaximized)) cannot be maximized.
    eg:
  addDockWidget(m_MainDockWidget.at(0), KDDockWidgets::Location_OnTop);
    addDockWidget(m_MainDockWidget.at(1), KDDockWidgets::Location_OnLeft);
    m_MainDockWidget.at(0)->addDockWidgetAsTab(m_MainDockWidget.at(2));

if delete "m_MainDockWidget.at(0)->addDockWidgetAsTab(m_MainDockWidget.at(2));",The main window returns to normal.

**Comment by iamsergio** [comment]
can you edit `examples/minimal` so I can repro ? Attach the patch here (or in a fork), also see README about bug reporting

thanks

**Comment by iamsergio** [comment]
Can you share something that compiles ? It's missing headers, main.cpp, a build system and requires me to copy paste everything into files.

I receive many bugs per week (on multiple-projects), so I need the bug triaging step to be very smooth. It's frustrating if I spend 10m trying to repro something that wasn't a bug.

I can update the README if it's not clear enough about what a minimal testcase is

thanks!

**Comment by downloadproject** [comment]
Thank you! you e-mail？I can't find the place to upload. I'll send it to you by email

**Comment by downloadproject** [comment]
I have another question.I click the button to create a new class(base KDDockWidgets),new the second,There are the following problems.
void KDDockWidgets::DockRegistry::registerDockWidget(KDDockWidgets::DockWidgetBase*) Another DockWidget KDDockWidgets::DockWidget(0x95f0420) with name "SecTab2"  already exists. KDDockWidgets::DockWidgetBase(0x95f0470)

**Comment by iamsergio** [comment]
sergio (at) kdab.com

**Comment by iamsergio** [comment]
each dockwidget needs to have a unique name

**Comment by iamsergio** [comment]
In the future, please just fork this repo (The fork button in the top-right), modify examples/dockwidgets and commit+push. 
Took me 20 minutes to get your project running, also the build system had hardcoded paths.

Then please give unique names to your dock widgets and main windows. Make sure there's no `Another DockWidget KDDockWidgets::DockWidget(0x95f0420) with name "SecTab2" already exists. ` in the output.

Right now I'm here. This opens full screen:

![Screenshot_20210207_124715](https://user-images.githubusercontent.com/20387/107146923-0571c700-6943-11eb-8eb5-b64767dc2732.png)

I can't see any problem though, the windows are maximizing fine
