### ISSUE TITLE
Cannot move docks within nested main window

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#160]
Hello! I have main_window1. It has tab_widget. Tab_widget contains main_window2 with docks in a tab. Docks are floatable. But I don't see any hints during drag-n-drop procedure. I can't place dock in another place by hand. All options for main window and docks are set by default. When I use non-embedded versio of main_window2 with the same docks, everything is ok.

**Comment by iamsergio** [comment]
Can you modify examples/minimal and attach a patch here ? Then I'll fix it if I can repro.
I'll also need which KDDW branch/sha1 or simply version, and which Operating System you're on
