### ISSUE TITLE
No hide by clicking on titlebar (Sidebar/Auto hide feature)

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#161]
Code Basis: 1.2.1
Steps:
* Activate the auto hide feature
* Open two widgets: One is docked the other is a sidebar widget
* Show the sidebar widget and click on the titlebar of the docked widget
* Observe that the sidebar widget won't be hidden
* Expectation: It should be hidden
Here is an animation of this issue:
![no_hide_by_clicking_on_titlebar](https://user-images.githubusercontent.com/3143027/106863921-7dcd5380-66c9-11eb-9a52-04f429830f3e.gif)

**Comment by iamsergio** [comment]
Fixed with #157
