### ISSUE TITLE
Floating of a sidebar widget remains in the sidebar

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#162]
Code basis: 1.2.1
Steps:
* Float an sidebar widget
* Observe that the sidebar widget remains in the sidebar
* The "state" of the sidebar widget is unclear: Is it a floating or a sidebar widget?
In Visual Studio it is in my eyes more clear: The sidebar widget disapears from the sidebar-
See the animation for more details:
![floated_sidebar_widget_remains_in_sidebar](https://user-images.githubusercontent.com/3143027/106876243-cdb31700-66d7-11eb-977f-96fde17079b8.gif)

**Comment by iamsergio** [comment]
please pull again, I've fixed a crash in latest

master and 1.2 branch have this fixed now
