### ISSUE TITLE
Resource linking in WASM (multisplitter)

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#164]
WASM version has the following error under Windows 10: 

     missing function: _Z42qInitResources_kddockwidgets_multisplitterv
sha1=024d56505a284339492388b94bcfb57efe49e180.

I've added the following snippet before experiments in `main()` according to your documentation:

    #ifdef QT_STATIC
        Q_INIT_RESOURCE(kddockwidgets_resources);
    #endif
Does CMakeLists.txt of the consumer app have to contain some additional stuff?
I use `find_package(KDDockWidgets REQUIRED)` and feed `target_link_libraries()` with `KDAB::kddockwidgets`.

**Comment by iamsergio** [comment]
This is very strange, kddockwidgets_multisplitter has been removed a few weeks ago already.
Make sure you don't have any stray headers or old KDDW builds, and do a clean build of your application.

I don't think the client app needs anything else.

**Comment by arietto** [comment]
Hello! Sorry, I've found additional Q_INIT_RESOURCE with obsolete kddockwidgets_multisplitter in client app. Thank you for assistance.
