### ISSUE TITLE
Qt6 Example - Conan

### ISSUE THREAD

**Issue by mpb27** [KDAB/KDDockWidgets#167]
I'm having an issue with 1.3 where `find_package(KDDockWidgets CONFIG)` is looking for Qt5 instead.

Is there a minimal example for Qt6 that could be followed?

**Comment by iamsergio** [comment]
Did it happen with 1.2 too ? And cna you paste the output

**Comment by winterz** [comment]
since you have "Conan" in the title of this issue can I assume you are asking for a conan recipe that builds a Qt6 version ?

**Comment by mpb27** [comment]
That's right I'm trying to use conan as the package manager for both Qt6 and KDDockWidgets.

I've created a minimal example [conan_qt6_kddw](https://github.com/mpb27/conan_qt6_kddw) which has the following issues.

1.  `QT_WIDGETS_LIB` is not defined, so Widget.h from KDDockWigets tries to load its own definition of QSIzePolicy causing redefinition compile error.
2. If I add `find_package(KDDockWidgets REQUIRED)` to *CMakeLists.txt* then KDDockWidgets tries to find Qt5 which is not present.
3. If I manually define `QT_WIDGETS_LIB`,  and add *kddockwidgets1.lib* using target_link_libraries, then it compiles and works but this can't be the correct way of doing this.

I think the correct way is to use `find_package` similar to how Qt6 imports, but the recipe for KDDockWidgets needs to be changed so that it loads Qt6 ?

Making the minimal example helped narrow down the issue.

**Comment by winterz** [comment]
I added an option to the kddockwidgets/conan/conanfile.py called build_for_qt6
kddockwidgets/conan/README.txt is updated as well to reflect his new option

commit 53d3bc86eac5cd5e44ae431a66226f8f33d4d1f4

**Comment by iamsergio** [comment]
thanks Allen!
