### ISSUE TITLE
What is the minimum required Qt version?

### ISSUE THREAD

**Issue by mrexodia** [KDAB/KDDockWidgets#17]
My project ([x64dbg](https://x64dbg.com)) is using Qt 5.6 and I managed to get it to compile on Qt 5.6 with minimal configuration changes. However I'd like to know what Qt version is officially required as a minimum version, because things do not seem to work very well on this version.

**Comment by iamsergio** [comment]
5.9 is the minimum, I haven't tested with 5.6
