### ISSUE TITLE
Using of RestoreOption_RelativeToMainWindow

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#175]
Steps to reproduce:

1. Run "kddockwidgets_example" with option "s";
2. Make size of MainWindow as "less is better";
3. Make width of float window "the bigger, the better";
4. Save layout;
5. Maximize MainWindow;
6. Restore layout.

The float window is large and located at the invisible part of the screen.

![case_1](https://user-images.githubusercontent.com/7323010/109140473-0fcef600-7776-11eb-8aca-6bdad4fa852e.gif)

Is it possible to add the ability to restore the layout of **FLOAT** (rather docks not being into layout of MainWindow) dock widgets but **NOT** scale it (not position, not size) when using `KDDockWidgets::RestoreOption_RelativeToMainWindow`?

**Comment by iamsergio** [comment]
Let's do this for now:

```
#include <kddockwidgets/private/LayoutSaver_p.h>
LayoutSaver restorer(RestoreOption_RelativeToMainWindow);
restorer()->m_restoreOptions.setFlag(InternalRestoreOption::RelativeFloatingWindowGeometry, false);
```
don't want to commit with public API until I gather more feature requests from other users

**Comment by amuralev** [comment]
Ok, thanks!

**Comment by amuralev** [comment]
Hi,

What about using `InternalRestoreOption::RelativeFloatingWindowGeometry` and **invisible** **floating** windows?

To reproduce:

1. Run "kddockwidgets_example" with option "s" and `InternalRestoreOption::RelativeFloatingWindowGeometry`;
2. Make size of MainWindow as "less is better";
3. Make width of float window "the bigger, the better";
4. **_Close float window_**;
5. Save layout;
6. Maximize MainWindow;
7. Restore layout;
8. **_Show closed window_**.

The float window is large and located at the invisible part of the screen.
