### ISSUE TITLE
Using compiled qt quick implementation in creator

### ISSUE THREAD

**Issue by Moonlight63** [KDAB/KDDockWidgets#177]
Let me start by saying I am very new to Qt and I'm still trying to learn how all this works. I have modified the cmakelist file to add the qt quick source files to the install target. This works perfectly fine and when I cd to one of the qtquick examples I run cmake with -DCMAKE_INSTALL_PREFIX="/path/to/install/lib/cmake" then run build. As far as I can tell, this works perfectly, and I should be able to include the shared library into a new project. While messing around with the example project in qt creator, I tried to open one of the qml files and noticed that it imports com.kdab.kddockwidget which causes the editor to throw an error and asks me to add the library with QML_IMPORT_PATH environment variable. I tried to add this to the cmake config with the path to the libkddockwidget.so file, but it didn't work. I've been trying to research how to import into a qml module from a compiled shared library and can not find a lot of information. ~~Mostly, the info I have found is that the import should match the file path you want to import with the library being the root. (sorry if that didn't make sense) With these examples, I am confused which file the qml is even importing (again, I'm new to Qt).~~ I mostly understand now how to import qml modules, but the same method doesn't work here and my trial and error hasn't worked so I figured I would just ask. To be clear, it's a minor problem since the program compiles with cmake just fine. I'm just curious about being able to use the designer along with this library. I also know that qml support is very new and experimental. I'm just hoping to gather as much info about how to works as I can and learn. Thank you for your time. Ps. If it matters, I am on Linux mint and using the master branch. 

Edit: I just found where in the source the QML types are registered, so now I'm just trying to figure out how to get designer to acknowledge that they have been registered in the library.

**Comment by iamsergio** [comment]
Hi,

KDDockWidgets isn't a "QML Module" (yet), that's probably why QtCreator doesn't recognize the types.
It still runs, as you're linking to the library file.

In the future we'll have the libkddockwidget.so file and a plugin for the QML types, and probably you won't have to link explicitly to the library.
