### ISSUE TITLE
Issue about focus changing

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#180]
Changes to repro: [patch.txt](https://github.com/KDAB/KDDockWidgets/files/6088274/patch.txt)

1. Make, for example, 2 tabs of docks at MainWindow (**without** any docks by "split");
2. Press key "Tab" (or "Shift + Tab");
3. Focus "**moves**" from widget to widget!

![focus_true](https://user-images.githubusercontent.com/7323010/110070674-ea547480-7d93-11eb-9a8f-54693db787f4.gif)

4. **Split** any dock at MainWindow;
5. Press key "Tab".
6. Focus transition only works up to a **certain** point. BUT "reverse TAB" (reverse focus) **works**!

![focus_false](https://user-images.githubusercontent.com/7323010/110070699-f4767300-7d93-11eb-923d-edb15efc3cbe.gif)

Environment:

1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDW master-branch.

**Comment by iamsergio** [comment]
Is this still a problem ?

**Comment by amuralev** [comment]
Hi, the problem still exists on master (62591bc360b5e41bf9a1074cbdc7f8245898ae50).

**Comment by amuralev** [comment]
Ooops..., sorry! The problem is solved on branch 1.3 (74c74593e227610d58e37094697e39adf0d0631c)... but **partially**. Please try to use "Tab" and "Back Tab" for reproduce.

**Comment by iamsergio** [comment]
After a whole day of debugging, turns out this bug is in Qt, but I've added a cheap workaround.

Ideally focus bugs should be reported directly to Qt, as KDDW messes very little with focus.
