### ISSUE TITLE
Using the option Flag_KeepAboveIfNotUtilityWindow does prevent docking

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#181]
Hi,

Qt 5.15.1
KDDW master
Win 10

Using the option Flag_KeepAboveIfNotUtilityWindow does prevent docking. The indicators appear for a short time and flicker but no docking is possible.

To reproduce:
Use the example on master and add the obove option.

Best regards,
Philipp

**Comment by tlaemmlein** [comment]
Hi @iamsergio,
this feature is very important for us for the comming release.  It is good to see that the floating windows stay in front, but the docking must still working.
![keep_in_front_docking_not_working](https://user-images.githubusercontent.com/3143027/111119673-aec36280-856a-11eb-80bc-f02222e6dbec.gif)
Do you have a solution for this issue?
Best regards,
Thomas

**Comment by iamsergio** [comment]
not sure yet, but will check later today
