### ISSUE TITLE
[Question] Drag-and-drop only to certain areas

### ISSUE THREAD

**Issue by ruilvo** [KDAB/KDDockWidgets#182]
Hey!

I have a question about the usage of KDDockWidgets:

Can I make several independent zones that some widgets can only drag and drop to and from the same area, or areas that I allow it to? The idea is that I have a sidebar with vertically stacked widgets and I would like if you could pop them out of the stack, but I want that they could only be rejoined into the same bar. Or one bar in the left and one in the right and allow the user moving widgets between them. I would also have another drag areas for other stuff in the middle.

What I'm trying to achive is something like Qt Designer's widget box:
![qt widget box](https://doc.qt.io/qt-5/images/designer-main-window.png)
But making the panels "detachable".

**Comment by iamsergio** [comment]
Hi, this is not supported

Maybe with FrameworkWidgetFactory::createDropIndicatorOverlay() and create your own drop indicator overlay which can block some areas for docking, but sounds like some work
