### ISSUE TITLE
[QUESTION] Conan package

### ISSUE THREAD

**Issue by sminjard** [KDAB/KDDockWidgets#183]
I haven't been able to find any Conan package available. Do you intend to have one ?
I saw you already have some support for Conan so I was surprised there was none directly serving kddockwidgets.

**Comment by winterz** [comment]
look in the kddockwidgets/conan subdir

**Comment by sminjard** [comment]
I saw it yes but I don't understand why it has not been uploaded to any conan remote repository such as bincrafters.

**Comment by winterz** [comment]
none of our products are on bincrafter yet.
maybe we'll get around to that one day.
