### ISSUE TITLE
[Question] Dock in stack-like fashion

### ISSUE THREAD

**Issue by ruilvo** [KDAB/KDDockWidgets#190]
Olá Sérgio!

So, I was reading the API and I found the affinities feature very interesting. 
I had this idea for an UI that I think would be interesting: I was thinking about a sidebar with widgets that can dock in and out of it, with using affinities. The thing is, it would be ideal if the docking could evenly split the size of the widgets. 
What I mean is, with 1 widget, it would occupy 100% of the height. 2 would each occupy 50% of the height, 3 at 33% each, etc etc. 
The thing is, the way docking usually works, if you start with 2 evenly split widgets, and want to add a third one, you dock it in relation to one of the existing ones, not the whole bar, so you end up with a 50/25/25% split, not an even split.
I was even thinking of having a minimum widget size and that said sidebar could create a scrolling area when there were too many!

For some clarity, allow me to share some screencaps I made of Qt-ADS that more or less illustrate this idea:

Creation is easy (at least with Qt-ADS):

https://user-images.githubusercontent.com/8402646/116216814-efed8b80-a740-11eb-9f47-9f5f1c3a791f.mp4

But it's not possible to get this evenly splitting behaviour with docking:

https://user-images.githubusercontent.com/8402646/116216899-072c7900-a741-11eb-9916-91d86c54e467.mp4

Hoping to hear from you! And thanks!

**Comment by iamsergio** [comment]
Could you call `MainWindowBase::layoutEqually()` after adding the dock widget ? Shouldn't flicker if event loop doesn't run in between

**Comment by ruilvo** [comment]
Seems like an option. I assume docking emits a signal?

**Comment by iamsergio** [comment]
you can do it programmatically right after adding the dock widget

**Comment by ruilvo** [comment]
But that only sets the initial layout. After undocking and redocking that doesn't stick, does it?

**Comment by ruilvo** [comment]
Thanks Sérgio!
