### ISSUE TITLE
Incorrect dock widget size with different screen scaling

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#191]
Hi,
System: KddockWidget Version 1.3.1, Windows 10, VS 2017, Qt 5.15.3.
There is problem with the size of the dock widget if the main window is in a screen with a scaling different to 100%.
To reproduce this issue I have changed the kddockwidgets_example code in MyMainWindow.cpp to:

`    QAction *newAction = fileMenu->addAction(QStringLiteral("New DockWidget"));

    const QSize mySize(200, 200);
    const QPoint myMove(3150,50);
    const QPoint myMove2(3150,400);

    connect(newAction, &QAction::triggered, this, [mySize, myMove] {
        static int count = 0;
        count++;
        auto w = newMyWidget();
        w->setGeometry(100, 100, 400, 400);
        auto dock = new KDDockWidgets::DockWidget(QStringLiteral("new dock %1").arg(count));
        dock->setWidget(w);
        dock->resize(mySize);
        dock->move(myMove);
        dock->show();
    });

    QAction *newWAction1 = fileMenu->addAction(QStringLiteral("New Widget 1"));

    connect(newWAction1, &QAction::triggered, this, [mySize, myMove2] {
        auto w = new QWidget();
        w->resize(mySize);
        w->move(myMove2);
        w->show();
    });
`
The code change is to "move" either the dock widget or QWidget.

Steps:

- Screen A = 100% + Screen B = 150%
- Start the example
- The main window is Screen A
- Open the dock widget and the QWidget
- Move the main window to Screen B
- Open the dock widget and the QWidget
- Observe that the second dock widget has a different size as the first one.

Here is an animation to explain the details:
![DockWidget_Size_incorrect_different_scaling](https://user-images.githubusercontent.com/3143027/116428178-f8c78580-a844-11eb-925c-39579f1f9f32.gif)

Our customer can set the width and height of many floating windows. So they report us this kind of bug.

----
And at this point there is another very important seeting called:
QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
If this is not set, then the QWidgets are opend in Screen B have a different size. 
Code
`    QAction *newWAction2 = fileMenu->addAction(QStringLiteral("New Widget 2"));

    connect(newWAction2, &QAction::triggered, this, [mySize] {
        auto w = new QWidget();
        w->setGeometry(3445, 100, 400, 400);
        w->resize(mySize);
        w->show();
    });`

In the following animation the second QWidget doesn't have the same size (200,200) like the first one. But with the "PassThrough" Setting it is working. 
![DockWidget_Size_incorrect_different_scaling_without_Passthrough](https://user-images.githubusercontent.com/3143027/116430361-10a00900-a847-11eb-9c1f-586a260f67f2.gif)

 

I recommend to add this setting in main.cpp
![image](https://user-images.githubusercontent.com/3143027/116514100-d5dfb480-a8ca-11eb-964d-c76f27270c04.png)

And I would like to say that the "PassThrough" Setting doesn't fix the main KDAB bug above.

**Comment by pklaffert** [comment]
@iamsergio : is there any update on this?

I also could reproduce it. In my case I had the following:
Windows 10
Qt 5.15.2
Latest kddw master

My monitor setup:
![image](https://user-images.githubusercontent.com/11087133/122522406-3ca16480-d016-11eb-94a6-b350cc65acf0.png)

where screen 1 has 100% desktop scaling and screen 2 125%.

Having the main application on screen 1, opening a new Dockwidget on screen 1 leads to the following:

**geometry = QRect(0, 0, 1000, 1000);**
```
auto geometry = QRect(0, 0, 1000, 1000);
dock->setGeometry(geometry);
dock->show();
auto dock_window_geometry = dock->window()->geometry(); // dock_window_geometry == **QRect(0, 0, 1000, 1000)**
```
dock_window_geometry == **QRect(0, 0, 1000, 1000)**


Having the main application on screen 1, opening a new Dockwidget on screen 2 leads to the following:

**auto geometry = QRect(0, -1000, 1000, 1000);**
```
auto geometry = QRect(0, -1000, 1000, 1000);
dock->setGeometry(geometry);
dock->show();
auto dock_window_geometry = dock->window()->geometry(); // dock_window_geometry == **QRect(0, -1000, 1250, 1250)**
```
dock_window_geometry == **QRect(0, -1000, 1250, 1250)**

This seems to be wrong. I would expect that the window on the second screen also would have the set geometry.

**Comment by iamsergio** [comment]
will have a look

**Comment by iamsergio** [comment]
I've reproduced the main issue

**Comment by iamsergio** [comment]
Main issue fixed in master, please add any secondary issues (if any) on a dedicated ticket for each
