### ISSUE TITLE
Dock in a stack-like fashion: followup questions

### ISSUE THREAD

**Issue by ruilvo** [KDAB/KDDockWidgets#194]
Olá Sérgio!

Thanks yet again for the work in #190. 

Now, this gave me an idea and now I have some some followup questions. I hope you don't mind I ask them, if you find them inappropriate, feel free to close the issue. 

So, I had this idea for an UI... It might be too out of mind, but tell me what you think and if it could be achieved. So, I'm imagining a sidebar on an application, where the elements of the sidebar can be undockable. 

I'm making an open source application for SDR and it has a main display and lots of controls for the hardware and the DSP, and I imagined like that would be a cool solution. That would allow users to have a main space uncluttered while being able to dock out important controls and hide away the sidebar... 

That's why I made this first question. But even further, how about something like this (amazing PowerPoint sketch incoming):
![gui_idea](https://user-images.githubusercontent.com/8402646/116605987-00ac2600-a928-11eb-8f84-bedcc5434cfe.png)

The idea is that docked widgets do *not* fill the sidebar, and if there are too many the sidebar could even scroll down...

Ideally they would be resizeable while docked and dock with the height they had before docking (only adjusting horizontally).

What do you think?

I guess this would require some things out of this library that I'm not sure are supported... Is "removing a dock and keeping an empty space" even a thing in KDDockWidgets?

Anyhow, thank you, and hope to hear from you!

**Comment by iamsergio** [comment]
yeah this is not supported, the layout will always resize the dock widgets. 
Something like this would require writing a new layout type
