### ISSUE TITLE
KDDockWidgets::InitialOption struct type not available in python bindings

### ISSUE THREAD

**Issue by JPLaude** [KDAB/KDDockWidgets#198]
Hello,

I'm writing an application with python bindings.
I'd like to provide initialOption struct when calling `addDockWidget (DockWidgetBase *dockWidget, KDDockWidgets::Location location, DockWidgetBase *relativeTo=nullptr, InitialOption initialOption={})`.

Unfortunately, it is not available in KDDockWidgets package, even if I see it declared in python/PyKDDockWidgets/typesystem_kddockwidgets.xml:
`    <namespace-type name="KDDockWidgets" visible="no">`
`...        <primitive-type name="InitialOption"/> `
`    </namespace-type> `

I'm based on tag 1.3.0

Any idea what am I missing ?

thanks !

**Comment by iamsergio** [comment]
@renatofilho Can you see what's going on and add it to the example too (in any addDockWidget) call

**Comment by winterz** [comment]
fixed in ec4a4d1c86af9e0a4c4395471e58ea4ae4f0ca64
