### ISSUE TITLE
How do I build on Windows?

### ISSUE THREAD

**Issue by wzhwzh94** [KDAB/KDDockWidgets#202]
I have been trying to build kdDockWidgets on Windows for several days without success. Can anyone tell me more about the detailed steps?

**Comment by wzhwzh94** [comment]
![1622518357(1)](https://user-images.githubusercontent.com/66460600/120262826-0ef5b500-c2cd-11eb-8c2f-4179a89f8ac4.jpg)

**Comment by iamsergio** [comment]
KDDW doesn't have special instructions on Windows, it works the same way on all platforms.

Judging by your screenshot, you're not linking to kddw library, (See the LIBS qmake variable https://doc.qt.io/qt-5/qmake-variable-reference.html#libs )

Our README has very detailed instructions for building the examples, you can follow that or you can adjust for your favorite IDE/build system.

**Comment by RomanKhv** [comment]
@wzhwzh94 Hi! 
Did you finally come to a working .pro file? 
I would appriciate if you share your version

**Comment by wzhwzh94** [comment]
I used a different code: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
