### ISSUE TITLE
Mixing ordinary widgets and docks

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#205]
Hello! I'd like to put normal widgets in MainWindow and have a possibility to put a single dock within MainWindow.
How can I set vertical layout to MainWindow? `setCentralWidget()` is is hidden, setting vertical layout with the widgets to `centralWidget()` leads to their top-left location instead of expansion.

**Comment by iamsergio** [comment]
For such custom usages, I recommend you inherit from KDDockWidgets::MainWindowBase and do your own layouting.

d->m_layout->addWidget(layoutWidget()) is the important line which adds the docking area.
Also copy MainWindow::resizeEvent(), and that should be enough copying I guess
