### ISSUE TITLE
Moving a widget on a screen with a different scaling leads to unexpected resizes

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#207]
My setup:
Remote connection to Windows Server 2012
Qt 5.15.2
latest kddw master

![image](https://user-images.githubusercontent.com/11087133/122525527-9bb4a880-d019-11eb-8ba7-27850ebe2cc3.png)

Monitor 1 scaling 100%, monitor 2 scaling 125%

Using the kddw example with the following addition:
`QApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);`

When moving a dockwidget from screen 1 to screen 2 it gets huge immediatly.
See the attached .gif:

![kddw-size-issue](https://user-images.githubusercontent.com/11087133/122526393-8724e000-d01a-11eb-85ad-ca11533d68a0.gif)

**Comment by iamsergio** [comment]
Are you saying it shouldn't grow or that it shouldn't grow so much ?

What's the initial and final size ? (in Qt pixels and in Windows physical pixels)

I can't reproduce on my Windows 10. It correctly increases by 1.25x

Can you also try:

1) This same KDDW example but on Windows 10
2) A regular non-kddw Qt example (with pass through) with your current RDP setup

We need to know if it's a OS difference or not

**Comment by pklaffert** [comment]
```
Can you also try:

   1. This same KDDW example but on Windows 10
   2. A regular non-kddw Qt example (with pass through) with your current RDP setup
```

1.) does not seem to happen on Windows 10
2.) does not happen with a non-kddw Qt example

Regarding the resizing issue:
The window gets bigger each time it transitions between the screens as seen in the attached animation:
![kddw-size-issue2](https://user-images.githubusercontent.com/11087133/123062572-f03a9800-d40c-11eb-9d7d-7bb472c1b89f.gif)

**Comment by iamsergio** [comment]
Can you try:
1) Windows Server 2012 with RDP (current setup)
2) Windows Server 2012 without RDP

Just to narrow it down a bit more.

**Comment by pklaffert** [comment]
Unfortunately not. The Windows Server 2012 is only available as a remote machine.

**Comment by iamsergio** [comment]
Windows 10 has seen lots of HDPI improvements and Qt is tested on that setup.
Windows Server 2012 is based on Windows 8.

KDDW is supported on Windows 10, so I suggest something newer is used.

I don't mind however accepting a patch that introduces a workaround for that platform. But I think such patch would be for Qt, as KDDW doesn't do HDPI manipulation, and uses Qt for that.
