### ISSUE TITLE
Close button has wrong color

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#208]
The close button included in the resources has a wrong color:
![image](https://user-images.githubusercontent.com/11087133/122552009-0c69be00-d036-11eb-9e42-9537058f52fc.png)

I would expect it to have the same color as close-1.5.png
![image](https://user-images.githubusercontent.com/11087133/122552082-20adbb00-d036-11eb-9c29-ac12ab490ed9.png)

**Comment by iamsergio** [comment]
@NunoPinheiroKDAB can you comment ?
