### ISSUE TITLE
close-2x.png is off-center

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#209]
The button is drawn off-center:

![image](https://user-images.githubusercontent.com/11087133/122552202-49ce4b80-d036-11eb-9b5d-dd876e107c7a.png)

**Comment by iamsergio** [comment]
@NunoPinheiroKDAB can you comment ?

**Comment by npinheiro** [comment]
need to fix those

**Comment by iamsergio** [comment]
nuno's new icon looks centered
