### ISSUE TITLE
Add lazy resized separator

### ISSUE THREAD

**Issue by farmovit** [KDAB/KDDockWidgets#21]
In many cases resizing via separator on the fly causes flicking and glaring of rendered content inside a widget. It would be nice to have an option of lazy resizing separator to get a more pleasant user's perception.
![lazy_sep](https://user-images.githubusercontent.com/22404014/70847006-6c473d80-1e70-11ea-8666-3d9da9bcda62.gif)

**Comment by iamsergio** [comment]
makes sense!
