### ISSUE TITLE
InitialOption can not be used in QML

### ISSUE THREAD

**Issue by scuhappy** [KDAB/KDDockWidgets#212]
Hi guys,

   I find that ,it is impossible to use InitialOption with function "addDockWidget" in QML.  If you just want to use the single param version of "InitialOption" , it is OK. But if you want to both set visible and size, it is impossible, because InitialOption does not have properties and is not registered in QML...

**Comment by iamsergio** [comment]
Any suggestion on how the API should look like ?

**Comment by scuhappy** [comment]
How about put the preferredSize into each DockWidget ? Just like the implicitWidth.

**Comment by iamsergio** [comment]
What do you mean by implicitWidth ? Do you mean as a Q_PROPERTY instead of a parameter in the invokable ?

**Comment by scuhappy** [comment]
Yes, set Q_PROPERTY of implicitWidth in each dockwidget

**Comment by iamsergio** [comment]
MainWindowInstantiator has the API already

**Comment by scuhappy** [comment]
Oh, yes, I found that. I used to look for API in MainWindowBase. So this issue could be closed. Thank you!
