### ISSUE TITLE
Create/destroy items when docking will cause app crash

### ISSUE THREAD

**Issue by scuhappy** [KDAB/KDDockWidgets#213]
Hi guys,
   Please see the demo, the app will crash when create /destroy items and docking the window at same time. If you remove the ColorOverlay, this problem will disappear. 
  To reproduce this issue, please make the black dockwidget floating and then dock it. 

[test_KDDockWidgets.zip](https://github.com/KDAB/KDDockWidgets/files/6730372/test_KDDockWidgets.zip)

**Comment by iamsergio** [comment]
Maybe "QQuickItem: Cannot use same item on different windows at the same time" needs to be fixed first

**Comment by iamsergio** [comment]
Reproduced without KDDW: See QTBUG-94943

There's also other bugs and crashes regarding moving QtGraphicalEffects between windows in the Qt bug tracker.

**Comment by abbaslele** [comment]
I Have Same Problem
I need Dark and Light Theme for this function I used Color Overlay for my Images , but when I want to undock the window , Application crashes.
What is the solution?

**Comment by iamsergio** [comment]
> I Have Same Problem I need Dark and Light Theme for this function I used Color Overlay for my Images , but when I want to undock the window , Application crashes. What is the solution?

It's a Qt bug, you can vote for https://bugreports.qt.io/browse/QTBUG-94943
Try to repro with Qt 6. Qt company will probably ignore this one as it was reported against Qt 5.
