### ISSUE TITLE
The hover event at the top of the window is unavailable in QML

### ISSUE THREAD

**Issue by luoyayun361** [KDAB/KDDockWidgets#214]
Hi guys,
In QML, the mouse hover event cannot be responded to in the area about 40 pixels high at the top of the window.
example：
![1](https://user-images.githubusercontent.com/23145591/123899710-4a51d500-d99a-11eb-811e-22901c6ed4e3.png)

 I wrote a simple window with a button in the upper right corner. The normal color is green, the hover color is cyan, and the press color is red. When the mouse moves to the 40-pixel height area at the top of the window, the button cannot respond to the hover event, but it does. Responding to click events, why is this ?

**Comment by luoyayun361** [comment]
I found the reason. The TabBar occupies the position in Frame.qml. When the TabBar is hidden, its height should be set to 0.

**Comment by iamsergio** [comment]
fixing
