### ISSUE TITLE
Content error after tab drag and drop in QML

### ISSUE THREAD

**Issue by luoyayun361** [KDAB/KDDockWidgets#215]
Hi guys,

In QML, when two or more windows are combined into a tab, drag the non-current tab, and its content will be confused
example：
![4](https://user-images.githubusercontent.com/23145591/123904855-c1d83200-d9a3-11eb-9f20-6d1ce351626e.png)

dock1 background color cyan
dock3 background color red
dock5 background color blue

step1：the current tab is dock5
step2：Drag dock1 out of the tab

![5](https://user-images.githubusercontent.com/23145591/123905042-2a271380-d9a4-11eb-9322-cff5f1855194.png)

bug：
1.Tab title bar name is wrong；
2.The current index of the tab is not selected (the part of the green box)

step3：Click the floting button of dock1 to restore it to the tab

![企业微信截图_16250302045408](https://user-images.githubusercontent.com/23145591/123909189-3e224380-d9ab-11eb-947a-2073d7d2805e.png)

bug:  The background color of dock1 becomes red, the background color of dock3 becomes blue, and the background color of dock3 becomes cyan. Wrong order.
I guess when dock1 is restored to tab, the order on the tab title bar is normal, from left to right are dock1, dock3, dock5, but the order of its contents in the tabwidget becomes dock3, dock5, dock1

Hope to get your reply！
thanks.

**Comment by iamsergio** [comment]
reproduced
