### ISSUE TITLE
In QML，Whether the dock window can set the minimum or maximum width and height？

### ISSUE THREAD

**Issue by luoyayun361** [KDAB/KDDockWidgets#216]
HI~
Is it possible to set the minimum or maximum width and height of the window in QML? I tried to add an interface to the DockWidgetInstantiator and then call it in qml, but it cannot be achieved.

Hope to get your reply, thank you~

**Comment by iamsergio** [comment]
max isn't supported yet for QtQuick
min is supported

do you still need help ?
