### ISSUE TITLE
Question: When will 1.4 be released?

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#219]
Hi,
we are very interested in the fix for  #191. 
Do you have a plan already when the 1.4 version will be released?

**Comment by iamsergio** [comment]
Maybe this week if our CI agrees with it

**Comment by iamsergio** [comment]
branch 1.4 has been created, you can start using it, meanwhile we'll tag

**Comment by iamsergio** [comment]
probably today or monday, @winterz will take care of it

**Comment by iamsergio** [comment]
done
