### ISSUE TITLE
Resetting the dock widget size will cause the app title box to disappear

### ISSUE THREAD

**Issue by xiaonuo911teamo** [KDAB/KDDockWidgets#22]
Environment:
Windows 10;
Qt 5.9.3;
MSVC 2017 community;
Cmake 3.15.2.

Steps to reproduce:

    Open example application.
    Resize some dock widget.  -> fisrt, the style of title bar changed; second, title bar to disappear.

![123](https://user-images.githubusercontent.com/34291867/71650293-e2dcaa00-2d4f-11ea-8633-bed5b9170d85.gif)

**Comment by iamsergio** [comment]
Very strange, never seen it.
Can you repro with a more recent Qt ?

**Comment by xiaonuo911teamo** [comment]
Thank you! I will try.
