### ISSUE TITLE
How to make dockwidget, that can only be docked in the central area?

### ISSUE THREAD

**Issue by jade74-work** [KDAB/KDDockWidgets#222]
I want the editor dockwidget to dock only to the cnetral area.
How to do? It is possible?

same issue : #36 

Best Regards.

**Comment by iamsergio** [comment]
It's not supported currently
You can however inherit from DefaultWidgetFactory, and override this method
 DropIndicatorOverlayInterface *createDropIndicatorOverlay(DropArea *) const override;
 
 Returning your own DropIndicatorOverlayInterface subclass where you can implement the docking rules you like most.
 
 Call KDDockWidgets::Config::self()->setFrameworkWidgetFactory(yourFactoryFunc);
