### ISSUE TITLE
Possible to dock a QWidget to QtQuick-based build

### ISSUE THREAD

**Issue by gnuherdnix** [KDAB/KDDockWidgets#223]
It seems when building with QtQuick support that this prevents from adding a QWidget as a dock using the C++ api. Is this the case, or am I missing something in the build settings?

**Comment by iamsergio** [comment]
KDDW is built either for QtWidgets or for QtQuick, not both.

However, if QtQuick supports embedding QWidgets, then KDDW won't care and it will work. Just make sure to wrap it with a QQuickItem, as that's what KDDW expects.

KDDW won't care about your impl, you can have QtWidgets inside, if QtQuick supports it.
