### ISSUE TITLE
Incorrect positioning of docks due to toolbars

### ISSUE THREAD

**Issue by Dr64h** [KDAB/KDDockWidgets#227]
https://user-images.githubusercontent.com/75995487/130141956-5211f985-7a5c-461b-b786-b5a3a1d85a8c.mov

Environment:
    Linux X11
    Qt6.1.2
    KDDockWidgets-1.4.0

**Comment by iamsergio** [comment]
If you provide a test-case I can quickly compile and run then I can fix it quickly too

**Comment by Dr64h** [comment]
[example.tar.gz](https://github.com/KDAB/KDDockWidgets/files/7027762/example.tar.gz)
