### ISSUE TITLE
use 'restoreLayout' to restore layout from file, resize again, error occurred! 

### ISSUE THREAD

**Issue by xiaonuo911teamo** [KDAB/KDDockWidgets#23]
Environment:
Windows 10;
Qt 5.12.6;
MSVC 2017 community;
Cmake 3.15.2.

here is my code:
@code1

        KDDockWidgets::LayoutSaver saver;
	if (true == saver.saveToDisk())
	{
		auto arr = saver.serializeLayout();
		std::string s = saver.serializeLayout().toStdString();
		std::ofstream ofile(".\\layout.config", ios::out);
		if (ofile.is_open())
		{
			ofile << s;
			ofile.close();
		}
		saver.restoreLayout(arr);
	}

// @code1
@code2

        std::ifstream ifile("layout.config", ios::in);
	if (ifile.is_open())
	{
		std::string temp, s;
		while (std::getline(ifile, temp))
		{
			s += temp;
			s += "\n";
		}
			
		QByteArray arr = QByteArray::fromStdString(s);
		KDDockWidgets::LayoutSaver saver;
		saver.restoreLayout(arr);
	}

// @code2

I hope to use the last layout, when opening the app again.
but, the following error occurred!
![1234](https://user-images.githubusercontent.com/34291867/71810212-d092a100-30ac-11ea-9feb-357e75a021bc.gif)

I tried to solve the error, but I failed. Is it possible that the information ‘saver.serializeLayout()’ keeps is not comprehensive?

**Comment by iamsergio** [comment]
Could you do a test-case ? Maybe change examples/dockwidgets/

If I can reproduce it I'll fix it.

**Comment by xiaonuo911teamo** [comment]
Oh! It's my fault. I didn't use 'std::ios::binary' and 'QTimer::singleShot'. I submitted the modification,  maybe you can refer to it.

**Comment by iamsergio** [comment]
ok, then this can be closed, right ?

**Comment by xiaonuo911teamo** [comment]
sure!
