### ISSUE TITLE
Unable to build project with KDDW-1.4.95, "Could NOT find KDDockWidgets"

### ISSUE THREAD

**Issue by Dr64h** [KDAB/KDDockWidgets#230]
![1](https://user-images.githubusercontent.com/75995487/130481457-5d6b31af-8a06-4c48-9556-1a766e580d95.png)

When i use KDDW-1.4.0 all works fine

**Comment by iamsergio** [comment]
Can you checkout 35de0a2fef16931fbd0711e0ea093bf96a383d0b and see if it works,
then checkout 6a7230e5464ffd633032604b100518ee1d34dac6 and see if that works, report what you get for both commits

**Comment by Dr64h** [comment]
So, after I made checkout 35de0a2, the errors disappeared.
And after 6a7230e, I got the same error as at the beginning.

**Comment by winterz** [comment]
is this with Qt6?

**Comment by Dr64h** [comment]
Yes with Qt6

**Comment by winterz** [comment]
we made the Qt5 and Qt6 versions fully co-installable now.
That means if using Qt6 you'll need to find_package(KDDockWidgets-qt6)

**Comment by Dr64h** [comment]
Ok
