### ISSUE TITLE
Add support for pinned tabs

### ISSUE THREAD

**Issue by Dr64h** [KDAB/KDDockWidgets#231]
Can you add pinned tabs like in VS IDE/VS Code?

![1](https://user-images.githubusercontent.com/75995487/130970579-2c32fa86-9fae-4c92-9a80-f0d393006040.png)

**Comment by iamsergio** [comment]
what does it do ?

**Comment by Dr64h** [comment]
The tabs are divided into two groups, the fixed tabs go to the group on the left, the usual ones go to the right, you can not move the tabs between different groups until the pin is removed.
And you cannot detach tabbed dock fixed with a pin.

**Comment by iamsergio** [comment]
the number of feature requests for tabbing are open ended, it's better that each app overrides TabWidgetWidget and TabBarWidget in their FrameworkFactory and implement specific behaviour
