### ISSUE TITLE
Drop down menu for selecting tabs

### ISSUE THREAD

**Issue by delins** [KDAB/KDDockWidgets#232]
I've been playing around with KDDockWidgets and must say I'm really impressed with how nice and painless everything works! 

Are there plans to add a drop down menu for selecting tabs? For instance, see this screenshot taken from Sublime:

![image](https://user-images.githubusercontent.com/4976257/132264631-6f98fbc9-f600-423c-a905-c18eb5273ffb.png)

The current controls in KDDockWidgets do allow you to go to the one you need, but if there are many tabs it's not the most effective solution. Having many tabs open makes sense on a main window, such as ones found in text/code editors, browsers, etc.

**Comment by iamsergio** [comment]
would this only appear if there were many tabs ?

**Comment by delins** [comment]
I think it would be nicest to have to option to either:

1. Not have it (default)
2. Have it only when needed, similar to the current arrow buttons (1)
3. Always have it

And be able to set this flag per dock.
(1):
![image](https://user-images.githubusercontent.com/4976257/132422955-4719a0ef-ac62-49dc-81ea-bd7415bf7035.png)


That's because I think I'd prefer to always have it on a window where I expect to need it, such as on a main window. Stuff only appearing under certain conditions makes the interface harder to understand.

On small dock widgets, however, I think it's more reasonable not to show them unless you need them, as the dock widget area is probably small and the drop down menu icon will take up a more significant amount of space.

It would also make sense to add the possibility _not_ to show the current left and right buttons (1) at all, since the two systems side by side would compete for the user's attention, and take up more space than needed.

Btw I think that the qt advanced docking system does it more cleanly than Sublime does (taken from the CentralWidgetExample):
![image](https://user-images.githubusercontent.com/4976257/132422790-c7d4233d-288b-4b3d-8b38-5586ed6f90ba.png)


Just some thoughts, I'm interested to hear what you think.

**Comment by iamsergio** [comment]
Now it's possible to have a context-menu, where you can select which tab you want.
This fixes the problem of it being hard to find the tab when there are many.
More advanced solutions can be implemented by deriving from TabWidgetWidget in your widget factory

**Comment by delins** [comment]
Thanks for the quick work! It works nicely (for the unaware, provide `kddockwidgets_example` with the `--allow-switch-tabs-via-menu` flag and right-click on any tabbar with more than one tab). I'd need an actual button, but I'll probably be able to manage that by looking at the code of the existing buttons.
