### ISSUE TITLE
private/multisplitter/Widget_qwidget.h: No such file or directory

### ISSUE THREAD

**Issue by hussainkadori** [KDAB/KDDockWidgets#235]
Hi,
I have an error when using KDDockWidgets for QtQuick , this file is missing:

 private/multisplitter/Widget_qwidget.h

I am using Qt6.1.2

**Comment by iamsergio** [comment]
Which version or sha1 ?

**Comment by hussainkadori** [comment]
> Which version or sha1 ?

v1.4.0

**Comment by iamsergio** [comment]
Is this file inside the installation directory ?

**Comment by hussainkadori** [comment]
> Is this file inside the installation directory ?

Problem Solved with Qt5.15.2 , Thanks.
