### ISSUE TITLE
Incorrectly redocking dock when `KDDockWidgets::MainWindowOption_HasCentralFrame` is used

### ISSUE THREAD

**Issue by delins** [KDAB/KDDockWidgets#245]
I supply `KDDockWidgets::MainWindowOption_HasCentralFrame` to `KDDockWidgets::MainWindow` so that I can use `addDockWidgetAsTab`. This works, I can add docks as tabs. It has a weird side effect, however: if you programmatically add a dock using `addDockWidgetAsTab` and then drag-undock that tab to make it float, and then drag-redock it into the mainwindow, the end result is that the mainwindow's viewport is split between the dock that I created and some white canvas, which I assume is the `CentralFrame`. 

I can imagine why this default frame exists, but it should be ignored/hidden when an actual dock is redocked again.

**Comment by iamsergio** [comment]
I can't reproduce this, with master

See the test I committed, it has instructions for running it, if you could change the code to make it repro it would be great, or tell me what I did wrong

**Comment by delins** [comment]
Thanks for looking into this. I'll investigate this and my other issues further later this week

**Comment by delins** [comment]
Is this something that can be fixed? I'm not trying to push people to fix this, but it would be helpful for me to know the status.

**Comment by iamsergio** [comment]
Better late than never, this is fixed now

**Comment by delins** [comment]
Cool, thanks!
