### ISSUE TITLE
Add option to not resize sibling widgets when docking

### ISSUE THREAD

**Issue by rolivav** [KDAB/KDDockWidgets#25]
When docking widgets, KDDockWidgets resizes the entire container where the widget is going to go, resizing every widget in that container, seen here:
![kddockwidgets_behavior](https://user-images.githubusercontent.com/1664301/72999699-0602f280-3e00-11ea-92fc-54188b2137d1.gif)

It would be nice to have an option to have dragged widgets split the area of the widget where it is being dragged on, without modifying any other widgets. The AdvancedDockingSystem repo does this:
![ads_behavior](https://user-images.githubusercontent.com/1664301/72999704-07ccb600-3e00-11ea-9b5d-524e15de2a2d.gif)

**Comment by iamsergio** [comment]
unless it would violate Label1's min-size, I guess ?

**Comment by rolivav** [comment]
Right, I didn't think about it. In ADS they add a scrollbar by default so this is not really a problem there.
For me here it could try to use as much space as allowed from the left widget, reducing it to its minimum size and then pushing the splitter to the right to accommodate for the dropped widget, since my intention as a user is to drop it in the left area.

**Comment by iamsergio** [comment]
this is now done when docking in the opposite orientation
i.e. if some widgets are laid out horizontally and you dock to bottom/top of one, then it won't affect siblings vertically and the parent horizontal container won't change size

for the case in the screenshot it's not done yet, but almost

**Comment by iamsergio** [comment]
Are you still using KDDW and is this something you still need ?

**Comment by rolivav** [comment]
I went with AdvancedDockingSystem in the end for my application, it is no longer needed from me.
