### ISSUE TITLE
How to remove outer border and spacing when using `setPersistentCentralWidget`?

### ISSUE THREAD

**Issue by delins** [KDAB/KDDockWidgets#250]
I'm using `setPersistentCentralWidget` on a `MainWindow` to host another `MainWindow`, so that I have more control over which docks can be dropped onto the central area (using affinities). In the screenshot below the persistent central widget is on the right. For some reason there's an additional border + spacing around that tab widget:

![image](https://user-images.githubusercontent.com/4976257/137648132-74f49061-0c52-40aa-8bfc-bad920d0f5d4.png)

There used to be even more spacing, but some of it can be removed with `persistentChildMain->centralWidget()->layout()->setContentsMargins(0, 0, 0, 0)`. You can get rid of the rest of the spacing as well using a stylesheet: `setStyleSheet("QTabWidget { border: 0; padding: 0px; margin: 0px }")` but that creates some artifacts of its own, and since that's not required for the dock widget on the left, there must be a better solution. I haven't found it though.

You probably know what creates the border, but if not: if I comment out the draw calls in this paint event, the borders disappear: https://github.com/KDAB/KDDockWidgets/blob/56bec0db045fc5efcc1432ed3d26ac343c37e7f0/src/private/widgets/FrameWidget.cpp#L74

The screenshot is created using the code below, which can be added to the test suite
```c++
auto m = createMainWindow(QSize(500, 500), MainWindowOption_HasCentralWidget, "a");

auto persistentChildMain = new MainWindow("a perschild", MainWindowOption_HasCentralFrame);
persistentChildMain->centralWidget()->layout()->setContentsMargins(0, 0, 0, 0);
m->setPersistentCentralWidget(persistentChildMain);

auto dock1 = createDockWidget("1", new QPushButton("1"));
m->addDockWidget(dock1, Location::Location_OnLeft);

auto dock2 = createDockWidget("2", new QTextEdit);
persistentChildMain->addDockWidgetAsTab(dock2);
```

**Comment by iamsergio** [comment]
Is this something you still need ?

**Comment by delins** [comment]
Probably not, I also don't have time to make use of a fix anyway. So you can close this if you'd like.
