### ISSUE TITLE
Crash on Drag operation

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#253]
Hi,
There are no exact steps to reproduce, but once a crash occurs with call stack:
![image](https://user-images.githubusercontent.com/7323010/139813548-d1a7db00-5788-4e49-92bd-6000842e6127.png)

Is it related to https://github.com/KDAB/KDDockWidgets/commit/232e96ee0e387461c54a5485c5b671aec9dbb017#diff-0e74fc1a2871439061cc00ff1c978172c29e3eeea94ec7f5ef6cd2d8ab9ebbb3?

Environment:
1. Windows 10 (64bit);
2. KDDW master-branch (1.4)

**Comment by iamsergio** [comment]
Can't say it's related to that commit, never seen this crash
Please try to get me exact steps to repro, then I'll fix it, otherwise it's very difficult

**Comment by iamsergio** [comment]
Is it repro with kddockwidgets_example.exe ?

**Comment by iamsergio** [comment]
feel free to reopen when you can repro, then I'll gladly fix it
