### ISSUE TITLE
The drop indicators appear from floating windows that are behind the MainWindow

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#256]
System: Ubuntu 20.04.3 LTS, Kddock version 1.5 (2021-11-17), gcc compiler

The drop indicators appear from floating windows that are behind the MainWindow.

Steps:
Build and run kddockwidgets_example -k
Take care to have two floating and the main window
Move the main window in front of one floating window
Move the other floating window in front of the main window
Observe that the drop indicators of the floating window appears even though it's in the background

![drop_indicators_from_background](https://user-images.githubusercontent.com/3143027/142172149-eaa433be-e9e4-4e6d-acbf-193fb84cd8b2.gif)

The expectation is that the drop indicators should not appear of floating windows which are in the background.

Hint: Under windows it works as expected.

Thanks,

Thomas

**Comment by tlaemmlein** [comment]
@iamsergio Can you check this issue please?

**Comment by iamsergio** [comment]
Is that really stock Ubuntu ? 
I don't have ubuntu, but I'm installing it. However I'm not too confident, as Qt's window flags are known to not be portable across window managers.

**Comment by iamsergio** [comment]
The problem is that there's no way for KDDW to know the z-order of the windows. It doesn't know that the floating widget is under it.

It might mean we can't support -k on Linux/macOS, or it might mean someone contributes it to Qt for each platform plugin.
If the latter then it won't be available for Qt 5.

I'll investigate a bit more.

**Comment by iamsergio** [comment]
I'm trying with X11/XCB API directly , it will be too experimental to put into 1.5

**Comment by iamsergio** [comment]
Please build with -DKDDockWidgets_XLib=ON , it uses XLib api now.
We can't enable it by default, as KDDW is built on many Linux platforms without XLib

**Comment by tlaemmlein** [comment]
Great work!
Is it possible to integrate this fix into the 1.5 branch?
Greetings,
Thomas

**Comment by iamsergio** [comment]
I think so, since it's disabled by default it's safe

**Comment by tlaemmlein** [comment]
What are your plans to integrate the fix in 1.5?
At the moment I'm going to build kddockwigets for our application and it would be nice this fix is also integrated.
