### ISSUE TITLE
Floating windows can hardly dock back into windows or tabs on "Windows Server 2022"

### ISSUE THREAD

**Issue by zengdaiwei** [KDAB/KDDockWidgets#261]
Thanks for the wonderful docking systems. It helps me a lot.
But today I got into trouble with it on "Windows Server 2022".
With the example programs "kddockwidgets_example.exe", once a dock-widget is pull out of window/tab into a floating window, I can hardly drag it back into any window/tab.
The problem is obvious. Please take a little time to look into it, and make the wonderful docking systems better.
Thanks again!

**Comment by iamsergio** [comment]
Hmm, which Qt version ? And is "Windows Server 2022" supported by that Qt version ?

"Windows Server 2022" seems rather new , I wouldn't be surprised it's not supported yet. And once Qt fixes any incompatibilities, they'll probably go to Qt 6 and not backported to 5.15.

**Comment by zengdaiwei** [comment]
I tried Qt6.2.2 with Windows Server 2022，but the floating-Windows-can-not-dock-back still exists。 After struggling， I restore my system to Server 2109.



---- 回复的原邮件 ----
| 发件人 | Sergio ***@***.***> |
| 日期 | 2021年12月16日 18:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [KDAB/KDDockWidgets] Floating windows can hardly dock back into windows or tabs on "Windows Server 2022" (Issue #261) |

Hmm, which Qt version ? And is "Windows Server 2022" supported by that Qt version ?

"Windows Server 2022" seems rather new , I wouldn't be surprised it's not supported yet. And once Qt fixes any incompatibilities, they'll probably go to Qt 6 and not backported to 5.15.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
