### ISSUE TITLE
Minimizable dock window ignores the window icon

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#264]
with `KDDockWidgets::Config::Flag_TitleBarHasMinimizeButton` setting `QApplication::windowIcon(icon) ` displays the icon for the main window but not for the floating windows. To have floating window window icons you have to call `setIcon(icon)` on each dock widget but this displays the icon also in the titlebar which is not necessarily desired. Calling `dockwidget->setWindowIcon(icon)` has no effect.

**Comment by iamsergio** [comment]
can you try: dockWidget->windowHandle()->setIcon() ?

**Comment by pklaffert** [comment]
@iamsergio : please open again (sorry, I was not available until now)

setting the icon on the windowHandle does not work, because the windowHandle() is a nullptr

**Comment by iamsergio** [comment]
Sorry, I meant dockWidget->window()->windowHandle()->setIcon()

**Comment by pklaffert** [comment]
That worked, thank you. The issue is solved.
