### ISSUE TITLE
Impossible to build lib on OpenBSD

### ISSUE THREAD

**Issue by Dr64h** [KDAB/KDDockWidgets#265]
Build process fails with linker error. Maybe bug in CMakeLists?
[build.log](https://github.com/KDAB/KDDockWidgets/files/7776082/build.log)

**Comment by iamsergio** [comment]
Does a simple Qt application build for you (With CMake) ?

**Comment by winterz** [comment]
I'm curious what happens with gcc

**Comment by Dr64h** [comment]
@iamsergio Yes, I tried to build regular C++ programs and Qt examples. Everything works fine.
@winterz I tried to build it using gcc and clang, It has the same linker error.
And other programmers from the linux forum advised to check the standard C++ library using the "dump objects" utility, but there were no problems in it. And yes, everything was put on a purely installed system.

**Comment by winterz** [comment]
My guess is to try commenting these lines in the top-level CMakeLists.txt 
```

  if(NOT sanitizers_enabled OR NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    # Do not allow undefined symbols, even in non-symbolic shared libraries
    set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--no-undefined ${CMAKE_SHARED_LINKER_FLAGS}")
    set(CMAKE_MODULE_LINKER_FLAGS "-Wl,--no-undefined ${CMAKE_MODULE_LINKER_FLAGS}")
  endif()

```
or any other lines that are mucking with the CMAKE_SHARED_LINKER_FLAGS or CMAKE_MODULE_LINKER_FLAGS

**Comment by Dr64h** [comment]
Yeah, even before that I wanted to try it. It helped.

**Comment by iamsergio** [comment]
Can you wrap it with if(APPLE OR LINUX) , let me know if it works

**Comment by Dr64h** [comment]
@iamsergio Works.
