### ISSUE TITLE
Window-specific layout saver & restorer

### ISSUE THREAD

**Issue by zengdaiwei** [KDAB/KDDockWidgets#276]
Will "Window-specific layout saver & restorer" be supported?  For App with multiple MainWindows, each for different jobs, window-specific layout-saver & restorer will be very useful. As we may want to save/restore one window's docks layout, while leave the others unchanged.
Best Regards!

**Comment by iamsergio** [comment]
Closing and adding "later" tag, so it reflects the chance of being done.
After 2.0 is released I'll search for "later" issues and do the ones that make sense.
