### ISSUE TITLE
Auto - hide improvement

### ISSUE THREAD

**Issue by hannescmarits** [KDAB/KDDockWidgets#278]
Hello, 
i have two (in the end three) suggestion to improve the auto-hide functionality:
1.) If a window on the upper right side is auto hidden, an entry with it's name appears at the top and on the left side. 
    This is var away from it's last position. 
    
    Maybe it would help to restrict the used spaces to the left and right, side but not using spaces on all four sides.
    Maybe it would help to make this configurable. Configure which spaces can be used: Top| Bottom | Left | Right
    
2.) If a widget is auto-hidden, the user has to click twice to see it again at the last place. 
     Maybe a double click could be used to dock it again at it's last position. 
     Normal click just view it. 
     Double click dock it a the last position.

3.) Just a note:
     A bigger problem of the auto hide is, that a docked window may have preferred layout, horizontal or  vertical.
     If a window is than docked to the top it is displayed over the whole screen, if it would benefit from a vertical approach, and vice versa. 
    For cases could be solved, by configuring if a window is docked top/bottom or left/right.
    
 Kind regards
 Hannes

**Comment by iamsergio** [comment]
Closing and adding "later" tag, so it reflects the chance of being done.
After 2.0 is released I'll search for "later" issues and do the ones that make sense.
