### ISSUE TITLE
Tabbed widgets are only docked to main window

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#280]
Hi,
System: Windows 10 / VS 2019
kddockwidgets version: 1.6.0 with bug fix: https://github.com/KDAB/KDDockWidgets/issues/96

Nandish mentions this already in #96 : The tabbed widgets are only docked to main window.

But isn't it more logical if the widget will be docked to the last dock position instead of the main window?

Image you have tabbed some tool widgets and you undock one of these tool to set something and then you want to dock it to the other tools again and not to the main window.

![dock_location_is_only_main_window](https://user-images.githubusercontent.com/3143027/159272500-58edaedb-903e-4a2f-93f5-ce8c3b707983.gif)

Kind Regards,
Thomas

**Comment by iamsergio** [comment]
FloatingWidgets don't keep "previous positions" yet, I agree it would be useful.
Some people however only want them in main windows (but could be configurable).
Hasn't been done since it's a big feature (or rather big change). Probably for 2.0

**Comment by bbc131** [comment]
I just stumpled over this behavior when playing with the example and was going to file a bug issue.
Not a big issue, but clearly a bug, imho.
At least I was very surprised seeing a dockwidget docking in the main-window, after I just played with it in a floating-window.

**Comment by iamsergio** [comment]
This is done (main / 2.2)
