### ISSUE TITLE
Docking or undocking a widget causes graphs to stop working when using QOpenGLWidget

### ISSUE THREAD

**Issue by oleyniko5** [KDAB/KDDockWidgets#283]
Hello,

We have a DockWidgetQuick object that graphs data using a simple ChartView with a LineSeries. The graph in the widget displays data without problem after creating the widget, and moving it around the screen when undocked. However, as soon as the widget is docked or undocked, none of the previous data inside the chart is displayed anymore, and no new data is displayed either. 

All datapoints still exist on both the C++ side and the QML side, and the series is being updated as expected when examining the data there.

The bug happens when using OpenGL to draw the series. Drawing with OpenGL disabled for the series does not cause the bug. The bug happens on both Linux 20.04, and on Windows 10.

**Comment by iamsergio** [comment]
Hi I need a link to the app with repro instructions so we can debug this

**Comment by oleyniko5** [comment]
Hello, please find a repo for minimal example here

https://github.com/oleyniko5/kddockwidgets_example

@iamsergio

**Comment by iamsergio** [comment]
Please report a bug against QtCharts instead. KDDW does not do anything special related QOpenGLWidget.

This problem has been recurring, and it's always a bug in the client code, which doesn't support being moved to another window.

The QtChart devs can try creating two QQuickWindow sharing the same QQmlEngine, and making their chart move to another window (by usage of QQuickItem::setParent), which is all KDDW does.
