### ISSUE TITLE
Python Bindings build fails

### ISSUE THREAD

**Issue by k4sima** [KDAB/KDDockWidgets#284]
Hello,
Builds of kddockwidgets, kddockwidgets_example_mdi_quick, kddockwidgets_example_quick and kddockwidgets_customtitlebar_quick succeed, but fails to build PyKDDockWidgets

[build.log](https://github.com/KDAB/KDDockWidgets/files/8396130/build.log)

Used PySide6, shiboken6 and trying to build using Visual Studio 2019.
replace libclang.dll but I get an error...

**Comment by k4sima** [comment]
What should I do?

**Comment by k4sima** [comment]
This is a screenshot of Cmake gui

![kddw_cmake_screenshot](https://user-images.githubusercontent.com/44926913/161652976-2a58ed77-a6f5-4698-82cc-20a7fdc71671.png)

**Comment by k4sima** [comment]
This was output

-------------------------------------------------------------------------
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
The CXX compiler identification is MSVC 19.29.30141.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
Building KDDockWidgets 1.5.99 in Release mode. Installing to C:/KDDockWidgets
ShibokenGenerator base dir: C:\python\python39\lib\site-packages\shiboken6_generator
Shiboken base dir:          C:\python\python39\lib\site-packages\shiboken6
Shiboken custom path:       
Shiboken include dir:       C:/python/python39/Lib/site-packages/shiboken6_generator/include
Shiboken library:           C:/python/python39/Lib/site-packages/shiboken6/shiboken6.abi3.lib
Shiboken binary:            C:/python/python39/Lib/site-packages/shiboken6_generator/shiboken6.exe
Shiboken version:           6.2.4
PySide6 base dir:           C:\python\python39\lib\site-packages\PySide6
PySide6 suffix:             pyd.6.2
PySide include dir:         C:/python/python39/Lib/site-packages/PySide6/include
PySide library:             C:/python/python39/Lib/site-packages/PySide6/pyside6.abi3.lib
PySide typesystems:         C:/python/python39/Lib/site-packages/PySide6/typesystems
PySide6 version:            6.2.4
PYTHON INSTALL PREFIX C:/KDDockWidgets/lib/python3.9/site-packages/PyKDDockWidgetsQt6
The C compiler identification is MSVC 19.29.30141.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
The following OPTIONAL packages have been found:

 * Qt6WidgetsTools (required version >= 6.2.4)
 * Qt6CoreTools (required version >= 6.2.4)
 * Qt6GuiTools (required version >= 6.2.4)
 * Qt6Widgets (required version >= 6.0.0)
 * Qt6Test (required version >= 6.0.0)
 * Qt6Quick
 * Qt6QmlTools (required version >= 6.2.4)
 * Qt6QuickControls2

-- The following REQUIRED packages have been found:

 * Qt6
 * Python3 (required version >= 3.7)
 * Shiboken6
 * PySide6 (required version == 6.2.4)

-- The following OPTIONAL packages have not been found:

 * Qt6QmlCompilerPlus
 * Vulkan
 * WrapVulkanHeaders
 * Doxygen, API Documentation system, <https://www.doxygen.org>
   Needed to build the API documentation.

Configuring done
Generating done

**Comment by winterz** [comment]
try turning-off the CMAKE_UNITY_BUILD setting

**Comment by k4sima** [comment]
I turned off CMAKE_UNITY_BUILD and rebuilt, but the result was the same.

**Comment by winterz** [comment]
I verify that building the bindings with CMAKE_UNITY_BUILD fails.
suggest cleaning your build directory and trying again without  CMAKE_UNITY_BUILD 

I'll add something to the buildsystem to warn about this combination.

**Comment by ughstudios** [comment]
I am getting identical errors in the post I recently made
