### ISSUE TITLE
Ability to get all open dockwidgets (readonly)

### ISSUE THREAD

**Issue by Murmele** [KDAB/KDDockWidgets#288]
Hello,

I have seen that the dockwidgets are stored in the layoutwidget. Is there a way to access the dockwidgets for readonly purpose?
In MainWindowBase there exists layoutWidget(), but the definition of hte layoutWidget is only available internally, because of which i did not find a way to access all the docks.

I would need it to check if a specific dock is already available or not (the user closed it)

**Comment by iamsergio** [comment]
You can #include <kddockwidgets/private/DockRegistry_p.h>

And call KDDockWidgets::DockRegistry::self()->dockwidgets()

**Comment by Murmele** [comment]
Thank you @iamsergio
