### ISSUE TITLE
Is there a way to use DockWidgetQuick from Python?

### ISSUE THREAD

**Issue by k4sima** [KDAB/KDDockWidgets#290]
Hello, is there a way to use DockWidgetQuick from Python?
I want to use Qml and Python

**Comment by iamsergio** [comment]
There isn't and it's not planed, for this year anyway.

**Comment by JamesWrigley** [comment]
Out of curiosity, what would it take to add bindings for `DockWidgetQuick`?

**Comment by k4sima** [comment]
im also interested in it.
