### ISSUE TITLE
Trying to compile with cmake gui on windows

### ISSUE THREAD

**Issue by ughstudios** [KDAB/KDDockWidgets#296]
It seems to be working, but there are some issues:
```
7>C:\Users\pbssu\Desktop\KDDockWidgets\kddockwidgets-1.5.0\src\MainWindow.h(59): error C3210: 'QMainWindow': a member using-declaration can only be applied to a base class member
7>C:\Users\pbssu\Desktop\KDDockWidgets\kddockwidgets-1.5.0\src\MainWindow.h(54): error C3668: 'KDDockWidgets::MainWindow::resizeEvent': method with override specifier 'override' did not override any base class methods
9>kddockwidgets_example_mdi_quick.vcxproj -> C:\Users\pbssu\Desktop\KDDockWidgets\kddockwidgets-1.5.0\build\bin\Release\kddockwidgets_example_mdi_quick.exe
8>kddockwidgets_customtitlebar_quick.vcxproj -> C:\Users\pbssu\Desktop\KDDockWidgets\kddockwidgets-1.5.0\build\bin\Release\kddockwidgets_customtitlebar_quick.exe
7>C:\Users\```

**Comment by ughstudios** [comment]
Nvm I was able to get it to work, but you should really update your read me to be more clear on ALL the steps that need to be taken to get this to compile. I don't even know everything I did, but it worked 🗡️

**Comment by ughstudios** [comment]
Also, on windows, I had to copy paste python.exe and make a copy that was named "python3.exe" for it to work

**Comment by iamsergio** [comment]
@renatofilho if you want to fix anything regarding the python comment feel free

**Comment by iamsergio** [comment]
@ughstudios Which compiler version were you using when it failed ?

**Comment by ughstudios** [comment]
> @ughstudios Which compiler version were you using when it failed ?

MSBuild.exe (Visual studio 2019)

**Comment by iamsergio** [comment]
@ughstudios Sou you're saying it failed with 2019 but not with 2017 ?

**Comment by iamsergio** [comment]
We have CI builds with 2019 and locally I use 2019 too. 2017 is not a requirement. 
No idea why it didn't work for you

**Comment by ughstudios** [comment]
> @ughstudios Sou you're saying it failed with 2019 but not with 2017 ?

Yes exactly. When I downgraded from 2019 -> 2017 it worked. It would actually be really nice if you guys built a https://pypi.org package for this as well. https://packaging.python.org/en/latest/tutorials/packaging-projects/

Having these bindings on pypi.org would make you guys be the ONLY python binding for docking that's setup in a ready-to-use package.
