### ISSUE TITLE
Error when building with conan.

### ISSUE THREAD

**Issue by nrbnlulu** [KDAB/KDDockWidgets#299]
when i run
 ```shell
conan create -s build_type=Release -o kddockwidgets:build_examples=True -o kddockwidgets:build_tests=True -o kddockwidgets:build_for_qt6=True /home/nir/Desktop/git\ clones/qt/KDDockWidgets/conan
```

ERROR: Version range '>5.12.0' from requirement 'qt/[>5.12.0]@kdab/stable' required by 'kddockwidgets/1.5.0@kdab/stable' could not be resolved in local cache

I have qt6.3.0 installed with connan

**Comment by Be-ing** [comment]
Could you please post what you did to resolve the issue in case someone else runs into this in the future?

**Comment by nrbnlulu** [comment]
@Be-ing I actually didn't. I closed it just because It didn't seemed like anyone is interested...

**Comment by iamsergio** [comment]
I've never used Conan myself. Maybe @bog-dan-ro knows.

**Comment by winterz** [comment]
we will eventually fix this

**Comment by iamsergio** [comment]
Let's reopen when there's someone interested on working on it
