### ISSUE TITLE
Have you ever tested it on windows?

### ISSUE THREAD

**Issue by 007-SamuelHsu** [KDAB/KDDockWidgets#30]
I really tried but still failed. I installed ninga and configured the required environment. It's almost the latest step. But when I try to run cmake step, I encountered the following problems.

> CMake Error at CMakeLists.txt:10 (find_package):
>   Could not find a configuration file for package "KDDockWidgets" that is
>   compatible with requested version "".
>   The following configuration files were considered but not accepted:
>     C:/library/kddockwidgets/src/KDDockWidgetsConfig.cmake, version: 0.1 (64bit)

ps:
when I use command
`cmake -DCMAKE_PREFIX_PATH=C:\library\kddockwidgets,`

> error occured as follows,
> Could not find a package configuration file provided by "KDDockWidgets" with any of the following names:
>     KDDockWidgetsConfig.cmake
>     kddockwidgets-config.cmake

so I use this instead
`cmake -DKDDockWidgets_DIR=C:\library\kddockwidgets\src`

could you please help me,thanks a lot

**Comment by iamsergio** [comment]
Yep, tested on Windows, many people are using it. 

Here's my steps, which I've just tested on a random laptop:

Open a cmd.exe suitable for development (Qt, compiler, cmake, ninja in PATH)

> cd kddockwidgets_sources/
> mkdir build/
> cd build/
> cmake -G Ninja -DCMAKE_INSTALL_PREFIX=c:\kddockwidgets_installed ..
> ninja
> ninja install
> cd ..\examples\dockwidgets
> cmake -DCMAKE_PREFIX_PATH=C:\kddockwidgets_installed .
> ninja
> set PATH=%PATH%;c:\kddockwidgets_installed\bin
> kddockwidgets_example.exe

Let me know if it worked

**Comment by 007-SamuelHsu** [comment]
Thanks for your reply，but same error occurred when I run 
`cmake -DCMAKE_PREFIX_PATH=C:\kddockwidgets_installed .`

> CMake Error at CMakeLists.txt:10 (find_package):
>   Could not find a configuration file for package "KDDockWidgets" that is
>   compatible with requested version "".
>   The following configuration files were considered but not accepted:
>  C:/kddockwidgets_installed/lib/cmake/KDDockWidgets/KDDockWidgetsConfig.cmake, version: 0.1 (64bit)
> -- Configuring incomplete, errors occurred!
> See also "D:/.../KDDockWidgets/examples/dockwidgets/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/KDAB/KDDockWidgets/files/4217569/CMakeOutput.log)

**Comment by iamsergio** [comment]
Looks like you're building an app in 32-bit mode (according to CMakeOutput.log) against a 64-bit KDDW

**Comment by 007-SamuelHsu** [comment]
Hi, I used `vcvarsall.bat x86_amd64` incorrectly to initialize the environment before, but it worked fine after switching to `vcvarsall.bat x86` or `vcvarsall.bat amd64`, thanks for the help.
After that, I want to try the example, run `ninja`(after `cmake -DCMAKE_PREFIX_PATH=C:\kddockwidgets_installed .`), it said 
> ninja: error: loading 'build.ninja': The system cannot find the file specified.
I checked, and actually there is no such file.

**Comment by 007-SamuelHsu** [comment]
And how should I use it in qt creator? I tried to add library like this
![20200218211510](https://user-images.githubusercontent.com/54670020/74739488-e2fb1f80-5293-11ea-806a-35bf953ada78.png)
in qt pro file

> win32: LIBS += -LC:/kddockwidgets_installed/64bit/lib/ -lkddockwidgets
> INCLUDEPATH += C:/kddockwidgets_installed/64bit/include
> DEPENDPATH += C:/kddockwidgets_installed/64bit/include
> win32:!win32-g++: PRE_TARGETDEPS += C:/kddockwidgets_installed/64bit/lib/kddockwidgets.lib
> else:win32-g++: PRE_TARGETDEPS += C:/kddockwidgets_installed/64bit/lib/libkddockwidgets.a

But when I build it, it said 

> C:\kddockwidgets_installed\64bit\include\kddockwidgets\private\Frame_p.h:31: error: C1083: Cannot open include file: 'docks_export.h': No such file or directory

In fact, not only this one but many documents are missing. Please help, thanks.

**Comment by iamsergio** [comment]
first let's get the cmd line build working: also pass -G Ninja to cmake, otherwise it will use whatever is the default generator

Note that ninja isn't a requirement, you can use your usual generator (NMake, etc.)

**Comment by 007-SamuelHsu** [comment]
Thanks a lot, It works really amazing, look forward to the official release.
By the way, can you help with how to use it in qt creator. Pardon my ignorance showing...

**Comment by 007-SamuelHsu** [comment]
Hi, can you help, I tried but still don't know how to use it in qt creator with qmake

**Comment by 007-SamuelHsu** [comment]
I don't know if there is a better way, but my stupid way is to change the include path one by one, now it worked, thanks

**Comment by 007-SamuelHsu** [comment]
Sorry, but I still have a question, as default, it will build the debug version of the library according to the above command? How can I get the release version? When using release mode in qt creator, the build is successful but cannot run

**Comment by iamsergio** [comment]
I don't know which error you got, so will try to guess you're linking debug kddw to a release app, which msvc doesn't support.

A release version needs to be linked to a release version of kddockwidgets (pass -DCMAKE_BUILD_TYPE=Release when building kddw

Closing this now, as KDDW doesn't have any bug.
