### ISSUE TITLE
Convert cmake to qmake 

### ISSUE THREAD

**Issue by mehrdadpilevar** [KDAB/KDDockWidgets#301]
i have project using qmake i whant import this library from that but its not work

**Comment by mehrdadpilevar** [comment]
how can i use from qmake

**Comment by winterz** [comment]
kddockwidgets does install a qmake ".pri" file under mkspec/modules/qt_KDDockWidgets.pri

you can use that .pri file in your main project's qmake .pro to set the include and librarys paths for KDDockWidgets

**Comment by mehrdadpilevar** [comment]
can you show me a exampli in empty project ??
tnx.

**Comment by mehrdadpilevar** [comment]
I tried to add this library in two ways
1-using add library in qml 
2-using pri file 


after compile and "cmake --build --target install  " make KDAP folder in Drive c


1. **add lib and header file** 

pro file 
```
QT += quick

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        main.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

DEFINES+= KDDOCKWIDGETS_QTQUICK 1

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

unix:!macx|win32: LIBS += -L$$PWD/../../../../KDAB/KDDockWidgets-1.5.99/lib/ -lkddockwidgets1

INCLUDEPATH += $$PWD/../../../../KDAB/KDDockWidgets-1.5.99/include
DEPENDPATH += $$PWD/../../../../KDAB/KDDockWidgets-1.5.99/include

win32:!win32-g++: PRE_TARGETDEPS += $$PWD/../../../../KDAB/KDDockWidgets-1.5.99/lib/kddockwidgets1.lib
else:unix:!macx|win32-g++: PRE_TARGETDEPS += $$PWD/../../../../KDAB/KDDockWidgets-1.5.99/lib/libkddockwidgets1.a

```
2. using KDAB in cpp

```
#include <QGuiApplication>
#include <QQmlApplicationEngine>



#include <kddockwidgets/Config.h>
#include <kddockwidgets/DockWidgetQuick.h>
#include <kddockwidgets/private/DockRegistry_p.h>
#include <kddockwidgets/FrameworkWidgetFactory.h>


int main(int argc, char *argv[])
{
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    KDDockWidgets::Config::self().setQmlEngine(&engine);

    const QUrl url(QStringLiteral("qrc:/main.qml"));
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}
```
in this case i have a error 

Compile out
`:-1: error: [Makefile.Debug:314: debug/qrc_qml.o] Error 1`

**Comment by mehrdadpilevar** [comment]
in the second project using pri file 
pro file 
![Capture](https://user-images.githubusercontent.com/34956619/179367378-de9cffa6-cbc5-49c4-8d78-9b653592bcd3.PNG)

main.cpp
![Capture](https://user-images.githubusercontent.com/34956619/179367411-edf10997-f876-4f18-8cc6-46ef2240a318.PNG)

**Comment by mehrdadpilevar** [comment]
If I made a mistake, please let me know
I don't think it would be bad to give an example for qmake

**Comment by iamsergio** [comment]
can you try CONFIG += C++17 in your pro file ? I don't see any -std= being passed in that command line, and not sure what mingw defaults to.

I haven't used qmake in some years, I'd recommend just using CMake, as TQC isn't developing qmake any further
