### ISSUE TITLE
DockWidget with name "" already exists

### ISSUE THREAD

**Issue by ughstudios** [KDAB/KDDockWidgets#304]
```void __cdecl KDDockWidgets::DockRegistry::registerDockWidget(class KDDockWidgets::DockWidgetBase *) Another DockWidget DockWidget(0x24bcb3c1e60) with name "Logs"  already exists. KDDockWidgets::DockWidgetBase(0x24bcb3c23e0)     ```

How do I deal with this issue? 

I'm trying to make a dialog that is a dock widget that I can toggle with this function:
```
def toggle_logs_dialog() -> None:
    global __visible__
    widget = try_add_dock_widget()
    if __visible__:
        widget.setWidget(None)
        widget.close()
        __visible__ = False
    if not __visible__:
        try_add_dock_widget.cache_clear()
        try_add_dock_widget()
        __visible__ = True
```

But it will not allow me. I tried to use the `hide()` method, but it only hides the widget within the dock widget, not the widget itself. And if I call `close()` I get the result I want, but it will not reopen the widget, I get the above error instead.

**Comment by iamsergio** [comment]
Can you explain that code a bit, after "__visible__ = False" it will enter the "if' unconditionaly ?

Did you mean to use an elif instead of if ?

**Comment by iamsergio** [comment]
Can you push to a github repo, a minimal testcase, so that I can run and debug it ?

**Comment by iamsergio** [comment]
Not yet, I'm not at work this week and I don't have a Python env at hand. Will check Monday

**Comment by iamsergio** [comment]
I've finally got a Python env and build.

I've tried your testcase but nothing happens. Seems to be missing an entry point ?

Please attach a minimal testcase that reproduces the problem.

A minimal testcase has only the required code to reproduce a bug (nothing more), but needs to be runnable.

I'm not a Python developer so I really something that runs out of the box
