### ISSUE TITLE
Docking sometimes failed when dropped on drop indicators

### ISSUE THREAD

**Issue by liszto** [KDAB/KDDockWidgets#306]
Hello !
I'm using Qt 5.14 + Windows 10 + KDDockWidget 1.5
When I release my mouse above the drop indicator, sometimes it matches with the lambda check (every 100ms) and I supposed the mouse left button state between Qt & Window is not the same just at this particular moment and it fails to dock whereas the click release is on an indicator.
If I click and release without moving at the same place it will dock.

I try to comment the code used for the this bugfix ([166](https://github.com/KDAB/KDDockWidgets/issues/166)) and the issue seems gone (I say seems because it's not 100% reproduced) and without the code I can't reproduced the bug mentioned above.

I though maybe it could be better to check if at this particular moment we are in the same "state" than handleMouseButtonRelease in order to call dropped() or draggedCanceled() depending on the situation ? 🤔

Edit: 

I made this and it works fine (maybe not the best solution but at least it will cover your initial case and the one we are facing).
Here a part of your initial StateDragging constructor 
```
        const bool mouseButtonIsReallyDown = (GetKeyState(VK_LBUTTON) & 0x8000);
        if (!mouseButtonIsReallyDown && isLeftButtonPressed()) {
            qCDebug(state) << "Canceling drag, Qt thinks mouse button is pressed"
                << "but Windows knows it's not";
           Q_EMIT q->dragCanceled();
        }
```

and here what we changed 

```
        const bool mouseButtonIsReallyDown = (GetKeyState(VK_LBUTTON) & 0x8000);
        if (!mouseButtonIsReallyDown && isLeftButtonPressed()) {
            qCDebug(state) << "Dropping or Canceling drag, Qt thinks mouse button is pressed"
                << "but Windows knows it's not";
		QPoint globalCursorPos = QCursor::pos();
		handleMouseButtonRelease( globalCursorPos );
        }
```

**Comment by liszto** [comment]
I made this and it works fine (maybe not the best solution but at least it will cover your initial case and the one we are facing).
Here your initial StateDragging constructor 
`StateDragging::StateDragging(DragController *parent)
    : StateBase(parent)
{
#if defined(Q_OS_WIN) && !defined(DOCKS_DEVELOPER_MODE)
    m_maybeCancelDrag.setInterval(100);
    QObject::connect(&m_maybeCancelDrag, &QTimer::timeout, this, [this] {
        // Workaround bug #166 , where Qt doesn't agree with Window's mouse button state.
        // Looking in the Qt bug tracker there's many hits, so do a quick workaround here:

        const bool mouseButtonIsReallyDown = (GetKeyState(VK_LBUTTON) & 0x8000);
        if (!mouseButtonIsReallyDown && isLeftButtonPressed()) {
            qCDebug(state) << "Canceling drag, Qt thinks mouse button is pressed"
                << "but Windows knows it's not";
           Q_EMIT q->dragCanceled();
        }
    });
#endif
}` 
and here what we changed 
`StateDragging::StateDragging(DragController *parent)
    : StateBase(parent)
{
//Commented to fix a docking issue on dock indicator. Without this I can't reproduced their bug 166
#if defined(Q_OS_WIN) && !defined(DOCKS_DEVELOPER_MODE)
    m_maybeCancelDrag.setInterval(100);
    QObject::connect(&m_maybeCancelDrag, &QTimer::timeout, this, [this] {
        // Workaround bug #166 , where Qt doesn't agree with Window's mouse button state.
        // Looking in the Qt bug tracker there's many hits, so do a quick workaround here:

        const bool mouseButtonIsReallyDown = (GetKeyState(VK_LBUTTON) & 0x8000);
        if (!mouseButtonIsReallyDown && isLeftButtonPressed()) {
            qCDebug(state) << "Dropping or Canceling drag, Qt thinks mouse button is pressed"
                << "but Windows knows it's not";

			QPoint globalCursorPos = QCursor::pos();
			handleMouseButtonRelease( globalCursorPos );
        }
    });
#endif
}`

**Comment by iamsergio** [comment]
yeah that's fine, there's not much else we can do here

**Comment by liszto** [comment]
Thanks for the fix integration in your codebase @iamsergio  

You don't need to keep the `Q_EMIT q->dragCanceled();`
because it's already managed by the `handleMouseButtonRelease( globalCursorPos );` for all its states
