### ISSUE TITLE
 KDDockWidgets::LayoutSaver sometimes recreates reduced screen

### ISSUE THREAD

**Issue by cvf-bcn-gituser** [KDAB/KDDockWidgets#313]
Hello,

I am using the   KDDockWidgets::LayoutSaver class to create a "saver" object in my application . It works and the restoreLayout() function works well when with a floating  KDDock widget and the app behaves "faithfully : i.e when you close the app and the floating widget is in a certain position , after restarting the app  this position is reproduced as expected.

However , I upgraded my App (let call it version 2) when I add a login feature to the app and insert the required signals and slots that are triggered on successful login. the app does not re start up again as expected. 

Instead of the  occupying the whole screen, it appears half the intended size. 

I took the JSON file that was saved in version 2  and I placed it in version 1 of the app ( i.e no login feature), the layout was reproduced ok. So it seems there is nothing wrong with the width and height contents in the different attributes of the layout JSON.
The problem appears in the context when the kdockWidget restoreFromFile(..)  is called.

I thought that if I could "hack" what was coming out of JSON I could fix it, but now, this wouldnt work.

I tried the other case , i.e. putting the JSON from version 1 into the exe folder of the Version 2 (with login) and the screen reduction still takes place.

Has anyone else encountered use cases where incorrect restoreFromFile()  happens?

**Comment by iamsergio** [comment]
this will be handled in the internal bug tracker
