### ISSUE TITLE
Allow different settings for floated widgets

### ISSUE THREAD

**Issue by hannescmarits** [KDAB/KDDockWidgets#314]
Hi KDDockWidgets-Team, hi Sergio, 
at the moment it seems to be possible to keep floated widget in front of the main application or allow to minimize and be also in the background of the main application. 
We need the possibility to have both types. 
Have floated widgets which stay always in front of the main application, and
widgets which can be in front or behind the main application. 

If not already possible, this should be provided.

Cheers, Hannes

**Comment by iamsergio** [comment]
Maybe, but needs to be well thought first.

Can two floating windows (with different settings) be tabbed together ? If so, which settings do they acquire ?

**Comment by hannescmarits** [comment]
Hi Sergio, 

you are right, a good question, but maybe it’s not that difficulty.

We have an application, with windows which can be easily docked. 
Other windows are rarely used, or just used to configure something and afterwards closed again. 
But during that time they interact with an docked window. Therefore they should stay in front of the application. 

Other windows may be docked, or not, but may be to big to always stay in front of the our application. 
So it should be possible to bring the application in front of this window. 


So back to your question.
It see two possibilities. 
1. ) It’s not allowed to dock/tab floating windows of different kinds.
2.) It’s configurable if such windows than always stay in front or be minimizable and stay in the background. 


Kind regards,
Hannes

**Comment by iamsergio** [comment]
Ok, sounds good.

1.6 is due today though, I'll try to delay the release by 1 day or so ;)

**Comment by iamsergio** [comment]
Are you OK with using 1.6 branch instead of 1.6 tag ? There's quite some work involved in making a release, which we would have to duplicate

**Comment by hannescmarits** [comment]
Hi Sergio, 
at first i am very happy to hear that you can provide the needed functionality.  This will help us a lot. 
One of the development team will answer your question.
Thanks again and kind regards
Hannes

**Comment by hannescmarits** [comment]
Hi Sergio, 
does the currently released version 1.6 contain this feature?
Kind regards
Hannes

**Comment by iamsergio** [comment]
I does not. I'm trying to implement it this week.

@tlaemmlein Which exact "settings" need to be per-window ? Would the window flags be enough (Qt::Window vs Qt::Tool) ?

**Comment by winterz** [comment]
this new feature will be added into the new 1.7 branch, btw

**Comment by tlaemmlein** [comment]
@iamsergio We need the internal functionality of Flag_TitleBarHasMinimizeButton which is Qt::Window and Qt::Tool (after checking the source code). Hence I'm very sure that Qt::Window and Qt::Tool are enough.

To be more sure you can create an dev branch, where I can test the feature.

**Comment by iamsergio** [comment]
See DockWidgetBase::setFloatingWindowFlags(flags) and set your needed flags, per dock widget.
Call it first thing after creating the dock widget. Needs to be done before show.
I wrote some tests but will appreciate feedback. I'll be back on the 26th

**Comment by iamsergio** [comment]
Branch is 1.7. Which is exactly the same as 1.6 but with this feature on top.

**Comment by tlaemmlein** [comment]
Hi @iamsergio ,
many thanks for implementing this feature. I have two things.
1.
To have the same behaviour like Config::Flag_TitleBarHasMinimizeButton
(See https://github.com/KDAB/KDDockWidgets/blob/1.7/src/Config.h)
I have to set (See https://github.com/KDAB/KDDockWidgets/blob/1.7/src/KDDockWidgets.h)
        auto flags = pSubWnd->floatingWindowFlags();
        flags = KDDockWidgets::FloatingWindowFlag::TitleBarHasMinimizeButton;
        flags |= KDDockWidgets::FloatingWindowFlag::DontUseParentForFloatingWindows;
        flags |= KDDockWidgets::FloatingWindowFlag::UseQtWindow;
In my eyes I would like to set the 'floating' flag also only with FloatingWindowFlag::TitleBarHasMinimizeButton.

Hence it is ok to hide Qt::Tool and Qt::Window. So I think FloatingWindowFlag::UseQtTool and FloatingWindowFlag::UseQtWindow could be removed.

2.
The minimize action doesn't work if the (floating) window is set by the floating flags.
We figure out that TitleBar::onMinimizeClicked (https://github.com/KDAB/KDDockWidgets/blob/1.7/src/private/TitleBar.cpp) is responsible for minimize action.
It would be great to have here a bug fix.

Kind Regards,

Thomas

**Comment by iamsergio** [comment]
1. I've added the extra verbosity/granularity to the API on purpose, in case other users will want different things
2. Is fixed.

**Comment by hannescmarits** [comment]
Hi Sergio,

you are right, a good question, but maybe it's not that difficulty.

We have an application, with windows which can be easily docked.
Other windows are rarely used, or just used to configure something and afterwards closed again.
But during that time they interact with an docked window. Therefore they should stay in front of the application.

Other windows may be docked, or not, but may be to big to always stay in front of the our application.
So it should be possible to bring the application in front of this window.


So back to your question.
It see two possibilities.
1. ) It's not allowed to dock/tab floating windows of different kinds.
2.) It's configurable if such windows than always stay in front or be minimizable and stay in the background.


Kind regards,
Hannes
