### ISSUE TITLE
QML TabBar does not respond to hover events

### ISSUE THREAD

**Issue by ollie-dawes** [KDAB/KDDockWidgets#317]
Hi Guys,
I would like to be be able to set hover styles on my custom tab bar buttons however it looks like something is eating the hover events. Contemplating setting a window wide event filter to pass them through but feels pretty hacky so I thought I'd raise here to see if this is an actual bug first.

This is using the 2.0 branch as of `282c3106a46e5ccc3c4a7fa405b5a817e7468286`

**Comment by iamsergio** [comment]
Hi, which branch ?

**Comment by ollie-dawes** [comment]
I mentioned the branch and commit in the first post, branch `2.0`. 

I just tried updating to the latest commit (https://github.com/KDAB/KDDockWidgets/commit/04df3d5babf9b8489e2a2a8c0a702b58e76cfd88) for the sake of completeness and I get the same issue.

**Comment by iamsergio** [comment]
Events are filtered by C++, which control all the DND code (which is shared with QtWidgets).
I'll add a Q_PROPERTY(bool isHovered

or so ;)

**Comment by ollie-dawes** [comment]
Cheers @iamsergio! Might be good to update the custom quick tabbar example to show that this is something you guys expect to work.

**Comment by iamsergio** [comment]
example updated
