### ISSUE TITLE
QtQuick DockWidget header layout is incorrect when dragging between monitors

### ISSUE THREAD

**Issue by acarlson98** [KDAB/KDDockWidgets#320]
OS: Windows 10
Built with: Visual Studio 16 2019
Qt Version: 5.15.2
KDDockWidgets: 2.0 branch

In both my project and the qtquick_dockwidgets example, when moving a DockWidget separate from the main window to a different monitor, the header layout messes up as shown in the example below. This happens going from left to right monitor, or right to left monitor.

![CrossMonitorLayoutIssue](https://user-images.githubusercontent.com/22945784/195393231-d48fa2f5-05c2-46cd-a954-64f5f23f2e72.gif)

The popout/in and close buttons are also moved, but their original functionality exists in their original location. The popout/in button still works in this state but the layout is still incorrect when popped back out. This is not the case if the DockWidget is dragged out instead.

![CrossMonitorLayoutIssue2](https://user-images.githubusercontent.com/22945784/195401645-e0651ae3-657a-4bba-a9c6-ab26fcaeeea1.gif)

Dragging the dockwidget to the top of the screen to maximize it also causes the layout problem to resolve itself.

**Comment by iamsergio** [comment]
What's your DPI settings on each screen ? (100%, 150% ?)

**Comment by acarlson98** [comment]
Scaling is set to 100% (Recommended) for both monitors. They are both identical Samsung 1080p monitors if that matters.

![image](https://user-images.githubusercontent.com/22945784/195689387-a245c21f-6ad0-4038-8b8b-09ea3a56059d.png)

**Comment by iamsergio** [comment]
Reproduced, thanks

**Comment by iamsergio** [comment]
it's fixed
