### ISSUE TITLE
Move floating window to negative coordinates doesn't work

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#321]
Thank you for fixing https://github.com/KDAB/KDDockWidgets/issues/75

But a floating window can't moved to negative coordinates.

Example: You have two monitors horizontal arranged. The right monitor is the main monitor, which means the left/top corner is the origin. 
Hence the left monitor has negative X values.

If you want to move the floating window to the left monitor with this code:
floating_window>resize(size);
floating_window->move(QPoint(-250, 200);
floating_window>show();

Then the window is open at the right monitor.

And yes it is possible to switch around the code:
floating_window>show();
floating_window>resize(size);
floating_window->move(QPoint(-250, 200);

But then we have the flickering described in https://github.com/KDAB/KDDockWidgets/issues/75

Kind Regards,

Thomas

**Comment by iamsergio** [comment]
Does that even work with non-KDDW pure code ? I'm happy to support it if it's supported by Qt as well

**Comment by iamsergio** [comment]
It should work, but there's a few snags.

Can you print this (in your application, not in a testcase):

```
    for (auto screen : qApp->screens()) {
        qDebug() << screen << screen->geometry() << screen->virtualGeometry() << screen->devicePixelRatio();
    }

```

**Comment by tlaemmlein** [comment]
System: Windows 10 / VS 2019
kddockwidgets version: 1.7.x 

I have observed if the floating window is only a little bit in the negative area then it won't be moved. but if the floating window is total in the negative area then the kddockwidget lib moves it to zero.

Steps:

Change MyMainWindow.cpp to 

 ```
   QAction *newAction = fileMenu->addAction(QStringLiteral("New DockWidget -400x100"));

    connect(newAction, &QAction::triggered, this, [] {
        static int count = 0;
        count++;
        auto w = newMyWidget();
        w->setGeometry(50, 50, 400, 400);
        auto dock = new KDDockWidgets::DockWidget(QStringLiteral("new dock %1").arg(count));
        dock->setWidget(w);
        dock->setGeometry(-400, 100, 500, 500);
        dock->show();
    });

    QAction *newAction1 = fileMenu->addAction(QStringLiteral("New DockWidget -600x100"));

    connect(newAction1, &QAction::triggered, this, [] {
        static int count = 0;
        count++;
        auto w = newMyWidget();
        w->setGeometry(50, 50, 400, 400);
        auto dock = new KDDockWidgets::DockWidget(QStringLiteral("new dock %1").arg(count));
        dock->setWidget(w);
        dock->setGeometry(-600, 100, 500, 500);
        dock->show();
    });

    QAction *newAction2 = fileMenu->addAction(QStringLiteral("New QWidget -600x100"));

    connect(newAction2, &QAction::triggered, this, [] {
        static int count = 0;
        count++;
        auto w = newMyWidget();
![wrong_coordinates](https://user-images.githubusercontent.com/3143027/197470093-5e259b3e-a650-4e13-b868-aeac20706962.gif)

        w->setGeometry(-600, 100, 500, 500);
        w->show();
    });

```
* Setup your two screens: Screen 2 is left to Screen 1 and Screen 1 is the main display.
* Then start kddockwidget example with -k
* Click the three actions

Here see the animation:
![wrong_coordinates](https://user-images.githubusercontent.com/3143027/197470221-aab18b26-e63a-4a05-bb64-edf4037a6fc0.gif)

Kind Regards,

Thomas

**Comment by tlaemmlein** [comment]
Thanks.
