### ISSUE TITLE
QML DockWidget does not emit hidden()

### ISSUE THREAD

**Issue by msarehn** [KDAB/KDDockWidgets#322]
With the current 2.0 branch, the QML DockWidget type's `hidden()` signal is never emitted. There's also no other way for QML to detect that the DockWidget has been closed. This is an issue for us, as we want to destroy dynamically created DockWidgets when they are closed. The auto-delete option doesn't work either.

We could install an event filter to detect this, but it would be nicer for KDDW to just emit the signal correctly.

**Comment by iamsergio** [comment]
trying to repro, will have a look

**Comment by iamsergio** [comment]
Pull 2.0 (or f80bd625171e). At least here and in my test it's fixed.

The signal as been renamed to "closed" instead of "hidden" to avoid confusion.
An open dock widget that is on a non-current tab counts as open, even though it's not visible.

**Comment by msarehn** [comment]
Thanks!
