### ISSUE TITLE
Cannot use KDDW with a QML test runner that runs multiple tests

### ISSUE THREAD

**Issue by msarehn** [KDAB/KDDockWidgets#327]
When using QtQuickTest with multiple test files, the tests all get their own QQmlEngine. However, once     `KDDockWidgets::Platform_qtquick::instance()->setQmlEngine(engine);` has been called, it cannot be called again with another one.

I don't think that fixing this would require porting away from the singleton pattern. Maybe wrapping `Platform_qtquick::m_qmlEngine` in a QPointer is enough so that it detects the destruction of the old QQmlEngine and allows setting a new one.

**Comment by iamsergio** [comment]
Yes makes sense.

**Comment by iamsergio** [comment]
scheduled for Friday
