### ISSUE TITLE
cmake: silence nlohmann-json warning

### ISSUE THREAD

**Issue by olafmandel** [KDAB/KDDockWidgets#328]
For the `2.0` branch, when running `cmake` on a system without the `nlohmann-json` library installed, there was the following loud warning:

```
CMake Warning at src/CMakeLists.txt:539 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nlohmann_json", but CMake did not find one.

  Could not find a package configuration file provided by "nlohmann_json"
  with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

  Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
  "nlohmann_json_DIR" to a directory containing one of the above files.  If
  "nlohmann_json" provides a separate development package or SDK, be sure it
  has been installed.
```

There is no advantage to having this output, the very next line states that this was not found much more quietly:

```
nlohmann_json not found in system. Using our own bundled one
```

Please add the `QUIET` keyword to the `find_package(nlohmann_json)` call: it will get rid of the warning without changing the output in other ways.

**Comment by iamsergio** [comment]
commit dff81befdca0b2f618261773756a2046bff1090d (HEAD -> 2.0, origin/2.0)
Author: Sergio Martins <sergio.martins@kdab.com>
Date:   Fri Nov 18 22:09:05 2022 +0000

    cmake: Add QUIET while finding nholman
    
    It's fine if it's not found
