### ISSUE TITLE
Question about KDDW and Application style

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#330]
Hi,
According to official documentation of [QApplication::setStyle](https://doc.qt.io/qt-6/qapplication.html#setStyle): "... QApplication will delete the style object ... or **when a new style is set and the old style is still the parent of the application object**". 
[Ctor](https://github.com/KDAB/KDDockWidgets/blob/1.7/src/private/widgets/TabBarWidget.cpp#L35) `KDDockWidgets::anonymous::MyProxy` changes (through `QProxyStyle`) the parent of Application style so calling of QApplication::setStyle later does not remove the previously set style! 

Is this behavior legal (the user code does not know about it)!?

**Comment by iamsergio** [comment]
It's legal and documented in QProxyStyle docs.
From user's pov, it shouldn't make much difference if the style is deleted by QProxyStyle or QApplication.

But maybe we can improve, if it's causing trouble
