### ISSUE TITLE
Hide the drop indicators

### ISSUE THREAD

**Issue by hannescmarits** [KDAB/KDDockWidgets#334]
Hi,
one of our customers mentioned the desire to hide the drop indicators while moving a floating window.
Taking a look at Visual Studio revealed that it provides such functionality. 
Pressing the CTRL key, while a floating window is moved hides the drop indicators. 
 Would be nice if such functionality would also be offered by KDDockWidgets.
 Regards
 Hannes

**Comment by iamsergio** [comment]
Hi,

We expose API so applications can do this.

Call this once in main:

`KDDockWidgets::Config::setDropIndicatorAllowedFunc()` , where inside the provided lamda you can check if the ctrl key is pressed and return false;

or call this whenever ctrl is pressed

`KDDockWidgets::Config::setDropIndicatorsInhibited(bool);`

**Comment by hannescmarits** [comment]
Thanks a lot for the informationen

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
