### ISSUE TITLE
Assert in Multisplitter

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#336]
Hi, there is repro of assert on some dokcs configurations ([changes.txt](https://github.com/KDAB/KDDockWidgets/files/10453519/changes.txt), kddockwidgets_minimal_example)

![docking](https://user-images.githubusercontent.com/7323010/213354790-4c9faecb-12cd-40e3-8678-8359fed3d60c.gif)

For branch 1.7:
![image](https://user-images.githubusercontent.com/7323010/213356198-c0391053-5d27-41df-b99b-00121031d6e0.png)

Environment:

Windows 10 (64bit);
KDDW v1.4.0, v1.5.0, branch 1.7

**Comment by iamsergio** [comment]
will try to repro next Friday

**Comment by iamsergio** [comment]
```
$ git apply ~/Downloads/changes.txt 
error: patch failed: examples/minimal/main.cpp:39
error: examples/minimal/main.cpp: patch does not apply
```

Does it apply for you ? please rebase over 1.7

**Comment by amuralev** [comment]
Please try [changes2.txt](https://github.com/KDAB/KDDockWidgets/files/10519163/changes2.txt)
