### ISSUE TITLE
Re:  Hide the drop indicators #334 

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#337]
Hi sergio,

the provided way to set a DropIndicatorAllowedFunc is not completely satisfying because it is only evaluated at the start of the dragging operation.
We need a way to show / hide the drop indicators also during the dragging similar to the way Visual Studio works

![docking-inidcator](https://user-images.githubusercontent.com/11087133/213415529-4217a3eb-f544-4be6-82fe-9e219e83b068.gif)

Best regards,
Philipp

**Comment by iamsergio** [comment]
ok will have a look.
when do you need it done ?

**Comment by pklaffert** [comment]
Hi,

it is not, too urgent but it would be nice to have by mid / end of February.

**Comment by iamsergio** [comment]
This is done, you'll need to pull the latest 1.7 which has a bug fix in the library.
It also has an example of how to use the KDDW API to achieve this, see commit af455bb37edd2e6471f2e3929914a4ffc196af46

The requirement itself is not generic enough to make it to the library, but can easily be done on the app side, as shown in the example.
