### ISSUE TITLE
EGLFS: OpenGL windows cannot be mixed with others

### ISSUE THREAD

**Issue by giridhar123** [KDAB/KDDockWidgets#342]
Hello everybody. I got a cross-compile environment with these details:
Qt version: 6.4.2
host OS: Ubuntu
host architecture: x86
target OS: Raspberry Pi OS
target architecture: arm32

I can compile a simple QML application and run it onto Raspberry Pi but if I use the "KDDockWidgets" library and put the "DockingArea" and a "DockWidgets" object inside a QML file, the application crash with the following error:
"EGLFS: OpenGL windows cannot be mixed with others".
The library is cross-compiled. In the README file of this repostiory, it is written that EGLFS is supported. What am I doing wrong?

Thanks in advice.

**Comment by iamsergio** [comment]
I don't think Qt supports multi window on EGLFS with QtQuick (Only with QtWidgets).
Can you try a minimal, non-kddw app, which opens a separate Window {}

**Comment by giridhar123** [comment]
I did it and I got the same error
