### ISSUE TITLE
Layout restore under QtQuick can unintentionally hide the main window

### ISSUE THREAD

**Issue by petrmanek** [KDAB/KDDockWidgets#343]
I am trying to get `LayoutSaver` to work with QtQuick, and have encountered an interesting situation. Not sure if it is a bug, however it may be source of annoyance, and the creators of this library should know about it.

The conditions to reproduce are as follows:

- Put your `KDDW.DockingArea` inside a `StackLayout` with at least two views.
- Populate docking area with some widgets, does not matter how many.
- Switch `StackLayout.currentIndex` to the view that is not the docking area.
- Use `LayoutSaver` to serialize the layout to JSON.

If you inspect the JSON, you will find that the main window has the `isVisible` attribute set to `false` because of [this logic][1]. While this is technically true that the docking area was not visible at the time of serialization, it is not very practical because when you later attempt to restore the JSON layout (regardless of the value of `currentIndex`), your entire `QQuickWindow` will receive `setVisible(false)`, which is undesirable.

My current workaround for this is to always explicitly switch the `StackLayout` to the view with my docking area before saving the layout, and then switch back to any other view if needed. However, I could easily imagine a scenario with multiple docking areas which are visible/hidden at different times, where this would not be tractable.

[1]: https://github.com/KDAB/KDDockWidgets/blob/2.0/src/qtquick/views/View_qtquick.cpp#L327

**Comment by iamsergio** [comment]
done!

**Comment by petrmanek** [comment]
@iamsergio Brilliant, thank you!
