### ISSUE TITLE
How to make floating window with fixed size

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#345]
I want to have a floating window with a fixed size

        ```
       auto w = newMyWidget();
       auto dock = new KDDockWidgets::DockWidget(QStringLiteral("new dock %1").arg(count),
                           KDDockWidgets::DockWidget::Option_NotDockable);
        
        w->setFixedSize(600, 600);                       // Does not make the size fixed
        dock->setWidget(w);         
        dock->setFixedSize(600, 600);                  // Does not make the size fixed
        dock->show();

        dock->window()->setFixedSize(600, 600); // Does not make the size fixed
        ```

How can I achieve this?

**Comment by iamsergio** [comment]
Hi,

Can you try kddockwidgets_example -g

That calls: myWidget->setMaximumSize(200, 200); which works
Replacing with myWidget->setFixedSize(200, 200); works as well.

Maybe there's an edge case where this doesn't work. Ideally please show through modifying the example (attach a patch that I can repro).

Or maybe it's platform specific, we'll find out.

**Comment by pklaffert** [comment]
Hi Sergio,

myWidget->setMaximumSize works. What does not work is to have a fixed size floating window. 

![not-fixed](https://user-images.githubusercontent.com/11087133/221604504-f8a29ee8-e96d-447f-be44-17447f4b38d2.gif)

I am using kddw 1.7 from today on windows 10

**Comment by iamsergio** [comment]
So you're saying, if you edit MyMainWindow.cpp , and replace "setMaximumSize" with "setFixedSize" it stops working ?

I've tried on Windows 10 / Qt 5 / KDDW-1.7 latest , and both work, floating window is not resizable past its max

Do you have maybe other changes in MyMainWindow.cpp that are conflicting ?

**Comment by pklaffert** [comment]
No. No other changes. Clean build. Using Qt 5.15.1 and KDDW in release build.

**Comment by iamsergio** [comment]
Can you:
- Checkout branch test/345
- Build and run the example (no -g needed, it's implied in this test)
- Make dockwidget 8 float, then make it have a too big size
- Press the "dump debug" button
- Paste the results here (qDebug statements are printed to the terminal)

**Comment by pklaffert** [comment]
Widget:  QRect(0,0 250x250) QSize(250, 250) QSize(-1, -1) QSize(250, 250) QSize(-1, -1) KDDockWidgets::FloatingWindowWidget(0x2a09a44f0a0)
TLW   :  KDDockWidgets::FloatingWindowWidget(0x2a09a44f0a0) QRect(97,412 1000x762) QSize(262, 292) QSize(262, 292) QSize(262, 292) QSize(262, 292)
Window   :  QWidgetWindow(0x2a09a6dd010, name="KDDockWidgets::FloatingWindowClassWindow") QRect(104,412 986x755) QRect(97,412 1000x762) QSize(262, 292) QSize(262, 292) QRect(104,412 986x755) QFlags<Qt::WindowType>(Window|WindowTitleHint|WindowSystemMenuHint|WindowMinMaxButtonsHint|WindowCloseButtonHint|WindowFullscreenButtonHint)

**Comment by iamsergio** [comment]
This is even more strange, as your floating windows have Qt::Window instead of Qt::Tool.

The example might be picking some other KDDW dll you have, possible patched with different Config::flags() ? please double check.

meanwhile I'll prepare another round of debug info to figure this out :)

**Comment by pklaffert** [comment]
This time I did a fresh clone of the kddw repo:

```
Widget:  QRect(0,0 250x250) QSize(250, 250) QSize(-1, -1) QSize(250, 250) QSize(-1, -1) KDDockWidgets::FloatingWindowWidget(0x2c0c164a030)
TLW   :  KDDockWidgets::FloatingWindowWidget(0x2c0c164a030) QRect(97,412 704x638) QSize(262, 292) QSize(262, 292) QSize(262, 292) QSize(262, 292)
Window   :  QWidgetWindow(0x2c0c16a8b20, name="KDDockWidgets::FloatingWindowClassWindow") QRect(104,412 690x631) QRect(97,412 704x638) QSize(262, 292) QSize(262, 292) QRect(104,412 690x631) QFlags<Qt::WindowType>(Window|WindowTitleHint|WindowSystemMenuHint|WindowMinMaxButtonsHint|WindowCloseButtonHint|WindowFullscreenButtonHint)
```

Same results.

**Comment by iamsergio** [comment]
ok, please pull test/345 again (should be 3e6e090d266) and repeat please
there will new debug info printed

**Comment by pklaffert** [comment]
```
Flags:  QFlags(0x2) QFlags()
Widget:  QRect(0,0 250x250) QSize(250, 250) QSize(-1, -1) QSize(250, 250) QSize(-1, -1) KDDockWidgets::FloatingWindowWidget(0x2922b8e6920)
TLW   :  KDDockWidgets::FloatingWindowWidget(0x2922b8e6920) QRect(97,412 501x475) QSize(262, 292) QSize(262, 292) QSize(262, 292) QSize(262, 292)
Window   :  QWidgetWindow(0x292295c0ee0, name="KDDockWidgets::FloatingWindowClassWindow") QRect(104,412 487x468) QRect(97,412 501x475) QSize(262, 292) QSize(262, 292) QRect(104,412 487x468) QFlags<Qt::WindowType>(Window|WindowTitleHint|WindowSystemMenuHint|WindowMinMaxButtonsHint|WindowCloseButtonHint|WindowFullscreenButtonHint)

```

**Comment by iamsergio** [comment]
Thank you, that helped me track down a local problem. My example for some reason was running with "compatibility for windows 8".

Disabling that, I've now reproduced your problem
