### ISSUE TITLE
How to move the titleBar to the bottom and specify the titleBar width?

### ISSUE THREAD

**Issue by ilongshan** [KDAB/KDDockWidgets#347]
Hi,

Is there any way to move the titleBar to the bottom and specify the titleBar width when group them together like the following image shows?

<img width="233" alt="image" src="https://user-images.githubusercontent.com/7447401/222107064-05b86e29-b0a2-4945-8ba6-d88e8d52453e.png">

Regards,
Longshan

**Comment by iamsergio** [comment]
This is not supported out of the box.
Try subclassing FrameworkWidgetFactory and providing your own QTabBarWidget subclass, which you can paint as you like.
