### ISSUE TITLE
1.7 planning

### ISSUE THREAD

**Issue by GitMensch** [KDAB/KDDockWidgets#349]
Sadly the [milestones](https://github.com/KDAB/KDDockWidgets/milestones) do not contain an entry for 1.7.
The last release is 1.6.

As I'm using the last release and have not seen any planning issue- can you please share some insights on your release planning / ETA?

Note: I'm not waiting for any specific commit (but wonder about issues I've seen in Hotspot https://github.com/KDAB/hotspot/issues/339 https://github.com/KDAB/hotspot/issues/467 that are _possibly_ related to KDDockWidgets)

**Comment by iamsergio** [comment]
I don't think KDDW 1.7 fixes those hotspot bugs. Maybe you can easily try updating KDDW and confirm.

**Comment by iamsergio** [comment]
Maybe in 2 months we'll do a 1.7 release, we're still gathering more fixes

**Comment by GitMensch** [comment]
Thanks for the note, so the 1.7 entry in https://github.com/KDAB/KDDockWidgets/blob/1.7/Changelog is what is in the version and "whatever gets in is in (no published plans)", right?

Note that it is still unclear what the underlying issues are, it _may_ be related to these widgets (or QT) used with QT_QPA_PLATFORM=xcb.

**Comment by iamsergio** [comment]
yes. I'll try to repro the & problem and confirm if it's a kddw problem
will comment in hotspot tracker
