### ISSUE TITLE
DockWidget's isFloating property does not reliably indicate if the DockWidget is docked or not in Qt Quick

### ISSUE THREAD

**Issue by oleyniko5** [KDAB/KDDockWidgets#350]
Hello,

I am looking into how to detect when a DockWidget is being docked or undocked via a notification in Qt Quick. From the documentation, it looked like the property `isFloating` is the property that signals of that event with the signal `isFloatingChanged`. However, that did not do what I expected in my tests. 

Specifically, the property value is not consistently changed to False if the `DockWidget` is docked back in. There isn't an obvious pattern to nail when it does and when it fails to do so.

The problem is easily reproducible in the Qt Quick example. Apply the patch below, and observe the text in the footer of the application window; the text in the footer reflects the `isFloating` value of dock4. Then, dock and undock dock4 to note inconsistent behaviour.

This behaviour is observed in both 2.0 and in 1.x versions. Tested on Ubuntu 20.04, with Qt 6.2.4 and Qt 6.4.2.

```
diff --git a/examples/qtquick/dockwidgets/main.qml b/examples/qtquick/dockwidgets/main.qml
index fb500cd6..af87a78b 100644
--- a/examples/qtquick/dockwidgets/main.qml
+++ b/examples/qtquick/dockwidgets/main.qml
@@ -18,6 +18,10 @@ ApplicationWindow {
     width: 1000
     height: 800

+    footer: Label {
+        text: "dock 4 is floating: " + dock4.isFloating
+    }
+
     menuBar: MenuBar {
         Menu {
             title: qsTr("&File")
```
Refer to the clip below for a demo 

![kddw_quick](https://user-images.githubusercontent.com/96281602/223911146-2c968c50-778e-4bc4-8164-7e4478b7201d.gif)

**Comment by iamsergio** [comment]
reproduced

**Comment by iamsergio** [comment]
fixed
