### ISSUE TITLE
Assertion triggered when trying to serializeLayout with open DockWidgets in MDIArea

### ISSUE THREAD

**Issue by sblkr** [KDAB/KDDockWidgets#352]
Hi,

when trying to serialize the layout with open dockwidgets in an MDIArea an assertion is triggered:
`ASSERT: "mainWindow || fw" in file KDDockWidgets/src/private/Position.cpp, line 180.`

You can trigger this issue by modifying the mdi_with_docking example. Just insert the following code right before `return app.exec();`

```cpp
mainWindow.setMenuBar(new QMenuBar());

const auto pMenu = new QMenu("Layout");
const auto pAction = new QAction("Save...");
mainWindow.menuBar()->addMenu(pMenu);
pMenu->addAction(pAction);

QObject::connect(pAction, &QAction::triggered, &mainWindow, []()
{
    KDDockWidgets::LayoutSaver saver;
    saver.serializeLayout();
});
```

and trigger the action from the menu.

Thanks!

**Comment by iamsergio** [comment]
This crash is fixed.
I've opened #353 to test if it actually restores the layout correctly.

**Comment by sblkr** [comment]
Thank you <3
