### ISSUE TITLE
Window jumps across monitor boundaries

### ISSUE THREAD

**Issue by clickingbuttons** [KDAB/KDDockWidgets#354]
I'm using i3wm. When moving windows across monitors (that are all the same) this bug happens.

![bug](https://user-images.githubusercontent.com/43246297/228659079-db3c0ae0-561b-40d9-9e56-e3045aaa391d.gif)

It doesn't happen exactly on the boundary. Oddly enough it seems to only happen while moving in one direction. That direction is determined by which half of the window I drag.
![image](https://user-images.githubusercontent.com/43246297/228659977-59041d4c-995c-41ed-83e3-6b0c36bfadd0.png)

**Comment by iamsergio** [comment]
I'm not surprised and I've seen similar bugs with less used window managers.
This is probably either a bug in Qt or in i3 with frameless windows, as KDDW just uses Qt to drag the window.

For me this is out of scope and I need to focus on other things
