### ISSUE TITLE
"... Unable to set geometry ..." if dock-widget undocked at negative screen coordinates

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#358]
I get a "QWindowsWindow::setGeometry: Unable to set geometry ..." message printed, when I undock a dock-widget within a screen, which has negative coordinates.

For example, I have three screens where the rightmost is the primary one. Therefore the center and right screen have all negative x coordinates.
In a simple example I create a `MainWindow` and add a `DockWidget` to it. 
If I undock the dock-widget while the main-window is within the center or left screen the following message is printed. This doesn't happen, if the main-window is within the right screen.

> ```QWindowsWindow::setGeometry: Unable to set geometry 598x394+0+369 (frame: 598x394+0+369) on QWidgetWindow/"KDDockWidgets::FloatingWindowClassWindow" on "\\.\DISPLAY6". Resulting geometry: 614x433-8+338 (frame: 614x433-8+338) margins: 0, 0, 0, 0 minimum size: 88x128 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=88,128 maxtrack=0,0)```

I found this Issue  #321, which is not related directly, but the problem reasons could be similar.

**Comment by iamsergio** [comment]
Is there any visual problems besides the message ? afaik windows will place it at the correct position and account for the 8px frame margin. 

It's difficult to fix this in kddw as every window manager is different

**Comment by bbc131** [comment]
No, I don't see any visual problems, it's just the message.

**Comment by iamsergio** [comment]
Ok will close. It's a very common message on Windows, even with non-KDDW Qt applications
