### ISSUE TITLE
Disable Float- and Auto-Hide-Button

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#359]
Is there a simple way to disable the title bars Float-Button and Auto-Hide-Button at the same time?
The flag `Config::Flag_TitleBarNoFloatButton` implicitly enables the Auto-Hide-Button (the one with the pin icon) for docked widgets.

Currently I see only two ways, which are both not very elegant I think. 
Either I override `FrameworkWidgetFactory::createTitleBar` which delivers my customized `TitleBar` in which I should call `m_floatButton->setVisible(false)` in the right situations. Or, I override `FrameworkWidgetFactory::createTitleBarButton` and I implement a dummy button which is simply empty and of zero size.

**Comment by iamsergio** [comment]
Which version ? 
Are you using Config::Flag_AutoHideSupport by any chance ?

This sounds like a bug

**Comment by bbc131** [comment]
I'm using 1.7

No, I only set `Flag_TitleBarNoFloatButton`, see my small example below. There the output is `flags=0x00004002`

Maybe for clarification, the Auto-Hide-Button appears only if docked, see the screenshot. If I undock it (floating) then it's all fine.

```cpp
int main(int argc, char** argv)
{
    QApplication app(argc, argv);

    auto flags = KDDockWidgets::Config::self().flags();
    flags |= Config::Flag_TitleBarNoFloatButton;
    fprintf(stderr, "flags=0x%08x\n", flags);
    KDDockWidgets::Config::self().setFlags(flags);

    KDDockWidgets::MainWindow mainWindow(QStringLiteral("MyMainWindow"));
    mainWindow.setWindowTitle("MyMainWindow");
    mainWindow.resize(600, 400);
    mainWindow.show();

    auto dock1 = new KDDockWidgets::DockWidget(QStringLiteral("MyDock1"));
    mainWindow.addDockWidget(dock1, KDDockWidgets::Location_OnLeft);

    auto dock2 = new KDDockWidgets::DockWidget(QStringLiteral("MyDock2"));
    mainWindow.addDockWidget(dock2, KDDockWidgets::Location_OnRight);


    return app.exec();
}
```

![grafik](https://github.com/KDAB/KDDockWidgets/assets/36670201/f70ddf40-34f6-493b-a6f4-19c414ec9fea)

**Comment by iamsergio** [comment]
done! thanks for the example code
