### ISSUE TITLE
`cmake --install ... --prefix ...` broken

### ISSUE THREAD

**Issue by skoslowski** [KDAB/KDDockWidgets#361]
The CMake configuration uses `CMAKE_INSTALL_PREFIX` in several places, generating install scripts with fixed absolute paths. This breaks prefix overriding during install using e.g. `cmake --install ... --prefix ...`. 

To remedy this, consider replacing the use of `CMAKE_INSTALL_PREFIX` with `.` when setting `${PROJECT_NAME}_PYTHON_BINDINGS_INSTALL_PREFIX `.

**Comment by winterz** [comment]
please try this patch:

[PYTHON_BINDINGS_INSTALL_PREFIX.txt](https://github.com/KDAB/KDDockWidgets/files/11477673/PYTHON_BINDINGS_INSTALL_PREFIX.txt)

**Comment by skoslowski** [comment]
Thanks for the fast response. This works, if the now duplicated `INSTALL_LIBRARY_DIR` here
https://github.com/KDAB/KDDockWidgets/blob/ede69197ed2c91ee0aec8f9eb44bbc5e3b20e960/python/CMakeLists.txt#L38
is removed. Minor comment here: the `pythonX.YY/` subdir, is quite natural on Linux. On windows less so.

**Comment by winterz** [comment]
let me know if e7c9a20752d7b425e80f0ec44802c66ba693c84c  works for you

**Comment by skoslowski** [comment]
Sorry for the delay. 
It works. Thanks.
