### ISSUE TITLE
Floating windows increase size on restoration

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#371]
When I save and restore the layout of some dockwidgets, I experience the problem, that floating windows are restored with an increased size.

This can be reproduced with the *kddockwidgets_example*: 
I placed two floating windows in front of the mainwindow (mainwindow is restored correctly). Then I simply save the layout and restore it again via *Save Layout* / *Restore Layout* in the *File* menu. On restore, the two floating windows change their size as can be seen in the screenshots.

**Before**
![20230704_before](https://github.com/KDAB/KDDockWidgets/assets/36670201/788e8309-fa37-495f-bcf3-7df5fd8ae141)

**Restored**
![20230704_after](https://github.com/KDAB/KDDockWidgets/assets/36670201/c7e377f1-e024-4a62-86eb-e62ff1d08083)

**Two observations:**

1. This happens only if I place the mainwindow on screen 1 or 2 of my 3 screens. 
When I place the mainwindow on screen 3, it works perfectly fine.
It is independent of where the floating windows are placed. This means, I can place one floating window on each screen and depending on where the mainwindow is placed, the problem occurs for all or for none of the floating windows.
I'm using Win10 with three screens aligned as can be seen below. Screen 3 is the primary screen.
![20230704_screen_setup](https://github.com/KDAB/KDDockWidgets/assets/36670201/55ce24a5-63f6-4d64-8591-c5b8748b4795)

2. If the problem occurs, I get the following prints:

```
QWindowsWindow::setGeometry: Unable to set geometry 213x148-2701+57 (frame: 213x148-2701+57) on QWidgetWindow/"KDDockWidgets::FloatingWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 229x187-2709+26 (frame: 229x187-2709+26) margins: 0, 0, 0, 0 minimum size: 35x38 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=35,38 maxtrack=0,0)
QWindowsWindow::setGeometry: Unable to set geometry 241x176-2756+316 (frame: 241x176-2756+316) on QWidgetWindow/"KDDockWidgets::FloatingWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 257x215-2764+285 (frame: 257x215-2764+285) margins: 0, 0, 0, 0 minimum size: 35x38 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=35,38 maxtrack=0,0)
```
This reminds me on issue #358, maybe it is related.

**Comment by Chicou** [comment]
Yep same issue
The floating window on thje second screen is 8 pixel ( left right & up & down ) bigger than the screen size....

**Comment by iamsergio** [comment]
@Chicou Windows too ?

**Comment by Chicou** [comment]
yep windows too... 


sorry i forgot to mention it 
----- Mail original -----

De: "Sergio Martins" ***@***.***> 
À: "KDAB/KDDockWidgets" ***@***.***> 
Cc: "Chicou" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 8 Août 2023 15:02:36 
Objet: Re: [KDAB/KDDockWidgets] Floating windows increase size on restoration (Issue #371) 



@Chicou Windows too ?

**Comment by bbc131** [comment]
This problem is still present, are there any plans to address it?

**Comment by iamsergio** [comment]
@bbc131 I'm trying to reproduce, but no luck so far.

What's your Qt version and KDDW version ?
If you by now upgraded to Windows 11, let me know if it's repro there as well.
Next time you test, please also make sure you don't have HDPI scaling on any (unless that's the culprit ofc), trying to figure out what's different in the setups.
I assume your main monitor is #3 ?

**Comment by bbc131** [comment]
I still can reproduce it as described above with Qt 5.15.8; Win 10 and KDDW main branch as of today.

> I assume your main monitor is #3 ?

That's right.

**Comment by bbc131** [comment]
The issue is reproducible with Qt 5.15.8; Win 10 and KDDW main branch as of today.
But just checked with Qt6, there the problem seems to be gone. I cannot reproduce it with the kddw example as described above (used a Qt 6.6.2 build).

We will update to Qt 6 in the near future, so if this will fix the problem, this issue has no priority anymore for me.

**Comment by iamsergio** [comment]
It's hard to workaround Win10 or Qt5 specific issues. For Qt6 we can always work with upstream and try to get a fix merged there or a workaround in KDDW if not too intrusive.
