### ISSUE TITLE
Programmatical resize of DockWidget doesn't work

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#380]
I'm not able to change the size of a `KDDockWidgets::DockWidget` using `resize()`.

I have a simple scenario with two dockwidgets next to each other within a mainwindow.

As an example, I modified the `kddockwidgets_example`:
I disabled all but the first two dockwidgets and changed the size of the mainwindow to 300/300.
Now I want the two dockwidgets to share the space not equally but rather 1:2, i.e. the left dockwidgets width shall be half the width of the right one. Therefore I call `resize()` of the left dockwidget with a width of 1/3 of the mainwindows width.
I experience that the picture within the left dockwidget changes its size, but the dockwidget itself doesn't (see screenshot).

Is there a different way to resize a dockwidget programmatically?

![image](https://github.com/KDAB/KDDockWidgets/assets/36670201/a1669eda-3fc6-4d3f-90e0-ee9e6419e680)

**Comment by iamsergio** [comment]
I don't think it's possible to use resize directly, instead, the way is to use the Separator class, (which represents the movable splitter.

QWidgets are "dumb" and don't drive geometry. Geometry is driven by the underlaying layout. Item class and Separator class. This is however very low level API, probably not documented

**Comment by bbc131** [comment]
I tried `Separator::move(..)` and `Item::setSize(..)`, which both doesn't work. 
`Separator::move(..)` doesn't seem to trigger the updating of the adjacent items, whereas `Item::setSize(..)` resizes this one item but doesn't make the separator move nor the other item to adjust its size.

The only way I found now is using `ItemBoxContainer::requestSeparatorMove(..)`.
This is actually triggered, when moving the separator manually by click'n'drag.

This is, as you said, very low level, and I think it's missing something on a higher level to be able do this.
So this is not satisfying, also because I need to do this via the python bindings.

**Comment by bbc131** [comment]
Yes, this is what I need.

It is just important that this doesn't implicitly changes the size of the window.
Only the distribution of space between the neighbouring DockWidgets should be affected.

**Comment by iamsergio** [comment]
`requestResize(QSize)` won't be enough. When resizing a dockwidget it will remove space from its neighbors,  potentially undoing other requestResize() calls.

Instead, I'm implementing `DockWidget::adjustSize(int left, int top, int right, int bottom)`, which will allow to resize as well, but you'll be able to specify which sides the extra size comes from

**Comment by iamsergio** [comment]
This is working now to resize along the layout's orientation.

i.e.: For dockwidgets layed-out horizontally, you can resize left/right.

Working on cross-axis resize now

**Comment by iamsergio** [comment]
This is done please test

**Comment by bbc131** [comment]
Seems to work, thank you!

**Comment by ihmin** [comment]
Is there a simple example of how to manually resize a KDDockWidgets::QtWidgets::DockWidget?
