### ISSUE TITLE
mainwindow with a custom titlebar

### ISSUE THREAD

**Issue by ixlm** [KDAB/KDDockWidgets#381]
Is't possible to create a mainwindow with a custom titlebar ,  the native titlebar is not suitable for my project.  i modified the code and implemented it by using the floatingwindow as a fake mainwindow, the only question was when i closed the fake mainwindow, the other floatingwindows still kept open.

**Comment by iamsergio** [comment]
yeah it's not possible to customize the main window's titlebar, at least not with KDDW api.

You can do it with pure-Qt API though, search for: Qt custom titlebar

**Comment by ixlm** [comment]
> yeah it's not possible to customize the main window's titlebar, at least not with KDDW api.
> 
> You can do it with pure-Qt API though, search for: Qt custom titlebar

thank you! you're right, in fact there isn't any offical way to implement it.  but by trying many different ways, i finally solve it . i don't know whether it is right.
-----------------------------------------------------------------------------------
in the custom titlebar , i override the method onMinimizeClicked
```
	void app_title_bar_widget::onMinimizeClicked()
	{
		auto win_list = QGuiApplication::allWindows();
		for (int i = 0; i < win_list.size(); i++)
		{
			win_list[i]->showMinimized();
		}
	}
```
int the custom floatingwindow, event method is also been overrided .
```
	bool app_main_window::event(QEvent* ev) 
	{
		if (ev->type() == QEvent::WindowStateChange)
		{
			QWindowStateChangeEvent* change_ev = static_cast<QWindowStateChangeEvent*>(ev);
			if (change_ev && change_ev->oldState() == Qt::WindowMinimized) // the state changes from minimized to anything else
			{
				auto win_list = QGuiApplication::allWindows();
				for (int i = 0; i < win_list.size(); i++)
				{
					win_list[i]->showNormal();
				}
			}
		}
		return KDDockWidgets::FloatingWindowWidget::event(ev);
	}
```
it works fine for me by now!
