### ISSUE TITLE
No `focusChanged` signal on clicking on tabbed `DockWidget`

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#387]
I have a problem with detecting, when a tabbed DockWidget becomes the visible DockWidget, i.e. becomes the one in the foreground.

I noticed, that clicking on the tab of a DockWidget brings this into foreground but not necessarily gives focus to this DockWidget.

In the first place I didn't noticed, that the missing focus here could be a bug until I came across issue #188, so maybe there is a regression on this issue. See details on how I reproduce this below at "Focus on click on tab".

If this isn't considered as a bug, then it would be good to have the means to detect if the DockWidget in the foreground changed, see some notes on this below at "Frame::currentDockWidgetChanged".

**Focus on click on tab**
To reproduce this, use the `kddockwidgets_example` and simply add the following lines in the constructor of `MyMainWindow`:

```
    for (auto &dock : m_dockwidgets) 
    {
        connect(dock, &KDDockWidgets::DockWidgetBase::isFocusedChanged, [&dock](bool is_focused) {
            if (is_focused) {
                printf("%s got focus\n", dock->uniqueName().toStdString().c_str());
            }
        });
    }
```
If you click on the tab of any of the tabbed DockWidgets, you get the `isFocusedChanged` signal only of one of the DockWidgets within this group of tabs already has focus.
In Detail: In the example DockWidget #&#x2060;3 and #&#x2060;5 are tabbed together by default, and DockWidget #&#x2060;2 is visible separately.
If you click into DockWidget #&#x2060;2 it gets focus. If you then click to the tabs of DockWidget #&#x2060;3 or #&#x2060;5 those won't get focus. Only after you clicked into DockWidget #&#x2060;3 or #&#x2060;5 such that one of them has focus, clicking on their tabs will also switch focus between them.

**Frame::currentDockWidgetChanged**
The only way I found to detect if the DockWidget in the foreground changed is with the signal `currentDockWidgetChanged` of the `Frame` class.
This doesn't seem to be straightforward since the frames are created and destroyed as you drag'n'drop DockWidgets and a frame may contain multiple DockWidgets. Also, the frame of a DockWidget is only accessible via something like `dock->titleBar()->tabBar()->frame()`.
So, if the focussing issue from above isn't considered as a bug, here is something more accessible needed.

**Comment by iamsergio** [comment]
which version is this ?

**Comment by bbc131** [comment]
Just checked: This is the case for release 1.7.0 and the branches 1.7 and 2.0

**Comment by iamsergio** [comment]
Hi,

"focus" is related to keyboard focus, for being the "current tab" I'll check if there's more suitable public API

**Comment by iamsergio** [comment]
Any chance you could use 2.0 branch ? There's some minor API break, but should be as stable as 1.7 with more features

**Comment by bbc131** [comment]
Thank you, I'll look into that!

**Comment by iamsergio** [comment]
Are you on Python or C++ ? Python bindings probably need to be regenerated

**Comment by bbc131** [comment]
We use KDDockWidgets via the Python bindings.

**Comment by iamsergio** [comment]
Reopen if required

**Comment by bbc131** [comment]
Thanks, this works!
