### ISSUE TITLE
Crash in 2.0 when docking to a QtWidgets window and moving window to another display

### ISSUE THREAD

**Issue by Cuperino** [KDAB/KDDockWidgets#389]
This crash happens under both X11 and Wayland, when using KDDW with QtWidgets and docking.
Issue might affect other systems, I've only replicated under Linux.

## Pre-requirements
* Use a system with multiple displays.
* Test on a QtWidgets application

## To replicate
1. Start any official QtWidgets example that allows docking. 
2. Grab any dock widget out into its own window (or a dock that is already in its own separate window), and let go docking into any other window.
3. Move the window you just docked into to a different display. 

## Outcome
* KDDW example crashes with: "pure virtual method called"
   "terminate called without an active exception"
* Crash occurs at: View.cpp#309
* The bug appears to have been introduced in commit: e843e8c48aca80361b5f4df43d6ed2590d321119

**Comment by iamsergio** [comment]
fixed in latest 2.0
