### ISSUE TITLE
Prevent undocking on double click

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#409]
Is there any way to prevent the DockWidgets from undocking in the event of a double click within the DockWidget or some contained widget?

I would have expected a Config flag.

**Comment by iamsergio** [comment]
I can't reproduce double-clicking on the contained widget.
I'd say that's unexpected and a bug if it happens, no config flag needed.

Can you try with `bin/examples/qtwidgets_dockwidgets` and modify it until repro, then I can fix

**Comment by bbc131** [comment]
I'm closing this issue, since I cannot reproduce it as well.
I tried to mimic the configuration of my use case, but weren't able find the cause.
