### ISSUE TITLE
Unable to use the auto hide button and the float button together

### ISSUE THREAD

**Issue by Dr64h** [KDAB/KDDockWidgets#425]
Hello, i trying to display auto hide button and floating button together.

I tried to set `Flag_AutoHideSupport`, it shows auto hide button, but it also set `Flag_TitleBarNoFloatButton`, to have both buttons i set the last one to false. As far as I remember it worked before in previous versions,  but it doesn't work right now.

**Comment by iamsergio** [comment]
Hi, this requires providing your own custom titlebar now
