### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kozlovandrei** [KDAB/KDDockWidgets#43]
Hello. I cannot build project.

cmake -G Ninja
CMake Error: Could not find cmake module file: CMakeDetermineHOMEPAGE_URLCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER
CMake Error: Could not find cmake module file: /home/andrei/KDDockWidgets/CMakeFiles/3.10.2/CMakeHOMEPAGE_URLCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDeterminehttps://github.com/KDAB/KDDockWidgetsCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/KDAB/KDDockWidgets_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/KDAB/KDDockWidgets_COMPILER
CMake Error: Could not find cmake module file: /home/andrei/KDDockWidgets/CMakeFiles/3.10.2/CMakehttps://github.com/KDAB/KDDockWidgetsCompiler.cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_HOMEPAGE_URL_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_HOMEPAGE_URL_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.

CMake Error: Could not find cmake module file: CMakeHOMEPAGE_URLInformation.cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_https://github.com/KDAB/KDDockWidgets_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_https://github.com/KDAB/KDDockWidgets_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error: Could not find cmake module file: CMakehttps://github.com/KDAB/KDDockWidgetsInformation.cmake
CMake Error: CMAKE_HOMEPAGE_URL_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_https://github.com/KDAB/KDDockWidgets_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by iamsergio** [comment]
can you checkout 1b337b5391e95d147311740c90542bf177a6d6b7 and see if it builds ?

**Comment by kozlovandrei** [comment]
not building

**Comment by kozlovandrei** [comment]
Project is builded. I deleted line "HOMEPAGE_URL https://github.com/KDAB/KDDockWidgets" in file CMakeLists.txt.

**Comment by iamsergio** [comment]
Fixed in dc4a1975ab8b8ff6b4dc6c436975403469d41b61
