### ISSUE TITLE
Broken on WASM with QtQuick

### ISSUE THREAD

**Issue by msarehn** [KDAB/KDDockWidgets#441]
On WASM, `createDropIndicatorOverlay(Core::DropArea *dropArea)` always creates a SegmentedDropIndicatorOverlay:

```cpp
#ifdef Q_OS_WASM
    // On WASM windows don't support translucency, which is required for the classic indicators.
    return new Core::SegmentedDropIndicatorOverlay(dropArea);
#endif
```

However, the QtQuick platform has no "View" implementation of this, so the above will always crash ultimately. If the "Classic" indicators don't work, it would be good to return the Null indicators on WASM/QtQuick so that it doesn't crash, at least.

**Comment by msarehn** [comment]
Having just tried this, the "Classic" Indicators work just fine in WASM/QtQuick.

**Comment by iamsergio** [comment]
That makes sense. I'd like to test locally as well though, but I'm not getting any *.html file.

I ran:

```
$ source ~/emsdk/emsdk_env.sh
$ em++ --version # Needs to be 3.1.37 for Qt 6.6.0
$ cd KDDockWidgets/
$ ~/Qt/6.6.0/wasm_multithread/bin/qt-cmake --preset=wasm-release
$ cd build-wasm-release/
$ ninja kddockwidgets
$ ninja qtwidgets_dockwidgets
$ ninja qtquick_dockwidgets
```
And got files such as qtwidgets_dockwidgets.js  , qtwidgets_dockwidgets.wasm
but no html file as suggested by the Qt documentation

Did you do something different ?

**Comment by msarehn** [comment]
> And got files such as qtwidgets_dockwidgets.js , qtwidgets_dockwidgets.wasm but no html file as suggested by the Qt documentation
> 
> Did you do something different ?

The html files are created by [qt_finalize_target()](https://doc.qt.io/qt-6/qt-finalize-target.html) in CMake. In our code, I've just replaced all `add_executable()` calls with `qt_add_executable()`; recent CMake (3.19+) then does finalization automatically.
