### ISSUE TITLE
Install PDB files to binary instead of library location

### ISSUE THREAD

**Issue by bebuch** [KDAB/KDDockWidgets#444]
2.x branch, Windows 11, MSVC VS 2019, CMake 3.27

`.pdb` files should be installed to the `bin` directory along with the `.dll` files, not to the `lib` directory with the `.lib` files.

https://github.com/KDAB/KDDockWidgets/blame/bbf9a75b9dd8889375e9ceb72c54d0a8daaefb45/src/CMakeLists.txt#L578

**Comment by iamsergio** [comment]
has been merged
