### ISSUE TITLE
Window repaint issue when moving dockwidgets from main window to secondary monitor

### ISSUE THREAD

**Issue by dlinenbe** [KDAB/KDDockWidgets#46]
KDDockWidgets commit: 4e88b37
Windows 10
QT 5.14.2
When using 2 identical model side by side displays, each set to same display resolution, sliding a dockwidget panel from one monitor to the other monitor causes the dock widget panel to not repaint properly at right edge of window.  Slightly expanding/contracting the widget causes a repaint which will then paint properly.

Reproduce:
Launch example test app.  
Slide widget containing DockWidget #6, #7  & #8 to the other display.
Note dock widget on right hand side & bottom of window has a repaint issue.

This issue can also be reproduced by sliding a contained dock widget from one monitor to the 2nd monitor. Letting the widget stay in the 2nd monitor by releasing the drag button on the mouse. Then sliding the widget back to the original monitor and releasing the drag button on the mouse. 

![Annotation 2020-05-31 174726](https://user-images.githubusercontent.com/2024049/83363348-e0b26200-a366-11ea-97d5-782570d0c686.png)

**Comment by iamsergio** [comment]
what are the scaling factors on each monitor, and which graphics card ?
Would also be useful to know if it's repro with 5.15 thanks

**Comment by dlinenbe** [comment]
Each monitor is a DELL U2515H, using 2560 x 1440 resolution.
The graphics card is an NVIDIA GTX960.  Note when one of the monitors is set to a different resolution, the issue goes away - it is as if when the dock widget shifts its screen, it readjusts to the new resolution, forcing a repaint - and thus eliminating the problem. e,g,
if one monitor is at 2048x1152 and the other is at 2560x1440, there are no issues. But as soon as the monitors are the same (say, both 2048x1152, or both 2560 x1440, or both 1920x1080, the issue reappears) I can try under 5.15 and report...

**Comment by iamsergio** [comment]
Reproduced on 5.15 too, for now as a workaround you can disable Flag_AeroSnapWithClientDecos

**Comment by dlinenbe** [comment]
Yes. I reproduced under 5.15 as well. I disabled the flags and the issue was solved. 
Thank you!
