### ISSUE TITLE
Nested MainWindows on Linux

### ISSUE THREAD

**Issue by bbc131** [KDAB/KDDockWidgets#461]
Hi, I stumbled over `KDDOCKWIDGETS_SUPPORTS_NESTED_MAINWINDOWS`, which is not defined on Linux, but I would like to use this feature on Linux.

When I add this define also for Linux and play a bit with the `qtwidgets_dockwidgets` example with option `-j` on Ubuntu 23.04 with Qt5, I can't find any problem or difference to Windows.
Further I don't understand what the comment "... On linux the Qt::Tool windows need reparenting. ..." means.

Could the reasons for this distinction be outdated? If there is still a problem, what exactly is it? Is it something that can be fixed?

**Comment by iamsergio** [comment]
Hi, this has bugs in a few window managers, I can make a flag so it's easier to use, if you only need ubuntu.
Will document what the problem was

**Comment by bbc131** [comment]
Okay, 
would be nice to know the problems,
thanks
