### ISSUE TITLE
Problem with running qtquick example: (Please call KDDockWidgets::initPlatform()).

### ISSUE THREAD

**Issue by capNmo** [KDAB/KDDockWidgets#462]
Im trying to include KDDockWidgets in a new sample project. im using qtquick.
- windows 10
- qt5
   

-----
This is my project structure: 
root
├── CMakeLists.txt(1)
└── deps
-----└── bin
-----└── include
-----└── lib
└── SimpleProject
------└── CMakeLists.txt(2)
------└── main.cpp
------└── qml.qrc
------└── main.qml and other qml files in full example
   
   
-----
deps folder contains `KDDockWidgets`  build results (installation dir of it)
  
  
-----
CMakeLists.txt (1): (contains project and deps)
```
cmake_minimum_required(VERSION 3.15)
project(SimpleProject VERSION 0.2 LANGUAGES CXX)
set(deps "${CMAKE_CURRENT_SOURCE_DIR}/deps")
list(APPEND CMAKE_PREFIX_PATH ${deps})
list(APPEND CMAKE_MODULE_PATH ${deps}/lib/cmake)
add_subdirectory(SimpleProject)
```

-----
CMakeLists.txt (2): (contains project)
```
find_package(Qt5 COMPONENTS Core Quick Charts REQUIRED)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC TRUE)
set(CMAKE_AUTORCC TRUE)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(EXECUTABLE_NAME SimpleProject)

find_package(KDDockWidgets REQUIRED)

add_executable(${EXECUTABLE_NAME})
target_sources(${EXECUTABLE_NAME} PRIVATE
        main.cpp
        qml.qrc)
target_link_libraries(${EXECUTABLE_NAME} PRIVATE
        KDAB::kddockwidgets)
```

main.cpp and main.qml are copied from [Git example](https://github.com/KDAB/KDDockWidgets/tree/2.0/examples/qtquick/dockwidgets)

---  
When trying to build this error appears: 

```
__cdecl KDDockWidgets::QtCommon::Platform_qt::GlobalEventFilter::GlobalEventFilter(class KDDockWidgets::QtCommon::Platform_qt *) Expected a qGuiApp!
Please call KDDockWidgets::initPlatform() after QGuiApplication
QObject::connect(QGuiApplication, Unknown): invalid nullptr parameter
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
```

**Comment by iamsergio** [comment]
Does the git example itself work, if you build it directly from within examples/ ?

**Comment by capNmo** [comment]
Im not sure im doing it correctly... but i cloned project and opened it with QtCreator. my build result is a module that i can use it in other projects. but im not sure how to run The example in /example root.     
also there is no document about how to run the example.

**Comment by capNmo** [comment]
i did it this way... build was successful:
![image](https://github.com/KDAB/KDDockWidgets/assets/140580463/9039153b-db5c-45e7-904d-ec1c121f0195)

**Comment by capNmo** [comment]
yes build was successful is i run from the main project: 

![image](https://github.com/KDAB/KDDockWidgets/assets/140580463/b162f633-7ee8-4897-8ead-2adc91e17a0e)


but now i need to run it from another simple project that use `find_package(KDDockWidgets REQUIRED)`

**Comment by iamsergio** [comment]
Are you sure you kept the `KDDockWidgets::initFrontend` call ?

I don't know how this could happen.
If you upload a sample project that reproduces the problem I'll be happy to fix it there.
