### ISSUE TITLE
Build error at first step - target "kddockwidgets_multisplitter"

### ISSUE THREAD

**Issue by digitalboilermaker** [KDAB/KDDockWidgets#47]
Download commit 180fb96
> cd s:\KDDockWidgets-master
> cmake -DCMAKE_INSTALL_PREFIX=S:\KDDockWidgets

ERROR:
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at src/CMakeLists.txt:157 (install):
  install TARGETS given target "kddockwidgets_multisplitter" which does not
  exist in this directory.

-- Configuring incomplete, errors occurred!
See also "S:/QT/KDDockWidgets-master/CMakeFiles/CMakeOutput.log".

**Comment by iamsergio** [comment]
which CMake version ?
