### ISSUE TITLE
Qt Quick: crash when `delete`-ing a toplevel dockwidget

### ISSUE THREAD

**Issue by MiKom** [KDAB/KDDockWidgets#472]
## Environment
- Qt 6.6.2
- Windows 11
- Visual Studio 2022 compiler 19.38.33135 amd64

## Steps to reproduce:
1. Add a timer to `examples\qtquick\dockwidgets\main.cpp`:
    ```
    QTimer::singleShot(std::chrono::seconds(10), [&](){
        delete dw3;
    });
    ```
2. Run the application
3. Before the timer runs out, detach the Dock Widget 3 so it forms a separate window
4. Wait until the timer runs out

## Expected behavior
The window in which Dock Widget 3 resides, disappears, application keeps running

## Actual behavior
Application crashes:

https://github.com/KDAB/KDDockWidgets/assets/104767/3d24dd12-857f-40e9-9b4c-698cae86441a

Stacktrace:
https://gist.github.com/MiKom/4d7bb6c25e7b01cc39497f793af96959

**Comment by iamsergio** [comment]
fixed
