### ISSUE TITLE
Qt Quick: Crash when deleting dockWidget in MDI

### ISSUE THREAD

**Issue by MiKom** [KDAB/KDDockWidgets#473]
## Environment
* Qt 6.6.2
* Windows 11
* Visual Studio 2022 compiler 19.38.33135 amd64

## Steps to reproduce
1. Add the following code to `examples\qtquick\mdi\main.cpp`:
   ```
   QTimer::singleShot(std::chrono::seconds(3), [&]{
        delete dw1;
        delete dw2;
   });
   ```
2. Run the `qtquick_mdi.exe` example
3. Wait

## Expected result
`dw1` and `dw2` are properly deleted and disappear taking their children with them.

## Actual result

Application crashes with the following stacktrace:
https://gist.github.com/MiKom/e9fe77c45004a2139a8410ba0c90740e

**Comment by iamsergio** [comment]
Fixed in 18663268bb521733cac6df6418809f179cbe0a01
