### ISSUE TITLE
Move DockWidget programmically

### ISSUE THREAD

**Issue by Sara-Abdallah-97** [KDAB/KDDockWidgets#484]
Hi,

I have a question.

I want to adjust the DockWidgets layout (i.e. positions) if user clicked on a button. I tried to call `addDockWidget` again with the new position but seems it isn't fast So, thinking if there is a "moveDockWidget" function ?

 I use  qquick 
 
 Thanks!

**Comment by iamsergio** [comment]
Hi,

By "it isn't fast", you mean it doesn't work ?

If you change `examples/qtquick/dockwidgets/` to make it repro, and attach the patch here I can take a look at it
