### ISSUE TITLE
Broken "Toggle Another" Quick MDI example

### ISSUE THREAD

**Issue by dantti** [KDAB/KDDockWidgets#488]
qrc:/Guest1.qml:38: TypeError: Property 'close' of object KDDockWidgets::QtQuick::DockWidget(0x558d84775d60) is not a function

Indeed close() there is not Q_INVOKABLE nor Q_SLOT, couldn't think of a fix, this was using main branch.

**Comment by iamsergio** [comment]
Works here. Which Qt version ?

**Comment by dantti** [comment]
6.7.0 and 6.6.1 also gives "qrc:/Guest1.qml:37: TypeError: Type erro"

**Comment by dantti** [comment]
Could also reproduce with 6.4.1

**Comment by iamsergio** [comment]
ah, need to press the button twice.
Reproduced thanks
