### ISSUE TITLE
The display on the right side of the dock window is weird.

### ISSUE THREAD

**Issue by dawnrs** [KDAB/KDDockWidgets#500]
When I run the example program, the dock window is always weird at its right side.
![pic](https://github.com/KDAB/KDDockWidgets/assets/74943651/5d7b02d8-f3f9-48c9-8302-941803d6a959)
The windows from other apps or built by original Qt don't have problems like that on my computer.
I tested v2.0 and v1.7 which have the same problem.

Are there any method to fix this problem?
Thanks a lot.

**Comment by iamsergio** [comment]
Which OS and Qt version ?

**Comment by dawnrs** [comment]
@iamsergio 
Thank you for response.
The OS is "Windows 11 Insider Preview 26200.5001". 
And Qt Version is "6.6.1".

**Comment by iamsergio** [comment]
That's caused by QTBUG-117704

Qt 6.6.1 is not supported.
6.6.2 should be good.
