### ISSUE TITLE
Is the installed version available?

### ISSUE THREAD

**Issue by lpiert** [KDAB/KDDockWidgets#521]
Why are there no examples out of source, is cmakelist.txt from release 2.1 complete? The generated version of the install simply doesn't work. Generated files are missing, header file dependencies are missing and confusing.

**Comment by iamsergio** [comment]
The instructions to build example against an installed KDDW are here: 

https://kdab.github.io/KDDockWidgets/installation_and_usage.html

Please follow that, and if it still doesn't work, paste here the commands you ran and respective output and reopen this issue.
