### ISSUE TITLE
It is possible to change the title bar color for toggle active state for a dock widget?

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#56]
Hi,
my goal is to have a different title bar color if the dock widget is "active".
I (re)implemented the "MyTitleBar" in the kddockwidgets example:
```
void paintEvent(QPaintEvent*) override
	{
		QPainter p(this);
		QColor c = isActiveWindow() ? QColor("#F28D26") : Qt::gray;
		p.fillRect(rect(), c);
		p.drawText(rect().adjusted(5, 0, 0, 0), Qt::AlignLeading | Qt::AlignVCenter, title());
	}

```
But this is not right. It changes the title bar color if the whole window is active. I would like to change the color for dock widget.

The following animation shows that only the whole window is changing the color and not the dock widget.

![active_dock_widget](https://user-images.githubusercontent.com/3143027/89543040-bd8dae00-d800-11ea-8678-f1c4090cd8f7.gif)

In Visual Studio it is possible to change the "active" color of each docking window.
![active_dock_widget_visual_studio](https://user-images.githubusercontent.com/3143027/89543047-c1213500-d800-11ea-92b4-4d97dec99f8d.gif)

Greetings,
Thomas

**Comment by iamsergio** [comment]
I'll see what I can do :)

**Comment by tlaemmlein** [comment]
Thank you!

**Comment by tlaemmlein** [comment]
We need a notify mechanism (Qt signal), that the active/focus state has changed. Is there still something available?
