### ISSUE TITLE
Inform the underlaying widget if docked or floating state is entered

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#58]
Hi, 
we have widgets which will display different gui elements (e.g. toggle visiblity of a toolbar) depending if the dockwidget is docked or is a flaoting window.
It would be great if the underlaying widget will be informed if the dockwidget is docked or floating.
I have prepared two suggestions with connecting signal/slot:
![image](https://user-images.githubusercontent.com/3143027/89893023-e8e51400-dbd7-11ea-929a-90b888edcd80.png)

Or do you have already a solution for this?
Greetings,
Thomas

**Comment by iamsergio** [comment]
Can you try: connect(dock->floatAction(), &QAction::toggled ?

**Comment by tlaemmlein** [comment]
Thank you. This works.

**Comment by tlaemmlein** [comment]
Unfortunately there is still an bug in it. If you have two docked widgets in it own "widget" window (Mean it is not in the main window) and you drag  one of the docked widget to a floating dock widget, then the dragged widget is marked as floating, but the unmoved widget is still "not floated" which is wrong because both widgets become floating.
The following animation shows the effect. The first part show the float/not float effect with the main window which is ok. But the second part shows the wrong behaviour with a "widget" window.
![Floting_or_not_Floating_is_the_question](https://user-images.githubusercontent.com/3143027/90011885-a89e9800-dca2-11ea-8162-3f77ba9cb36e.gif)

Kind Regards,
Thomas
