### ISSUE TITLE
Notify mechanism (Qt signal), that the active/focus state has changed

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#60]
We need a notify mechanism (Qt signal), that the active/focus state has changed. Is there still something available?
This regards issue #56

**Comment by iamsergio** [comment]
Do you need the signal in DockWidget class ?

**Comment by tlaemmlein** [comment]
Yes. The easiest way would be a qt signal in the DockWidget. Maybe you can implement in a simliar way like the other QAction's in DockWidgetBase?

DockWidgetBase.h
  /**
     * @brief Returns the QAction that allows to hide/show the dock widget
     * Useful to put in menus.
     */
    QAction *toggleAction() const;

    /**
     * @brief Returns the QAction that allows to dock/undock the dock widget
     * Useful to put in menus.
     */
    QAction *floatAction() const;

   QAction * focusAction() const;
...
MyMainWindow.cpp:
...
connect(dock->focusAction(), &QAction::toggled, w, &MyWidget::focusToggled);
...
But it is in your hand hwo to do this.
Thanks,
Thomas
