### ISSUE TITLE
Why are some Widgets private?

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#61]
I'm wondering why some widgets are private.
I'm as a user of the library I see this "interface":
|   Config.h
|   docks_export.h
|   DockWidget.h
|   DockWidgetBase.h
|   FocusScope.h
|   FrameworkWidgetFactory.h
|   KDDockWidgets.h
|   LayoutSaver.h
|   LayoutSaver_p.h
|   MainWindow.h
|   MainWindowBase.h
|   QWidgetAdapter.h
|   
+---multisplitter
|       Item_p.h
|       multisplitter_export.h
|       Separator_p.h
|       Separator_qwidget.h
|       Widget.h
|       Widget_qwidget.h
|       
\---private
    |   Draggable_p.h
    |   DropIndicatorOverlayInterface_p.h
    |   FloatingWindow_p.h
    |   Frame_p.h
    |   TitleBar_p.h
    |   
    \---widgets
            FloatingWindowWidget_p.h
            FrameWidget_p.h
            QWidgetAdapter_widgets_p.h
            TabBarWidget_p.h
            TabWidgetWidget_p.h
            TabWidget_p.h
            TitleBarWidget_p.h
For example I can reimplement/inherit from TitleBarWidget which is located in private/widgets/TitleBarWidget_p.h.

It is strange to use something from a "private" folder. If I use for exmaple QToolBar https://doc.qt.io/qt-5/qtoolbar.html it is not hidden in a private folder.

Furthermore in the documentation the "private" classes/types  are not listed (https://docs.kdab.com/kddockwidgets/latest/annotated.html). Of course I can change the doxygen configuration to list the private classes, but for me there aren't private.

For me it is interessting to see the inheritance graph to have a feeling how the classes relate to each other.

Kind Regards,
Thomas

**Comment by iamsergio** [comment]
To continue your Qt example analogy:

Qt, just as KDDW, has public and private headers, for example qtoolbar_p.h is private, while qtoolbar.h is public.
The difference is that for public headers there's a promise of ABI and API stability, also more documentation, while for private, Qt can change them in incompatible ways without warning its users.

Both Qt and KDDW allow advanced users to use the private API, for more custom usage, at their own risk and without documentation.

**Comment by tlaemmlein** [comment]
Thanks. I understand.
