### ISSUE TITLE
Removable Title bar with docked Tab Widgets.

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#64]
Hi, 

we find that the title bar occupies so much space, specially when Docked and has more Tabs with in the dock widget. In our product we are trying to eliminate the title bar if the widget has more than one tab and is docked to another widget.
In the attach you shall find 3 different screen shots. 
In MainWindow pic, 
<img width="558" alt="MainWindow" src="https://user-images.githubusercontent.com/8441461/91171038-1a7ed480-e6da-11ea-94a7-45274cf571bc.png"> we would want to remove titlebar dockwidget#4.
<img width="280" alt="FloatingWindow" src="https://user-images.githubusercontent.com/8441461/91171189-60d43380-e6da-11ea-9bc8-b482e066bb14.png">

However we would like to keep the title bar if the widget is floating, as seen in FloatingWindow pic.

Would it be possible for you to provide such an option or interface.

Kind Regards
Nandish

**Comment by nandishnan4** [comment]
Not just when docked to Mainwindow, but in general, please find in the below pic 
<img width="235" alt="DockedInsideFloatingWindow" src="https://user-images.githubusercontent.com/8441461/91171479-d213e680-e6da-11ea-9f08-13fde4d465aa.png">
we would like to remove the title bar newdock3, but the newdock 4 remains.

Kind Regards
Nandish

**Comment by iamsergio** [comment]
I don't see why not, thanks for the suggestion.

In order for me to prioritize this, which company is this for ?
Or if open-source, the url please. If I like it I'll hack on this on my free time over the weekend. 
If it's for a closed app for a company I'll need some due diligence and ask KDAB to schedule me time for it.

Alternatively, you can just wait for after the QtQuick port is done, in a few months.

**Comment by nandishnan4** [comment]
Hi Sergio, thanks for quick response, we are using it here in MVTech Software Gmbh.
The profiles tlaemmlein, and pklaffert are my colleagues, you might have already seen the issues raised by my colleagues as well.

Kind Regards
Nandish

**Comment by mola** [comment]
Hi,   you can hide all titlebars.when you want to work with them, show them.
`    for (auto dock : m_dockwidgets)'
'    {'
'      auto f = dock->titleBar();'
''
'      if (f)'
'      {'
'        f->setVisible(!e);'
'     }'
'    }'
`

**Comment by iamsergio** [comment]
So basically, like kddockwidgets_example -t ?

-t will hide the title bars and you drag by the tab bar instead

Except that you want the title bar for the floating window, so that's the only change needed here ?

**Comment by nandishnan4** [comment]
Yes, something very similar, if the window is floating and has more than one tabs, we need to have the title bar. As soon as this floating widget is docked (either on another widget or mainwindow) we would want to hide the title bar.

**Comment by nandishnan4** [comment]
> 
> 
> Hi, you can hide all titlebars.when you want to work with them, show them.
> 
> ```
> for (auto dock : m_dockwidgets)
>     {
>       auto f = dock->titleBar();
> 
>       if (f)
>       {
>         f->setVisible(!e);
>      }
>     }
> ```

**Comment by nandishnan4** [comment]
Thanks for the response mola, but in this method, we do hide all the title bar. We specifically need to hide the title bar only if the dock widget has more than one tab and it is docked.

**Comment by nandishnan4** [comment]
Sorry Closed the issue by mistake.

Regards
Nandish

**Comment by iamsergio** [comment]
Try  ./bin/kddockwidgets_example -qt

Which means:
Config::Flag_HideTitleBarWhenTabsVisible | Config::Flag_AlwaysTitleBarWhenFloating

**Comment by nandishnan4** [comment]
Sure I shall look into it, thanks again for the efforts.

Kind Regards
Nandish
