### ISSUE TITLE
Dock widgets reusage

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#66]
Hello! How can I safely delete previous widget and insert another one into DockWidget?
Do I have to assign another unique name to dock widget in the same MainWindow instance, if I recreate dock widget itself?

**Comment by iamsergio** [comment]
Simply dockWidget->setWidget(newWidget) should work
If it doesn't then it's a bug I need to fix, can you check if it works ?

**Comment by arietto** [comment]
Simple setWidget calls abort: `Q_ASSERT(w && !d->widget);`

**Comment by arietto** [comment]
https://forum.qt.io/topic/56880/calling-setwidget-a-second-time-on-qdockwidget/4

**Comment by iamsergio** [comment]
does simply removing the assert work ?
I'll have a look on monday

**Comment by arietto** [comment]
Simple removing the assert will lead to memory leak, because old instance won't be deleted.
void DockWidgetBase::setWidget(QWidgetOrQuick *w)
{
    Q_ASSERT(w && !d->widget);
    qCDebug(addwidget) << Q_FUNC_INFO << w;

    d->widget = w;
    setSizePolicy(w->sizePolicy());

    Q_EMIT widgetChanged(w);
    setWindowTitle(uniqueName());
}
