### ISSUE TITLE
Calling close before DockWidget reusage

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#67]
Hello! The question is about resetting DockWidget. When I simply remove widgetA after calling setWidget(widgetB), then I've got empty area besides widgetB. Do I have to call `close()`/`forceClose()`?

    dock->setWidget(widgetA);
    dock->close(); // or forceClose()?
    dock->setWidget(widgetB);
    delete widgetA;

**Comment by arietto** [comment]
Due to #https://github.com/KDAB/KDDockWidgets/commit/ae000e75bc311098d0d3b4441133c8c5e35d89e9
I have to store pointer to previously added widget outside dock when I want to replace widget. 
Calling `delete dock->widget();` is invalid (leads to dangling internal pointer).
Does it make sense to add something like `removeWidget()`, which calls close(), then deletes widget? Thus, reusage will be less verbose and less error prone.

**Comment by arietto** [comment]
I am sorry, the problem was in `QPointer::clear()` usage. I thought that it deleted tracked object (my widget) too.
So, using `close()`/`forceClose()` is redundant.

**Comment by iamsergio** [comment]
ah, great :)
