### ISSUE TITLE
IsDockedToMainWindow() 

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#69]
Hi Sergio,

could you please provide an interface like IsDockedToMainWindow() which informs if the dock widget is docked to mainWindow or if its docked to some other dock widget. 
For example in the attach, 
<img width="558" alt="MainWindow" src="https://user-images.githubusercontent.com/8441461/92386572-540d0200-f114-11ea-9007-cc1f87c47a18.png">

Dockwidget 1, 3,4,5,8 are docked to Mainwindow and should return true. 

For example in attach
<img width="235" alt="DockedInsideFloatingWindow" src="https://user-images.githubusercontent.com/8441461/92386745-afd78b00-f114-11ea-9708-5521264848c9.png">

Dockwidget 0,3,4 are not docked to mainwindow and should return false.

Dockwidget->IsDockedToMainWindow().

I have a requirement to dock the widget or float depending on if the widget is docked to main window or not.

Kind Regards
Nandish

**Comment by tlaemmlein** [comment]
It would be great, if there is also a IsDockedToMainWindowChanged() Qt signal. Or even better: a Q_PROPTERTY "DockedToMainWindow".

**Comment by iamsergio** [comment]
Added DockWidget::isInMainWindow().
Signal will come later this week

**Comment by nandishnan4** [comment]
Hello Sergio, 
unfortunately isInMainWindow() does not work as we expect it to work.

I just added below piece of code, in constructor of MyMainWindow.cpp

    auto checkIsinMainWindowAction = fileMenu->addAction(QStringLiteral("Is in MainWindow"));
    connect(checkIsinMainWindowAction, &QAction::triggered, this, [&]() {
        for (int i = 0; i < m_dockwidgets.size(); i++)
        {
            if(m_dockwidgets[i]->isInMainWindow())
                qDebug() << m_dockwidgets[i]->windowTitle() << "is on main window";
        }
    });

On the console output I see the below messages.
+40-120) margins: 0, 0, 0, 0 minimum size: 80x150 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=160,300 maxtrack=0,0)
"DockWidget #0" is on main window
"DockWidget #1" is on main window
"DockWidget #2" is on main window
"DockWidget #3" is on main window
"DockWidget #4" is on main window
"DockWidget #5" is on main window
"DockWidget #6" is on main window
"DockWidget #7" is on main window
"DockWidget #8" is on main window

Even though few widgets were not directly to mainwindow.
Could you please have a look at this. 

Kind Regards
Nandish
