### ISSUE TITLE
A click on tabs there is no focus changed

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#70]
With the flag KDDockWidgets::Config::Flag_TitleBarIsFocusable the title bar is able to get the focus changed. 
But the tabs we need the same functionality. A click on a tab the focus changed signal should be emitted.
In the following animation I started the example with "-p". So the content and the title bar react on the click event, but not the tabs:
![Click_on_tab_No_Focus](https://user-images.githubusercontent.com/3143027/92394655-35156c80-f122-11ea-8588-b1735e663693.gif)
This even more important, if the titlebar is hidden.
Kind Regards,
Thomas

**Comment by iamsergio** [comment]
yeah, what happens is that changing tabs doesn't change focus in Qt, as the tabs don't get keyboard focus when clicking on them. So from the focus machinary point of view nothing changed.

But I think it makes sense to include this situation too

**Comment by iamsergio** [comment]
(for tomorrow)
