### ISSUE TITLE
The focus is not set when you click on a current tab

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#71]
Thank you for https://github.com/KDAB/KDDockWidgets/issues/70.
Unfortunately, the focus is not set when you click on a current tab.
![Click_on_current_tab_does_not_change_focus](https://user-images.githubusercontent.com/3143027/92881299-232c1600-f40f-11ea-8d8c-110ce7dbe925.gif)
Greetings,
Thomas

**Comment by iamsergio** [comment]
commit 85cb289bc46a17788775f98ed6d4af36076d8d10 (HEAD -> master, origin/master)
Author: Sergio Martins <sergio.martins@kdab.com>
Date:   Mon Sep 14 21:08:48 2020 +0100

    Also focus when clicking on the current tab
    
    Fixes issue #71
