### ISSUE TITLE
QProperties in DockWidgetBase

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#73]
Hi,
it would be great, if DockWidgetBase have QProperties. At the moment the class interface is not uniform. Example:
The focus has a Qt signal:
connect(dockWidget, &KDDockWidgets::DockWidget::isFocusedChanged, ui->isFocusCheckBox, &QCheckBox::setChecked);
But for floating I must use the corresponding QAction:
connect(dockWidget->floatAction(), &QAction::toggled, ui->isFloatingCheckBox, &QCheckBox::setChecked);

Here are some suggested QProperties:
![image](https://user-images.githubusercontent.com/3143027/93086172-0144c480-f697-11ea-96c5-bea8777674e8.png)

Furthermore for using GammaRay all QProperties will be displayed:
![image](https://user-images.githubusercontent.com/3143027/93086279-2d604580-f697-11ea-8219-1c1af8c28465.png)

Kind Regards,
Thomas

**Comment by iamsergio** [comment]
I've added isFocused and isFloating. The others are not trivial to add, they might need the signal emitted in multiple-places.
Closing for now, I don't feel very strongly about adding the rest
