### ISSUE TITLE
Scaling problem if flag aero snap is disabled

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#78]
There is a scaling problem with the kddock widgets example. How to reproduce:
2  screens (100% and 150%)
Build the example with
flags &= ~KDDockWidgets::Config::Flag_AeroSnapWithClientDecos;
The animation explains the rest:
![scaling_problem_no_aerosnap](https://user-images.githubusercontent.com/3143027/93866376-d9bdaf80-fcc7-11ea-8b1f-8b5d28195edb.gif)
The behaviour is crashing the application (like in this animation) or the dock widget is getting bigger/smaller.

**Comment by iamsergio** [comment]
I think I rather make aero-snap unconditional, to make Windows handle the resizing and the screen-changes, as Qt has bugs when doing it manually.

Any problem with aero-snap, besides issue #46 ?

**Comment by tlaemmlein** [comment]
Unfortunately I have to report that even with "aerosnap" the scaling problem is not completely eliminated. I can reproduce the problem with by sliding the DockWidget back and forth on both screens several times.
Qt-Version: 15.5.1
OS: Windows 10
In the animation I cut the movements to go faster to the problem:
![scaling_problem_with_aerosnap](https://user-images.githubusercontent.com/3143027/93874214-543ffc80-fcd3-11ea-89f5-cd6a82632a7f.gif)

The code is based on https://github.com/KDAB/KDDockWidgets/commit/6a46744073e96d6d26ca8c7b21dbe96f9bd06188

**Comment by tlaemmlein** [comment]
And also in our large applications the scaling problem is always there. Regardless of whether aero-snap is on or off.

**Comment by iamsergio** [comment]
reproduced the problem with Aero enabled, it happens when:

- the floating window is in between screens when the drag starts
- or, if you detach a docked widget and drag it all the way to a second screen

I have a WIP to fix it, but needs more polish

**Comment by tlaemmlein** [comment]
After a discussion with my team, I try to implement a work around. Our idea is to resize the dockwidgetbase after a screen change.
