### ISSUE TITLE
Qt Creator plugin?

### ISSUE THREAD

**Issue by mateoconlechuga** [KDAB/KDDockWidgets#80]
Any plans for a Qt Creator plugin for the UI form editor? Or is there already a way to use a QWidget as a placeholder and grab child widgets from it?

Anyway I love the docking mechanisms, this is orders of magnitude better than QDockWidgets.

EDIT: I consider this a low-priority feature, as the Qt Creator interface is a pain on its own. But it could be a nice-to-have I guess.

**Comment by iamsergio** [comment]
I don't have any plans or motivation for a QtDesigner plugin, but if you write something let me know and I'll add a link to your plugin in the KDDW readme
