### ISSUE TITLE
Scaling of main display is used instead of scaling of current

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#83]
Setup:
Two displays
First 100% scaling
Second 150% scaling

Case 1:
First monitor is main display, application runs on first monitor:
![image](https://user-images.githubusercontent.com/11087133/94413637-a40f3f80-017b-11eb-9d4b-9ef7a2d2cb9a.png)

Case 2:
Second monitor is main display, application runs on first monitor:
![image](https://user-images.githubusercontent.com/11087133/94413762-d0c35700-017b-11eb-903b-94b77ce679ab.png)

As you can see, the font in case 2 is too small.

**Comment by pklaffert** [comment]
Sorry, forgot to mention.
Windows 10

**Comment by iamsergio** [comment]
Qt 5.15 ?
And which base style ? Can you repro with kddockwidgets_examples ?

**Comment by pklaffert** [comment]
Hi sorry, again forgot to include information.
Qt Version: 5.15.1

Screenshot is from the minimal example with no code changes. Just a fresh pull and build.

**Comment by iamsergio** [comment]
This bug is unrelated to KDDockWidgets, it happens with any Qt app.
Here's a minimal Qt example without KDDockWidgets.

Bug should be fixed in Qt or in your app, KDDockWidgets doesn't do any font size manipulation.


```
#include <QtWidgets>

int main(int a, char **b)
{
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QApplication app(a, b);

    QWidget widget;
    auto lay = new QVBoxLayout(&widget);

    auto button1 = new QPushButton("one");
    auto button2 = new QPushButton("two");
    auto button3 = new QPushButton("three");

    lay->addWidget(button1);
    lay->addWidget(button2);
    lay->addWidget(button3);

    widget.resize(500, 500);
    widget.show();

    return app.exec();
}
```


<img width="251" alt="test-case" src="https://user-images.githubusercontent.com/20387/94587168-18c8a380-027a-11eb-948e-9c6e7201b848.png">
