### ISSUE TITLE
Unexpected resize of the docked widgets.

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#84]
Hello Sergio, 

please take a look at the below gif, the docked widget is resized every time it is docked back to the main window. Normally this behavour is not expected, user expects the docked widget size to be retained. 
![DockedWidgetResizeBug](https://user-images.githubusercontent.com/8441461/94449585-86a69980-01ac-11eb-815c-e8cb88abec8f.gif)

If you need more information, please feel free to contact.

Kind Regards
Nandish

**Comment by iamsergio** [comment]
reproduced
