### ISSUE TITLE
Docking many dockables into a floating window makes the application hang.

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#92]
Setup:
Windows 10
Qt Version: 5.15.1
Current KDDW example

To reproduce:
- Start the example
- File -> Close All 
- File -> New DockWidget 15 Times*

This will create 15 floating dock widgets. Now start docking them into one floating widget, not into the mainwindow.
After a while the docking process will take more and more time until the application will hang and the cpu load in the task manager will be quite high constantly.

The attached .gif shows the problem. You also can see here, that the dock indicators are not shown every once in a while.

![dock-float-hang](https://user-images.githubusercontent.com/11087133/95764259-7f08e980-0cb0-11eb-8684-5a982ef14a14.gif)

[*] if 15 is not enough, try more

**Comment by iamsergio** [comment]
reproduced
