### ISSUE TITLE
No high res icons on windows with desktop scaling is fractional

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#94]
Using:
Qt: 5.15.1
KDDW: 1.1 branch latest
Windows 10

Having fractional scaling turned on e.g. 150% Desktop scaling I only get the low-res version of the icons e.g. titlebar close.

Digging through the code I found the following snippet:

```
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 2)
  const bool isFractional = int(dpr) != dpr;
  if (isFractional) {
    // We don't support 1.5x yet.
    // Linux is the only one affected as Windows and macOS use integral factors.
    // Problem with Linux is that rendering is off due to a rounding bug only fixed in 5.15.2
    // Will enable for fractional later.
    // QTBUG-86170
    return icon;
  }
#else
```

Which is not true. Since Qt 5.15.0 windows applications also can use fractional scaling by setting 
`  QApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
`

**Comment by iamsergio** [comment]
I'll give it a try on Windows, but can't promise it's not affected by the same Qt bug

**Comment by iamsergio** [comment]
I've fixed the comment about it affecting only Linux.
The bug is fixed in Qt and no workaround is possible in KDDW
Upgrade to 5.15.2 once out
