### ISSUE TITLE
Initial dock size

### ISSUE THREAD

**Issue by AV9** [KDAB/KDDockWidgets#95]
Hi,

How can I set the initial size of the docks? Calling the function resize(int w, int h) from the dock widget is not changing anything...

Any suggestion?

Thanks!

**Comment by iamsergio** [comment]
Do you mean the initial size when floating (top-level dock widget) or when docked ?
And which version/sha1, thanks

**Comment by AV9** [comment]
When docked.

**Comment by iamsergio** [comment]
there's no way
Shouldn't be much work to impl. Just not sure what the API should look like though.

**Comment by Daguerreo** [comment]
@iamsergio I see this has been implemented, however could you show a sample code to show how to do that?
