### ISSUE TITLE
Tabbed windows cannot be re-docked.

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#96]
Hi Sergio,

when a widget is un-docked, it can be re-docked by clicking on the button at the right top corner. However this does not work if we have two or more widgets tabbed together before they were un-docked.

The Giff in attach explains the problem more clearly.
If you need more information, please feel free to contact. 

![TabbedGrpReDock](https://user-images.githubusercontent.com/8441461/98942229-0040df80-24ee-11eb-95ca-6f40afe705b8.gif)

Further more, the tabbed windows are re-docked to main window and not the floating window they were previously docked to. 
I expect dockwidget 2 to get docked to dockwidget 0 in this case. But both the windows get docked to MainWindow.

Please find the Giff in attach which explains the problem.
![TabbedGrpReDock1](https://user-images.githubusercontent.com/8441461/98953041-78160680-24fc-11eb-9a75-b116d04ff4a8.gif)

If you need any more information, please feel free to contact.

Kind Regards
Nandish

**Comment by iamsergio** [comment]
This is #44 , not trivial to fix quickly, but on my todo list

**Comment by iamsergio** [comment]
Let's continue in #44

**Comment by tlaemmlein** [comment]
@iamsergio 
Do you think a workaround could be to disable the 'dock' button if the widgets are tabbed? Then it is more clear rather than have a 'clickable' button which do nothing.
Kind Regards,
Thomas

**Comment by iamsergio** [comment]
@tlaemmlein ok I will disable the dock button

**Comment by tlaemmlein** [comment]
@iamsergio What is the current status of this issue?

**Comment by iamsergio** [comment]
@tlaemmlein will be scheduled for March

**Comment by iamsergio** [comment]
It's fixed for me now

**Comment by tlaemmlein** [comment]
@iamsergio Thank you for the fix. Can you merge the fix into the 1.5 branch? Greetings, Thomas

**Comment by iamsergio** [comment]
Maybe it will be a 1.6 release, need to check
