### ISSUE TITLE
Floating windows are disapearing under Linux with KDE (example: SUSE)

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#98]
We face the problem that floating windows are disapearing under a Linux which has KDE as the window manager (For example SUSE).
Steps to reproduce:
Req.: openSUSE 15.1

Use case 1
- Start kddockwidgets_example and open at least one floating window
- Click outside the kddockwidgets_example application
- Observe that the floating window is hidden
- Click inside the kddockwidgets_example application
- Observe the floating window is shown again
If you set the window behavior policy to "focus under mouse" then problem occurs with moving the mouse outside the kddockwidgets_example application.
![kddockwidgets_example_floating_wnd_disapears](https://user-images.githubusercontent.com/3143027/98961264-aba95e80-2505-11eb-9c9e-f692d2656455.gif)

Use case 2
- Start kddockwidgets_example -u
 and open at least one floating window
- Perform the same step like use case 1
- Observe the floating window does not disapears
![kddockwidgets_example_floating_wnd_as_no_util_widget_does_not_disapear](https://user-images.githubusercontent.com/3143027/98961302-b49a3000-2505-11eb-8fd6-b5ffad0d85de.gif)

The expected solution is that the use case 1 is fixed.

Kind Regards,
Thomas

**Comment by iamsergio** [comment]
```
#include <QtWidgets>

int main(int argc, char **argv)
{
    QApplication app(argc, argv);

    QWidget mainWindow;
    QWidget secondaryWindow(&mainWindow, Qt::Tool);

    mainWindow.resize(500, 500);
    secondaryWindow.resize(500, 500);

    mainWindow.show();
    secondaryWindow.show();

    return app.exec();
}
```
Can you modify this minimal Qt testcase (non-KDDW) in a way that it shows the desired behaviour in KWin ?

If it's not possible with a Qt non-KDDW example then it won't be possible with KDDW (as KDDW uses Qt)

(Spoiler alert: It's a Kwin behaviour, you can't have pure Qt::Tool windows with transient parent that don't disappear when focus shifts)

**Comment by tlaemmlein** [comment]
I understand. Thanks.
